### ISSUE TITLE
Option for Using HTML in Roundcube Canned Responses

### ISSUE THREAD

**Issue by VyperPrecisionCorporation** [roundcube/roundcubemail#7942] opened 2021-03-14 02:47 UTC
**An issue I have and that I feel needs fixed or implemented is using HTML in the Canned Responses. I do not understand why HTML cannot be used in Canned Responses if it can be used to send or reply to other emails. I would love to have this feature implemented. Currently, if you use HTML in a Canned Response, it shows up as Text so that is not even an option. Please review this Issue & Implement the use of HTML in Canned Responses.**

**Comment by alecpl** [comment] 2021-03-14 06:42
Duplicate of #5315

**Closed by alecpl** 2021-03-14 06:42 UTC
