### ISSUE TITLE
Doubleclicking an item in the mailbox view, doesn't open mail anymore

### ISSUE THREAD

**Issue by tomsommer** [roundcube/roundcubemail#5823] opened 2017-06-28 07:27 UTC
Since 1.3.0, double-clicking an item in the mailbox view, doesn't open the mail anymore.

Pressing ENTER on a highlighted mail works.

**Comment by alecpl** [comment] 2017-06-28 07:40
This is an intentional change. It was needed because we wanted to eliminate 500ms delay in message loading on a single click. We can't do this with double-click handler enabled. So, double-click is working only if you have the preview pane hidden. So, wontfix.

**Comment by tomsommer** [comment] 2017-06-28 07:43
Might want to add stuff like this to the release notes.

**Comment by tribut** [comment] 2017-07-02 21:46
What about enabling the double click handler only for the currently selected mail? Might that be a reasonable compromise?

**Comment by alecpl** [comment] 2017-07-03 06:05
If the message is open you have "Open in new window" button. So, I don't see a difference.

The implementation might not be so simple as event handling on the list widget is quite complicated. It's because we use custom drag-n-drop functionality. Maybe some day we could switch to standard drag-n-drop API, then it would be simpler.

**Comment by tomsommer** [comment] 2017-07-03 07:24
Well, the problem is that people expect double-click to work because:
1) It worked before
2) It works in native OS-apps
3) It works in other webmail apps
4) It works in list-mode

It's going to be a huge undertaken to educate users that this "doesn't work" and the reason (500ms delay) is not something they will ever understand.

So it would be really nice to have this fixed somehow.

**Comment by tribut** [comment] 2017-07-03 08:30
I've had several people complain to me about this and they did find the "open in new window button" eventually but I believe the problem is that when people switch from Outlook at work to Roundcube at home getting rid of the impulse to double click when they want to open a message in a new window is a long and frustrating process. It directly contradicts the "don't make me think" mantra every time they switch, which is at least once per day.

**Comment by tomsommer** [comment] 2017-07-03 09:15
Well, the usability of the "Open in new window"-button is also questionable. It's well hidden and nobody can just tell what it does. but that's a general thing in the Roundcube UI (like the layout-setup button) ;)

**Comment by thomascube** [comment] 2017-07-10 19:36
I agree with Tom and others that this issue should be put back on the agenda and Roundcube 1.3.1 should bring back the old behavior. Asking users to change their behavior because of technical reasons ist what software vendors did in the 1990s.

I'm sure we can find a technical compromise to improve preview loading times even with the double-click feature. For example wait for 250ms (or 200) with loading the preview and if still a double-click is detected, abort the load. That's still a factor two improvement and as @tribut suggested, it's likely that users double-click on the already selected (and loaded) message.

**Comment by 2ndGAB** [comment] 2017-07-28 06:02
I agree with Tom, removing this obviously very ergonomic and intuitive feature is a VERY VERY VERY bas idea!

**Comment by thomascube** [comment] 2017-08-11 14:08
FWIW, the feature was removed upon issue #5199

**Comment by thomascube** [comment] 2017-08-11 15:21
Restored double-click handler with an improved behavior as suggested in #5199. This of course comes with the trade-off that with the preview frame open, the double-clicked message is opened twice now.

Please test with git master, feedback is welcome.

**Comment by thomascube** [comment] 2017-08-23 20:08
Backported for 1.3 release branch

**Closed by thomascube** 2017-08-23 20:08 UTC

**Comment by tjharman** [comment] 2017-09-04 20:45
Thank you, thank you, thank you.
