### ISSUE TITLE
Empty contact list in Contacts tab

### ISSUE THREAD

**Issue by xabispacebiker** [roundcube/roundcubemail#5971] opened 2017-09-26 08:31 UTC
Clicking on the Contacts tab displays an empty contact list. After checking in the database I could confirm the contacts were there. Roundcube throws the following error line:

[26-Sep-2017 10:19:23 +0200]: <f0be3u1q> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows FROM `contacts` AS c WHERE c.`del` <> 1 AND c.`user_id` = '10'' at line 1 (SQL Query: SELECT COUNT(c.`contact_id`) AS rows FROM `contacts` AS c WHERE c.`del` <> 1 AND c.`user_id` = '10') in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 540 (GET /?_task=addressbook&_action=list&_source=0&_remote=1&_unlock=loading1506413965049&_=1506413964977)

The error seems to be the "rows" term that conflicts with MariaDb. I modified the file /usr/share/roundcube/program/lib/Roundcube/rcube_contacts.php and changed all references from "rows" to "nrows" and it worked.

Roundcube Webmail 1.2.3
mysql  Ver 15.1 Distrib 10.2.6-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by alecpl** [comment] 2017-09-26 09:28
Duplicate of #5774. Fixed in 1.2.6.

**Closed by alecpl** 2017-09-26 09:28 UTC
