### ISSUE TITLE
Feature Request: Favorite folders to display them on top of the list

### ISSUE THREAD

**Issue by MarcoRemy** [roundcube/roundcubemail#8745] opened 2022-10-13 11:40 UTC
Hi everyone. May I'm not the only one managing a lot of folders. Some of them are used more frequently than others. If they are located at a lower part of the ordered list you have to scroll all the way down to interact with them. To improve UX it would be great to kind of favorite [⭐] folders so they would be displayed/mirrored first in the list.

**Comment by alecpl** [comment] 2022-10-18 06:43
Duplicate of #5003.

**Closed by alecpl** 2022-10-18 06:43 UTC
