### ISSUE TITLE
"Empty" moves the emails into Trash folder from Junk

### ISSUE THREAD

**Issue by ozgurkazancci** [roundcube/roundcubemail#9078] opened 2023-07-25 21:43 UTC
Greetings.

While having "$config['delete_junk'] = true;", clicking a mail inside the "Junk" folder then "Delete" icon at the upper-top right bar deletes the email directly without moving to Trash bin, as it's supposed to. That's good.

However, when the Junk folder is full and clicking to the "Empty" choice from the tool menu on it (Three dots on top), moves the emails from there into Trash folder, instead of erasing them completely.

Is that completely expected behaviour? (Again, considering "$config['delete_junk'] = true;")

**Comment by alecpl** [comment] 2023-07-26 05:50
Duplicate of #8766.

**Closed by alecpl** 2023-07-26 05:50 UTC
