### ISSUE TITLE
No longer able to zoom or rotate attached images when viewing in pop-up window

### ISSUE THREAD

**Issue by NathanLyle** [roundcube/roundcubemail#9618] opened 2024-08-28 20:04 UTC
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

At some point in the last month or so, the ability to rotate or zoom in or out on an image viewed by clicking the attached image (pops up in a new window) has stopped working. I get console logged errors like the following:

Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-l8DJjW34234hjkQj0udzj79U5b6VtF30h9ajBrho='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

### What browser(s) are you seeing the problem on?

Chrome

### What version of PHP are you using?

8.2

### What version of Roundcube are you using?

1.6.8

**Comment by alecpl** [comment] 2024-08-29 06:25
This is a duplicate of #9571. We'll release 1.6.9 soon.

**Closed by alecpl** 2024-08-29 06:25 UTC
