### ISSUE TITLE
Junk folder - mail deletion differencies

### ISSUE THREAD

**Issue by ozgurkazancci** [roundcube/roundcubemail#9470] opened 2024-05-28 11:40 UTC
Hi,

Within the Junk folder, when go to three dots-menu and select "Empty", all the Junk mails move to Trash bin. (Instead of directly deleting them)

However, within the Junk folder, when I click an email and select the "Delete" icon at upper-right top, the mail gets deleted without being moved into Trash bin.

Is this a normal, expected behaviour or do I have some misconfiguration?

Roundcube version: 1.6.7

Regards.

**Comment by pabzm** [comment] 2024-05-30 10:01
I don't think it's expected and I can't reproduce it, so I'd assume the problem is local on your side, sorry.

**Comment by ozgurkazancci** [comment] 2024-05-30 11:04
I have  several Roundcube installations on different servers and I can say after upgrade to 1.6.7, all of them does the same thing as above. But if so, which of the followings is the correct behaviour?

1- Inside the Junk folder, clicking to three dots-menu, then selecting "Empty", should move all mails to Trash bin.
2- Inside the Junk folder, clicking on an email and then the "Delete" icon at upper-right top, the mail should get deleted without being moved into Trash bin.
3- Both should move into Trash bin.

**Comment by pabzm** [comment] 2024-05-30 15:35
Thank you for the config details! With that I can reproduce the problem, but it is already fixed in the "master"-branch: <https://github.com/roundcube/roundcubemail/pull/8766>. Thus I'm closing this.

Apparently the fix is meant to be released in v1.7.

**Closed by pabzm** 2024-05-30 15:35 UTC
