### ISSUE TITLE
New folder doesn't display right away

### ISSUE THREAD

**Issue by arbitrary-dev** [roundcube/roundcubemail#9662] opened 2024-10-03 04:21 UTC
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

When I add new folder it doesn't display right away in the list. I need to go out and then back to folders listing to see it.

I use Elastic mobile theme.

### What browser(s) are you seeing the problem on?

Chrome

### What version of Roundcube are you using?

latest

**Comment by alecpl** [comment] 2024-10-04 10:12
What Roundcube version? What plugins? What web browser? Any errors in browser console? Is it a top-level folder or a subfolder?

**Comment by arbitrary-dev** [comment] 2024-10-05 09:20
Chrome browser for Android, no console there. Top-level folder.

As for plugins and version, I was unable to locate these things anywhere in web client I use.

**Comment by seanm** [comment] 2024-11-28 21:33
I believe I see this same thing. Roundcube 1.6.9. Firefox 132.0.2.

When I create a new user for a new employee, I log into roundcube as that user to create/send/delete some test emails. The first ever deletion of an email creates the `Trash` mailbox, but I don't see it appear unless I refresh the browser.  Screenshots:

![Roundcube9662](https://github.com/user-attachments/assets/68dd4ca3-b795-48d1-a95a-57da61310d6f)

**Comment by alecpl** [comment] 2024-12-21 17:43
@seanm No, it's not even close to the original issue. There's configuration options to create special folders for new users.

I'm closing this ticket as not enough info.

**Closed by alecpl** 2024-12-21 17:43 UTC
Labels: need feedback

**Comment by arbitrary-dev** [comment] 2024-12-21 18:03
Actually @seanm's is issue the same as mine, but in a different part of the system.

And the issue is that folders listing view doesn't update asynchronously after changes were made in another view (folder creation view in my case, messages listing view in @seanm's case). Only after refreshing the page as a whole changes could be noticed.

**Comment by alecpl** [comment] 2024-12-22 08:06
If your issue was indeed about a folder created in a different session/client, then yes it might not appear because of caching (`imap_cache` option). Visiting Settings > Folders reset the cache.

The other user issue is different because it is about refreshing the view (folder list) on automatic folder creation in background (same session and client).

**Comment by arbitrary-dev** [comment] 2024-12-22 16:53
Neither me nor @seanm were talking about different session/client, where did you get that from?

**Comment by alecpl** [comment] 2024-12-23 07:29
Then your description is not clear. Detailed steps to reproduce, please.
