### ISSUE TITLE
Search exact phrase with quotation marks

### ISSUE THREAD

**Issue by nclm** [roundcube/roundcubemail#9466] opened 2024-05-24 11:06 UTC
Hi. It seems that Roundcube search does not do any difference between `the exact phrase` and `"the exact phrase"`. It would be great and very useful if it was possible to sandwich some words between straight quotation marks to be able to search for that exact series of words in a row and in that order rather than any messages in which these words appear. Thanks!

**Comment by bronkoo** [comment] 2024-05-27 17:27
+1

would like to search all emails delivered exactly TO "round@cube.mail" in all folders...

**Comment by pabzm** [comment] 2024-05-29 09:32
@bronkoo You can select which message parts should be searched using the drop-down on the right of the search term field.

**Comment by pabzm** [comment] 2024-05-29 09:34
@alecpl From the "master"-branch I can use quotation marks to restrict searching, in v1.6.7 that doesn't work (in my test). Can you shed some light on the difference?

**Comment by alecpl** [comment] 2024-05-29 09:39
The difference is in https://github.com/roundcube/roundcubemail/commit/31241485decbf79b875ca7cb10691a134f63fbf8 ;)

**Comment by alecpl** [comment] 2024-05-29 09:44
So, in master you can do `the or exact or phrase`. I'll close this as a duplicate of #8502.

**Closed by alecpl** 2024-05-29 09:44 UTC
Labels: 0. to triage

**Comment by pabzm** [comment] 2024-05-29 09:48
Thank you! Could we maybe extend the description of that change in the changelog? I'd seen the line but neither the commit description nor the referenced issue's comments (and a no pull request was not involved) gave any hint what this commit actually changed.

**Comment by pabzm** [comment] 2024-05-29 09:50
@nclm According to https://github.com/roundcube/roundcubemail/issues/8502#issuecomment-1166307808 this will be released in v1.7

(@alecpl Please correct me if that's wrong.)

**Comment by nclm** [comment] 2024-05-29 09:53
Sounds great, thanks!
