### ISSUE TITLE
Elastic: Save bar/button does not show on some tablet devices, some resolutions

### ISSUE THREAD

**Issue by skanadian** [roundcube/roundcubemail#6872] opened 2019-07-26 18:32 UTC
Problem: When editing user preferences, the save bar/button does not show on some tablet devices at some resolutions.

To reproduce:
On desktop, setup a chrome custom device: (F12 > Devices > Dropdown at top > Edit > Add custom device > Name It > Resolution: 601 x 962).
Switch to your custom device.
Log in to roundcube with elastic set.
Go to settings > user interface (or any other setting menu).
![no-save](https://user-images.githubusercontent.com/43651180/61973540-39c8a100-afb2-11e9-9675-bc81e545f9ce.PNG)
No save button/save bar is present.

**Comment by johndoh** [comment] 2019-07-30 12:47
possible dupe of #6678

**Closed** 2019-07-31 11:50 UTC
