### ISSUE TITLE
Feature Request: individual date in search filter

### ISSUE THREAD

**Issue by boerner86** [roundcube/roundcubemail#5366] opened 2016-07-23 14:06 UTC
it would be awesome if to set an individual date (for example with a date picker) or a period of time within roundcube is searching for e-mails.

For example: searching for all emails older than 2016-07-23. With this feature it would be possible to delete all mails older than a certain date.

**Comment by alecpl** [comment] 2016-07-23 16:55
Duplicate of #5087.

**Closed by alecpl** 2016-07-23 16:55 UTC
