### ISSUE TITLE
Address helper in mail composition doesn't work with more than 1 character

### ISSUE THREAD

**Issue by FeZoli** [roundcube/roundcubemail#6855] opened 2019-07-18 09:37 UTC
Hi There,

I'm using Roundcube's own addressbook. It has been working for years.
Now I've upgraded to 1.4-rc1, and an issue occured:

1. Click on "Create Email"
2. Start typing into the To: field
3. If you type only 1 character, then the system lists all matching addresses as expected
4. If you type 2 or more characters, then the matching addressess do not show up any more.

If you type into the search box on the left side, then press Enter, the system shows that "3 matching addressess found", but there is no address listed below the search box.

Could you please help to sove?

Thank you:
FeZ

**Comment by alecpl** [comment] 2019-07-18 13:13
Disable all plugins and try again. Check for errors in logs and browser console. Try with another browser.

**Comment by FeZoli** [comment] 2019-07-18 15:04
Hi,
I've found this:

`PHP Warning:  preg_replace(): Compilation failed: escape sequence is invalid in character class at offset 8 in /opt/htdocs/roundcube/program/lib/Roundcube/rcube_vcard.php on line 547`

I've simply commented out that part, and now it works again. So this part is the affected one.

FeZ

**Comment by alecpl** [comment] 2019-07-18 17:22
Duplicate of #6744.

**Closed by alecpl** 2019-07-18 17:22 UTC
Labels: need feedback
