### ISSUE TITLE
Feature Request: Add "undelete" option to "mark messages" button

### ISSUE THREAD

**Issue by dddns** [roundcube/roundcubemail#6401] opened 2018-08-19 21:58 UTC
Howdy,

I’ve come up with the need to “undelete” a message, and i just noticed that I don’t have that possibility.
The “mark messages” button, has some nice options, but not that one.

Is is possible to add this option to it?
It's a basic operation that in my opinion of course, it should exist.

I would add two extra options:
- delete
- undelete

Thanks in advanced,
Jorge,

**Comment by alecpl** [comment] 2018-08-20 05:59
Duplicate of #5133.

**Closed by alecpl** 2018-08-20 05:59 UTC
