### ISSUE TITLE
Roundcube 1.6.0 upgrade poorly maps smtp_server/smtp_port setting to new config file

### ISSUE THREAD

**Issue by adipose** [roundcube/roundcubemail#8756] opened 2022-10-20 22:27 UTC
In my old config file (1.5?), I had the following setting:

```
$config['smtp_server'] = 'tls://127.0.0.1';
$config['smtp_port'] = 587;

```

In my upgrade config file, I did not get a corresponding mapping.

In defaults.inc.php, we have:

```
$config['smtp_host'] = 'localhost:587';
```

In my new config file, all I got was:

```
$config['smtp_port'] = 587;
```

Which if I understand correctly, is a deprecated setting, anyway.

In order to get it working, obviously I had to add this to override the defaults:

```
$config['smtp_host'] = 'tls://localhost:587';
```

**Comment by alecpl** [comment] 2022-10-21 05:48
Duplicate of #8643. I'll leave this open to recheck how smtp_port/default_port are handled.

**Comment by adipose** [comment] 2022-10-21 17:23
Thanks, I must have missed that one.  I did look, I swear...

**Comment by alecpl** [comment] 2022-11-13 12:20
Fixed.

**Closed by alecpl** 2022-11-13 12:20 UTC
Labels: bug, C: Installer

**Comment by adipose** [comment] 2022-11-13 19:56
TY
