### ISSUE TITLE
Ability to Create New Folders Without Leaving The Email That Made You Decide to Do That

### ISSUE THREAD

**Issue by Lonniebiz** [roundcube/roundcubemail#8518] opened 2022-04-28 13:26 UTC
When I receive an email, that needs to be stored in a folder that I haven't created yet, it takes more steps than I'd like to add that new folder. 

My current workflow for adding a new folder (without leaving the email I'm reading) is this:
1) I CTRL-Click the Mail-Tab/button at the top of Roundcube's "Larry" theme (which opens roundcube in a new tab).
2) I click the gear-icon and select "Manage Folders" from the context-menu.
3) I add the folder.
4) I go back to the original browser-tab of the email I was reading.
5) I have to refresh the page, because that tab isn't yet aware of the existence of the new folder I created.
6) I move the email to the new folder I've created.

Is there any way we can accomplish adding a new folder without leaving the email I'm currently reading and reduce the steps required to accomplish this task?

**Ideas:**
1) You could make it to where right-clicking an existing folder (in the left pane) produces a context menu with an option to add a sub-folder.
2) You could add a "New Folder" option to the "Move" drop-down-menu that produces a modal in front of the email, that allows you to add a folder without leaving the email you're currently viewing and move that email to the freshly created folder.

I recently started using roundcube, coming from Gmail, and I really like it. It looks like an application that has been beaten into shape over several years. I'm just throwing my own punch at it in hopes we can beat it just a little bit more.

**Comment by alecpl** [comment] 2022-04-28 13:43
Duplicate of #5062.

**Closed by alecpl** 2022-04-28 13:43 UTC
