### ISSUE TITLE
DB Schema:  NOT OK(Error creating database schema: [1071] Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by XegerrI** [roundcube/roundcubemail#8306] opened 2021-11-11 05:39 UTC
Hello,

I am setting up a new installation of RoundCube Web Mail 1.5.1 on Linux Debian, using MySQL v 10.1.x with the default storage engine set to InnoDB.

The first 3 tables are created successfully in the DB but then I receive the following error:

Check DB config
DSN (write):  OK
DB Schema:  NOT OK(Error creating database schema: [1071] Specified key was too long; max key length is 767 bytes (SQL Query: CREATE TABLE `cache_index` (
`user_id` int(10) UNSIGNED NOT NULL,
`mailbox` varchar(255) BINARY NOT NULL,
`expires` datetime DEFAULT NULL,
`valid` tinyint(1) NOT NULL DEFAULT '0',
`data` longtext NOT NULL,
CONSTRAINT `user_id_fk_cache_index` FOREIGN KEY (`user_id`)
REFERENCES `users`(`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
INDEX `expires_index` (`expires`),
PRIMARY KEY (`user_id`, `mailbox`)
) /*!40000 ENGINE=INNODB */ /*!40101 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */))

I have followed the suggestion to manually initialize the tables by importing the SQL file but the same issue occurs.

I tried changing the cache_key varchar key length to 128 and this allowed it to get to the next table, but if I continue to edit the SQL like this I will probably introduce another bug further down the line since the PHP code likely has a validator set to check the length is <= 255.

I am going to try and use a slightly older version of RC for the moment.

Thank you for your time.

Byron

**Comment by XegerrI** [comment] 2021-11-11 05:50
I think I  need to set innodb_large_prefix=true if it works I'll close this myself

**Comment by XegerrI** [comment] 2021-11-11 06:24
I have set the following 2 Server Settings and still get the issue;
  innodb_large_prefix=true
  innodb_file_format=Barracuda

**Comment by alecpl** [comment] 2021-11-11 06:28
Duplicate of #8231.

**Closed by alecpl** 2021-11-11 06:28 UTC
