### ISSUE TITLE
iPhone only email attachments wont forward

### ISSUE THREAD

**Issue by roberta0967** [roundcube/roundcubemail#7440] opened 2020-06-17 00:06 UTC
Hi Guys,

Odd one, so:

If a user emails in using outlook/roudcube or even a samsung mobile phone with an image/s attached. If you "forward" that email, the images will attach to the forwarding email.

However, if you email those images via an iphone using any account, and select "forward" on the email sent to you from an iphone - those images will NOT attach to the forwarding email.

I appears since cPanel upgrade to version 1.4.4 

Thanks
Robert.

**Comment by alecpl** [comment] 2020-06-17 05:48
Duplicate of #7414.

**Closed by alecpl** 2020-06-17 05:48 UTC
