### ISSUE TITLE
Scrollbar color in dark mode too dark

### ISSUE THREAD

**Issue by 532910** [roundcube/roundcubemail#8345] opened 2021-11-29 04:16 UTC
![image](https://user-images.githubusercontent.com/14617699/143807994-8c565b3e-537f-497f-a2f4-7d053aad2238.png)

v1.5.1

**Comment by alecpl** [comment] 2021-11-29 06:50
Duplicate of #8309.

**Comment by 532910** [comment] 2021-11-29 07:34
Sorry for lack of details, but I meant that scrollbar has low visibility, not his narrowness.

**Comment by alecpl** [comment] 2021-11-29 09:10
I guess we could fix that.

**Comment by alecpl** [comment] 2022-01-22 07:57
I switched scrollbar thumb color darkness from 30% to 25% (of the main color), should be enough.

**Closed by alecpl** 2022-01-22 07:57 UTC
Labels: bug, C: User Interface
