### ISSUE TITLE
Roundcube does not work anymore when using a reverse proxy with a subpath

### ISSUE THREAD

**Issue by Diman0** [roundcube/roundcubemail#8738] opened 2022-10-05 13:58 UTC
After upgrading Roundcube 1.5.3 to the latest version 1.6.0, it no longer works under a reverse proxy, under a subpath.

Log-in is redirecting to `/?_task=login` instead of `/subpath/?_task=login`.
The old behaviour was `./?_task=login`

This was working before. See also [#186](https://github.com/roundcube/roundcubemail-docker/issues/186).

**Comment by J0riz** [comment] 2022-10-06 09:48
This issue is related to #8170 

This is caused by a new `$_SERVER['REQUEST_URI']` check introduced in RoundCube 1.6 in `program/include/rcmail.php` on line 1155

I did for now just disable the check what doesn't sound like a nice solution but makes it work again if you use a reverse proxy:

```
        if ($absolute || $full) {
            // add base path to this Roundcube installation
            $prefix = $base_path ?: '/';

            // prepend protocol://hostname:port
            if ($full) {
                $prefix = rcube_utils::resolve_url($prefix);
            }

            $prefix = rtrim($prefix, '/') . '/';
        }
        else {
            // Disable check for REQUEST_URI
            //if (isset($_SERVER['REQUEST_URI'])) {
            //    $prefix = preg_replace('/[?&].*$/', '', $_SERVER['REQUEST_URI']) ?: './';
            //}
            //else {
                $prefix = './';
            //}
        }
```

I hope someone can come up with a more nice solution.

**Comment by thomascube** [comment] 2022-10-14 07:40
@alecpl This seems like a major regression and should be fixed in a 1.6.x release. There are a number of issues related to this reported to the docker repo where Roundcube mostly runs behind a reverse proxy.

**Comment by alecpl** [comment] 2022-10-14 07:51
Feel free to work on this if you know a solution that would cover this issue and #8170 case.

**Comment by thomascube** [comment] 2022-10-31 20:47
@alecpl Please review the proposed solution in PR #8770

**Closed** 2022-11-23 20:05 UTC
Labels: bug, C: User Interface, blocker
