### ISSUE TITLE
writing default to wrong location  "move_uploaded_file(): open_basedir restriction"

### ISSUE THREAD

**Issue by f1-outsourcing** [roundcube/roundcubemail#9209] opened 2023-11-08 15:49 UTC
Why are you not getting this from upload_tmp_dir or sys_temp_dir nobody uses /tmp any more.

**Comment by f1-outsourcing** [comment] 2023-11-08 15:59
If I set the sys_temp_dir= thent it is working so upload_tmp_dir  is not checked

**Comment by alecpl** [comment] 2023-11-08 17:01
Sounds like a duplicate of #6849.

**Closed by alecpl** 2023-11-08 17:01 UTC
