### ISSUE TITLE
collective contacts adding to group after search

### ISSUE THREAD

**Issue by KrzysztofWWW** [roundcube/roundcubemail#7908] opened 2021-02-26 11:15 UTC
After selecting multiple contacts in "Contacts" we can assign them all to given group by:
"More actions..." -> "assign to group..."
But after using search on that page, and selecting multiple contacts, the "More actions..." is inactive.

**Comment by alecpl** [comment] 2021-02-26 11:23
Duplicate of #7862

**Closed by alecpl** 2021-02-26 11:23 UTC
