### ISSUE TITLE
Password Plugin: How to enable password history

### ISSUE THREAD

**Issue by asoposman** [roundcube/roundcubemail#7194] opened 2020-01-24 10:26 UTC
Hello,
Is there a way to enable password history option in roundcube? I would like the user won't be able to reuse none of the last for example 5 passwords he has used.

Thanks.

**Comment by alecpl** [comment] 2020-01-24 10:27
Not possible. Duplicate of #5118.

**Closed by alecpl** 2020-01-24 10:27 UTC
