### ISSUE TITLE
Ldap (fulltext) search does not work without 'search_fields'

### ISSUE THREAD

**Issue by dilyanpalauzov** [roundcube/roundcubemail#8874] opened 2023-01-20 15:48 UTC
With the below configuration, which you can use as the LDAP server does not require authentication:

```
$config['ldap_public']['ldap'] = array(
  'name' => 'LDAP (AEGEE Bodies)',
  'hosts' => array('tls://ldap.aegee.org'),
  'user_specific' => false,
  'base_dn' => 'cn=bodies,dc=aegee,dc=org',
  'config_root_dn' => false,  // Root DN to search config entries (e.g. vlv indexes)
  'fuzzy_search'   => true,
  'vlv'            => false,
  'vlv_search'     => false,
  'numsub_filter'  => false, // '(objectClass=organizationalUnit)',   // with VLV, we also use numSubOrdinates to query the total number of records. Set this filter to get all numSubOrdinates attributes for counting
  'writable'       => false,
  'fieldmap' => array(
    // Roundcube  => LDAP:limit
    'name'        => 'cn',
    'surname'     => 'sn',
    'firstname'   => 'givenName',
    'jobtitle'    => 'title',
    'email'       => 'mail:*',
    //'phone:home'  => 'homePhone',
    'phone:work'  => 'telephoneNumber',
    //'phone:mobile' => 'mobile',
    //'phone:pager' => 'pager',
    //'phone:workfax' => 'facsimileTelephoneNumber',
    //'street'      => 'street',
    'street'      => 'postalAddress',
    'website'     => 'labeledURI',
    'zipcode'     => 'postalCode',
    'region'      => 'st',
    'locality'    => 'l',
    // if you country is a complex object, you need to configure 'sub_fields' below
    //'country'      => 'c',
    'organization' => 'departmentNumber', // instead of 'o' 
    'department'   => 'ou',
    'jobtitle'     => 'title',
    'notes'        => 'description',
    // these currently don't work:
    // 'manager'       => 'manager',
    // 'assistant'     => 'secretary',
  ),
  'scope' => 'one'
);
$config['ldap_debug'] = true;
```
in Roundcube 1.6.0 when I go in the LDAP addressbook and serach for `sof`, /tmp/errors.log includes  a lot of:
```
[20-Jan-2023 15:44:01 UTC] PHP Warning:  strpos(): Empty needle in /roundcubemail-1.6.0/program/lib/Roundcube/rcube_addressbook.php on line 880
[20-Jan-2023 15:44:01 UTC] PHP Warning:  strpos(): Empty needle in /roundcubemail-1.6.0/program/lib/Roundcube/rcube_addressbook.php on line 880
[20-Jan-2023 15:44:01 UTC] PHP Warning:  strpos(): Empty needle in /roundcubemail-1.6.0/program/lib/Roundcube/rcube_addressbook.php on line 880
[20-Jan-2023 15:44:01 UTC] PHP Warning:  strpos(): Empty needle in /roundcubemail-1.6.0/program/lib/Roundcube/rcube_addressbook.php on line 880
[20-Jan-2023 15:44:01 UTC] PHP Warning:  strpos(): Empty needle in /roundcubemail-1.6.0/program/lib/Roundcube/rcube_addressbook.php on line 880
[20-Jan-2023 15:44:01 UTC] PHP Warning:  strpos(): Empty needle in /roundcubemail-1.6.0/program/lib/Roundcube/rcube_addressbook.php on line 880
[20-Jan-2023 15:44:01 UTC] PHP Warning:  strpos(): Empty needle in /roundcubemail-1.6.0/program/lib/Roundcube/rcube_addressbook.php on line 880
[20-Jan-2023 15:44:01 UTC] PHP Warning:  strpos(): Empty needle in /roundcubemail-1.6.0/program/lib/Roundcube/rcube_addressbook.php on line 880
[20-Jan-2023 15:44:01 UTC] PHP Warning:  strpos(): Empty needle in /roundcubemail-1.6.0/program/lib/Roundcube/rcube_addressbook.php on line 880
[20-Jan-2023 15:44:01 UTC] PHP Warning:  strpos(): Empty needle in /roundcubemail-1.6.0/program/lib/Roundcube/rcube_addressbook.php on line 880
[20-Jan-2023 15:44:01 UTC] PHP Warning:  strpos(): Empty needle in /roundcubemail-1.6.0/program/lib/Roundcube/rcube_addressbook.php on line 880
```
and /tmp/ldap.err includes:
```
[20-Jan-2023 15:44:01 +0000]: <cfb25602> C: Connect [ldap://ldap.aegee.org:389:389]
[20-Jan-2023 15:44:01 +0000]: <cfb25602> S: OK
[20-Jan-2023 15:44:02 +0000]: <cfb25602> C: Close
```
* Having :389:389 in the above snippet seems wrong
* `Empty needle in /roundcubemail-1.6.0/program/lib/Roundcube/rcube_addressbook.php on line 880` also seems like a bug.  It appears after I delete the text in the search field and press enter.
* The LDAP search finds no results

**Comment by alecpl** [comment] 2023-01-24 17:46
1. The duplicate port issue has been fixed in Net_LDAP3 library (https://git.kolab.org/rPNL6d44013d92e9aabcfa1fca6fee0ee8d9888a8d9a).
2. I'm unable to reproduce the "empty needle" warning yet.
3. I'm not sure if unauthenticated access is supported. Probably not.

**Comment by dilyanpalauzov** [comment] 2023-01-24 18:12
> I'm not sure if unauthenticated access is supported. Probably not.

The contacts from the above configuration are displayed in the address book, just searching does not work.

**Comment by alecpl** [comment] 2023-04-02 09:29
I use "Need feedback" for all cases where "I don't know what to do with it and/or unable to reproduce".

I found a reason for your issue. You do not have `search_fields` in you LDAP config. So, whenever you search in addressbook with "All fields" selected it will not work. I'll change the code to use attributes for name, firstname, surname and email fields by default.

**Comment by alecpl** [comment] 2023-04-02 09:33
Fixed.

**Closed by alecpl** 2023-04-02 09:33 UTC
Labels: bug, C: Addressbook, C: LDAP
