### ISSUE TITLE
PGP-signed HTML emails aren't detected as HTML during reply/forward

### ISSUE THREAD

**Issue by rimas-kudelis** [roundcube/roundcubemail#8405] opened 2022-01-18 08:44 UTC
I have Roundcube 1.5.0 running, and I configured it so that by default only replies and forwards of HTML messages are composed as HTML.

This works just fine for stuff like Netflix newsletters, however, when I received an OpenPGP-signed HTML email today and wanted to forward it inline or reply to it, Roundcube just kept opening the plain text editor instead of the rich text one.

The email in question was sent using Thunderbird 91.5.0 and is structured like this:
- `multipart/signed`
  - `multipart/mixed`
    - `multipart/alternative`
      - `text/plain`
      - `multipart/related`
        - `text/html`
        - `image/png`
   - `application/pgp-signature`

**Comment by alecpl** [comment] 2022-01-22 08:04
I'm unable to reproduce. Could you provide a sample message?

**Comment by alecpl** [comment] 2022-01-22 13:59
I was able to reproduce with the following structure:
```
- multipart/signed
    - multipart/mixed
        -  multipart/related
            - text/html
            - image/png
    - application/pgp-signature
```

**Comment by alecpl** [comment] 2022-01-22 14:32
f546d7216c2cf fixes the issue for my case. Let me know if it fixes it for your, please.

**Comment by rimas-kudelis** [comment] 2022-01-24 06:47
Thanks! Not sure if I'll test the fix before the release though.

**Comment by alecpl** [comment] 2022-01-30 08:22
One more commit was needed, but it's fixed now.

**Closed by alecpl** 2022-01-30 08:22 UTC
Labels: bug, C: Plugins, C: MIME parsing
