### ISSUE TITLE
Problem on forward/reply on Inline image attachment with same name on message

### ISSUE THREAD

**Issue by lucasmarin** [roundcube/roundcubemail#7455] opened 2020-06-26 14:25 UTC
If a message have 2 or more image attachment used on message content (inline) with same name. When the messge is forwarded/replied , all images of that name will be presented with content of the first part with that name.

Message example with error:
[message_with_error](https://skybox.skymail.net.br/s/apW6h4y0m2OHBSa)

I replace the name of attachment on that message and the error not occurs:
[same_message_with_attachment_name_replaced](https://skybox.skymail.net.br/s/fPqrt3gezfy3QJw)

Tested on Thunderbird and the attachments are replaced on body content correctly.

RC Version: 1.4.6

**Comment by alecpl** [comment] 2020-06-26 15:00
What version? I think this was fixed.

**Comment by lucasmarin** [comment] 2020-06-26 15:12
RC Version: 1.4.6

**Comment by alecpl** [comment] 2020-06-27 06:40
I'm unable to reproduce. Is this a new installation or upgraded? Maybe something went wrong with update. Please, describe your environment, PHP version, IMAP server, etc. Try with disabled all plugins. Enable imap_debug and provide BODYSTRUCTURE response.

**Comment by lucasmarin** [comment] 2020-06-29 20:57
Closing issue.

I ran it on pure RC with minimal configurations and it is not happened.

Sorry for misunderstood and thanks for your quick response.

**Comment by lucasmarin** [comment] 2020-06-30 19:59
Hi @alecpl. I saw that error is in database_attachments plugin.

The id generated to cached attachment may not unique.

https://github.com/roundcube/roundcubemail/blob/5b531611987249faa5a4c92a8c2ddccd4a4fa435/plugins/database_attachments/database_attachments.php#L155:L162

I create a PR to fix it. https://github.com/roundcube/roundcubemail/pull/7463

**Comment by alecpl** [comment] 2020-07-01 07:51
Nice catch. Thanks. It is fixed now also for redundant_attachments plugin.

**Closed by alecpl** 2020-07-01 07:51 UTC
Labels: C: Mail composing, C: PHP backend, bug
