### ISSUE TITLE
Managesieve 8.9 hangs on filters containing ".. " (dot dot space)

### ISSUE THREAD

**Issue by Kurgan-** [roundcube/roundcubemail#5928] opened 2017-08-29 09:49 UTC
Managesieve plugin version 8.9 (in Roundcube 1.3.0) hangs while retrieving contents of a filter that has a text field (it's a vacation auto reply filter) where there is a row that begins whith ".. " (dot dot space)

When it hangs, it runs forever until php times out.

In Apache, I see this in the log:

`172.16.2.153 - - [29/Aug/2017:08:48:09 +0200] "GET /?_task=settings&_action=plugin.managesieve HTTP/1.1" 500 3177 "https://webmail.XXXXXXX.com/?_task=settings" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"`

Previous versions (an old roundcube installation) worked. 

Removing the ".. " from the beginning of the text row solved the issue.

Managesieve server is from Dovecot (version 2.2.13), and if I use a different sieve client it does not hang, so it seems Dovecot is not at fault.

The sieve filter that causes the issue is attached. 
[causes-hang.sieve.txt](https://github.com/roundcube/roundcubemail/files/1259818/causes-hang.sieve.txt)

**Comment by alecpl** [comment] 2017-08-29 09:50
Sounds like a duplicate of #5838, could you confirm?

**Comment by Kurgan-** [comment] 2017-08-29 10:17
It could be. If the attached sieve filter works properly (which means you can open it in the web interface) I suppose that it's in fact a duplicate.

Thanks

**Comment by alecpl** [comment] 2017-08-29 14:22
Confirmed. The attached file works for me.

**Closed by alecpl** 2017-08-29 14:22 UTC
