### ISSUE TITLE
Extends skin

### ISSUE THREAD

**Issue by splintyg** [roundcube/roundcubemail#6478] opened 2018-10-04 09:18 UTC
Hi!
I guess it can be an issue with doc:

> To create a skin that builds on another, simply name the base skin with the label extends in the meta.json file of your skin:
> 
> {
>   "extends": "larry",
>   ...
> }
> This basically adds the base skin folder to the search path for templates and assets. Now the extended skin **only needs to provide the templates or includes that actually differ from the base skin**. 

Skin's /var/www/mail/skins/DD/meta.json contains
{
"name": "DD",
"extends": "larry",
"author": "",
"license": "",
"license-url": ""
}

Directory /var/www/mail/skins/DD/ contains a couple of changed css and meta.json, no more. And opening web-interface failed with multiplies 404.

**Comment by alecpl** [comment] 2018-10-04 10:37
Works for me. What version? What 404's? What exactly is the folder content?

**Comment by splintyg** [comment] 2018-10-04 11:09
1.3.7
ls  /var/www/mail/skins/DD/ 
meta.json  styles.css  styles.min.css

And one thing i've encountered at first time. If i set $config['skin'] = 'DD'; 
then login page (a place, where i started to test) get all resources (and styles*css) from /var/www/mail/skins/larry/ 
If i set $config['skin'] = 'classic'; 
then all works fine on login page...

**Comment by splintyg** [comment] 2018-10-06 13:16
The matter is that further works requirre to move all files of larry to new theme directory. As i said without copyng all files we look at multiplies 404 errors "resource not found".
So the following doesn't work

**Comment by alecpl** [comment] 2018-10-08 14:37
No, it does not require moving all files. This depends on what you try to change. Problem with css files is that resource locations (e.g. background images) are resolved by browser. So, using a copy of css file without modifying all url()'s will require all referred images. And we obviously would not want to do this on the fly. We can't get rid of all limitations.

Depending on your needs it might be better to copy/modify only links.html template in a way that it loads additional css file. So, in your skin you'd end up with links.html and single css file. That css file would contain all additional styles.

**Comment by joshk03** [comment] 2018-10-08 20:06
I have been struggling with this same issue since I first installed roundcube a few months ago.  
I found the larry skin in 
`/usr/share/roundcube/skins/larry`
so I tried to extend it with a meta.json file in
`/usr/share/roundcube/skins/mySkin`
but my skin is not recognized in Preferences >> User Interface.

If i set `$config['skin'] = 'mySkin';` it just loads the Larry skin instead.  But if I choose Classic, all is well.

**Comment by alecpl** [comment] 2018-10-09 06:11
Don't use upper-case letters.

**Comment by joshk03** [comment] 2018-10-09 14:01
I didn't use upper case.  It was called larry2.  Now that you said that, I changed it to josh.  Still nothing.  Should I expect it to become available on the Preferences >> User Interface screen?  I have not modified the css file yet during this go around, so detecting when it's working is tougher.

**Comment by alecpl** [comment] 2018-10-09 15:36
You said it was 'mySkin'. 'larry2' is valid name and it should appear on the skins list, until you added 'skin' to dont_override config. I don't know why it didn't work, but as you can see in this ticket it generally works.

**Comment by joshk03** [comment] 2018-10-09 15:58
There must be more that is undocumented.  It is not working as expected on my fresh install if RC 1.3.6.  What do you mean "until you added 'skin' to dont_override config"?

**Comment by joshk03** [comment] 2018-10-10 01:02
I'm eagerly awaiting the next steps to diagnose this bug.

**Comment by joshk03** [comment] 2018-10-11 16:50
Proof:
I created this folder:
/usr/share/roundcube/skins/josh

and I created this file:
/usr/share/roundcube/skins/josh/meta.json
which contains:
```
{
	"name": "josh",
	"extends": "classic",
	"author": "Josh",
	"license": "Creative Commons Attribution-ShareAlike",
	"license-url": "http://creativecommons.org/licenses/by-sa/3.0/"
}
```
And in the file:
/etc/roundcube/config.inc.php
`$config['skin'] = 'josh';`

as well as a thumbnail.png file.

As you can see, I am now telling it to extend CLASSIC, but it is still giving me the default LARRY.

Also, the setting page does not show the new skin as an option.  but the radio-button is gone from both classic and larry, so it knows it is supposed to do something.

**Comment by splintyg** [comment] 2018-10-12 06:14
> Depending on your needs it might be better to copy/modify only links.html template in a way that it loads additional css file. So, in your skin you'd end up with links.html and single css file. That css file would contain all additional styles.

I guess the certain example will help me understand Your frase "That css file would contain all additional styles."
Look, i need new skin exactly as larry one, except for login and main window's background.  It must be red. 
What should i move to new skin directory /var/www/mail/skins/DD/ if it already contains
meta.json
{
"name": "DD",
"extends": "larry",
"author": "",
"license": "",
"license-url": ""
}
?
Thank You.

**Comment by johndoh** [comment] 2018-10-12 06:54
@joshk03 please check the permissions on the /usr/share/roundcube/skins/josh folder, make sure they match the other skins (the webserver/php user needs read and execute perms)

@splintyg you need to create a folder structure like this:

./roundcube/skins/DD/
./roundcube/skins/DD/meta.json - the meta file you already posted
./roundcube/skins/DD/DD.css - the new CSS you want
./roundcube/skins/DD/includes/
./roundcube/skins/DD/includes/links.html - copy the links.html file from the same place in the Larry skin

modify ./roundcube/skins/DD/includes/links.html to add in your css file (line 8 below):
```html
<meta name="viewport" content="" id="viewport" />
<link rel="shortcut icon" href="/images/favicon.ico"/>
<link rel="stylesheet" type="text/css" href="/styles.css" />
<roundcube:if condition="in_array(env:task, array('mail','addressbook','settings'))" />
<link rel="stylesheet" type="text/css" href="/<roundcube:var name="env:task" />.css" />
<roundcube:endif />
<script type="text/javascript" src="/ui.js"></script>
<link rel="stylesheet" type="text/css" href="/DD.css" />
<roundcube:add_label name="errortitle" />
<roundcube:add_label name="toggleadvancedoptions" />
```

If you want to create your own login page then add ./roundcube/skins/DD/templates/login.html

**Comment by johndoh** [comment] 2018-10-12 09:37
right. I was testing with git-master. I think this commit 35a3abd fixes the paths

**Comment by splintyg** [comment] 2018-10-12 09:47
Ok, thanks to everybody. In fact RoundCube is good and solves almost all tasks of mail client. Let's wait for commit or next release.

**Comment by joshk03** [comment] 2018-10-12 14:44
@johndoh, I had confirmed the permissions matched when I created the folder and files, and now I have changed them all to 777.  Even with full access for all there is no change in behavior.

**Comment by johndoh** [comment] 2018-10-13 06:15
@joshk03 I suggest you add some debug code into this function https://github.com/roundcube/roundcubemail/blob/release-1.3/program/steps/settings/func.inc#L1310

**Comment by alecpl** [comment] 2021-05-29 07:12
Reading this again, I see we can close the ticket.

**Closed by alecpl** 2021-05-29 07:12 UTC
Labels: C: Core functionality, C: User Interface, enhancement
