### ISSUE TITLE
php 8.0 Fatal Error when allowing images in an email

### ISSUE THREAD

**Issue by reubenfarrelly** [roundcube/roundcubemail#7968] opened 2021-03-23 22:19 UTC
Triggered when bring up an email that has images, and clicking on "Always allow from <email address>".

The UI displays a red Internal Error message and the log show the following fatal error:

[24-Mar-2021 09:11:37 Australia/Sydney] PHP Fatal error:  Uncaught TypeError: Illegal offset type in isset or empty in /var/www/roundcube/htdocs/program/lib/Roundcube/rcube.php:650
Stack trace:
#0 /var/www/roundcube/htdocs/program/include/rcmail_output_json.php(141): rcube->text_exists()                                                                       
#1 /var/www/roundcube/htdocs/program/actions/mail/addcontact.php(93): rcmail_output_json->show_message()                                                             
#2 /var/www/roundcube/htdocs/program/include/rcmail.php(275): rcmail_action_mail_addcontact->run()                                                                  
#3 /var/www/roundcube/htdocs/index.php(283): rcmail->action_handler()                                                                                                
#4 {main}                                                                                                                                                                     
  thrown in /var/www/roundcube/htdocs/program/lib/Roundcube/rcube.php on line 650        

This is with php 8.0.3 and git -head up to date as of about a week ago.

**Comment by alecpl** [comment] 2021-03-24 06:02
Looks like it might happen if the email address is invalid. Is that the case?

**Comment by reubenfarrelly** [comment] 2021-03-24 10:45
I can't be 100% sure - but that may be the case.  Most addresses work just fine, just a few that fail like that.  II'll pay attention going forward and report back here in a few days if there hasn't been any other comments or commits related to it.

**Comment by alecpl** [comment] 2021-03-26 17:44
I wasn't able to reproduce, but it should be fixed now.

**Closed by alecpl** 2021-03-26 17:44 UTC
Labels: C: Addressbook, C: PHP backend, bug
