### ISSUE TITLE
Too many public recipients warning: "Send now" does not work.

### ISSUE THREAD

**Issue by milankni** [roundcube/roundcubemail#5924] opened 2017-08-27 16:22 UTC
Roundcube 1.3.0.

When trying to send email to e.g. 7 "To:" addresses and 1 "Cc:" address, roundcube displays a warning that I should consider using "Bcc:" field instead. There is an option to send the message anyway.

However, clicking on "Send now" does not send the message - only the warning window disappears and the user has to click on standard "Send" icon again.
![screenshot from 2017-08-27 18-18-06](https://user-images.githubusercontent.com/937861/29751905-89e0c0ca-8b54-11e7-8229-012c25570c46.png)

Expected behaviour: the message should be sent immediately if the user wishes so.

**Comment by alecpl** [comment] 2017-08-27 17:34
Confirmed.

**Comment by alecpl** [comment] 2017-08-28 06:29
Closed by mistake.

**Closed** 2017-08-28 07:54 UTC
Labels: bug, C: Mail composing, C: User Interface

**Comment by mareksal** [comment] 2018-02-20 10:15
Hello,

the issue still appears in RC version 1.3.4 - both Firefox and Chrome.

`
TypeError: f.getClientRects is not a function  jquery.min.js:38:20138

TypeError: p is undefined  app.min.js:185:191
`

**Comment by alecpl** [comment] 2018-02-20 12:58
Works for me.

**Comment by vasyugan** [comment] 2018-11-29 10:55
Error can be reproduced here, roundcube 1.3.8 running with Nginx, PHP 7.2 fpm, Ubuntu 18.04, in Firefox 
the firefox console says:
TypeError: p is undefined app.min.js:185:191
n
https://webmail.rohr.org/program/js/app.min.js:185:191
click
https://webmail.rohr.org/program/js/app.min.js:185:423
_createButtons/</a.click
https://webmail.rohr.org/plugins/jqueryui/js/jquery-ui-1.10.4.custom.min.js:37:9547
dispatch
https://webmail.rohr.org/program/js/jquery.min.js:37:10264
add/q.handle
https://webmail.rohr.org/program/js/jquery.min.js:37:8326

**Comment by alecpl** [comment] 2018-11-29 11:08
Could you remove app.min.js (move temporarily to some other location) and try again? It should give some more useful error message.

**Comment by vasyugan** [comment] 2018-11-30 07:11
> Could you remove app.min.js (move temporarily to some other location) and try again? It should give some more useful error message.

This is what I am getting then:
```

Source-Map-Fehler: TypeError: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: moz-extension://d38c5d29-217f-48a1-99c5-982add902d10/lib/browser-polyfill.min.js
Source-Map-Adresse: browser-polyfill.min.js.map[Weitere Informationen]
Source-Map-Fehler: TypeError: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: moz-extension://97b9053d-4d1c-44e5-b9f1-a94bb3cb3754/browser-polyfill.min.js
Source-Map-Adresse: browser-polyfill.min.js.map[Weitere Informationen]
TypeError: f.getClientRects is not a function[Weitere Informationen] jquery.min.js:38:20138
offset
https://webmail.xxxx.org/program/js/jquery.min.js:38:20138
getWithinInfo
https://webmail.xxxx.org/plugins/jqueryui/js/jquery-ui-1.10.4.custom.min.js:36:14767
t.fn.position
https://webmail.xxxx.org/plugins/jqueryui/js/jquery-ui-1.10.4.custom.min.js:36:15031
_position
https://webmail.xxxx.org/plugins/jqueryui/js/jquery-ui-1.10.4.custom.min.js:37:14702
t.widget/</l[i]</<
https://webmail.xxxx.org/plugins/jqueryui/js/jquery-ui-1.10.4.custom.min.js:36:5027
open
https://webmail.xxxx.org/plugins/jqueryui/js/jquery-ui-1.10.4.custom.min.js:37:6529
t.widget/</l[i]</<
https://webmail.xxxx.org/plugins/jqueryui/js/jquery-ui-1.10.4.custom.min.js:36:5027
_init
https://webmail.xxxx.org/plugins/jqueryui/js/jquery-ui-1.10.4.custom.min.js:37:5164
t.widget/</l[i]</<
https://webmail.xxxx.org/plugins/jqueryui/js/jquery-ui-1.10.4.custom.min.js:36:5027
_createWidget
https://webmail.xxxx.org/plugins/jqueryui/js/jquery-ui-1.10.4.custom.min.js:36:7102
t.widget/t[u][i]
https://webmail.xxxx.org/plugins/jqueryui/js/jquery-ui-1.10.4.custom.min.js:36:4587
t.widget.bridge/t.fn[i]/<
https://webmail.xxxx.org/plugins/jqueryui/js/jquery-ui-1.10.4.custom.min.js:36:6309
each
https://webmail.xxxx.org/program/js/jquery.min.js:36:2713
each
https://webmail.xxxx.org/program/js/jquery.min.js:36:1001
t.widget.bridge/t.fn[i]
https://webmail.xxxx.org/plugins/jqueryui/js/jquery-ui-1.10.4.custom.min.js:36:6227
rcube_webmail/this.show_popup_dialog
https://webmail.xxxx.org/program/js/app.js:7620:5
rcube_webmail/this.check_compose_input
https://webmail.xxxx.org/program/js/app.js:4469:16
rcube_webmail/this.command
https://webmail.xxxx.org/program/js/app.js:1178:53
onclick
https://webmail.xxxx.org/:1:8
TypeError: dialog is undefined[Weitere Informationen] app.js:4464:11
save_func
https://webmail.xxxx.org/program/js/app.js:4464:11
click
https://webmail.xxxx.org/program/js/app.js:4474:33
_createButtons/</a.click
https://webmail.xxxx.org/plugins/jqueryui/js/jquery-ui-1.10.4.custom.min.js:37:9547
dispatch
https://webmail.xxxx.org/program/js/jquery.min.js:37:10264
add/q.handle
https://webmail.xxxx.org/program/js/jquery.min.js:37:8326

```
