### ISSUE TITLE
Google fonts deadlock

### ISSUE THREAD

**Issue by oscarhult** [roundcube/roundcubemail#6912] opened 2019-09-04 09:04 UTC
Not sure if this is specific for my email providers configuration.
They are running "`Roundcube Webmail 1.3.9`".

```
<html>
    <head>
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    </head>
    ...
```

Will result in something like

```
<!-- html ignored --><!-- head ignored --><!-- meta ignored -->
<link href="./?_task=utils&amp;_action=modcss&amp;_u=tmp-595cb6ccb56826a802ed411cef875f0e.css&amp;_c=message-htmlpart1" rel="stylesheet"></link>
```

When clicking [Display images], the email preview goes blank.
The "`_task=utils&_action=modcss`" request starts and after 2 minutes it ends up with a 504 Gateway Timeout and the email successfully loads.

**Comment by alecpl** [comment] 2019-09-04 09:55
I'm unable to reproduce on 1.3.10. The modcss action quickly returns `/* evil! */`. Maybe your server has problems with connecting to fonts.googleapis.com.

**Comment by alecpl** [comment] 2019-10-01 08:09
We set timeout to 15 seconds though, so it's strange that it hangs for 2 minutes. Any errors in log?

Closing until we get any feedback.

**Closed by alecpl** 2019-10-01 08:09 UTC
Labels: need feedback
