### ISSUE TITLE
Elastic: Accessibility difficulties (blue color)

### ISSUE THREAD

**Issue by chris246** [roundcube/roundcubemail#8210] opened 2021-09-23 18:33 UTC
Hi,

we have a user who has difficulties distinguishing the blue highlight/accent color from the background.
The sign in and send buttons and the mail count indicator on the individual folders are completely invisible to him.
In the side navigation, he has difficulties identifying the the labels and icons.

We just did some tests and he has no difficulties reading black text on the aforementioned buttons.

His impairment is not the traditional color blindness, therefore just considering sufficient contrast between background and foreground does not help in his case.

As he can use a mail app for reading emails, this issue is not that urgent.

**Comment by alecpl** [comment] 2021-09-25 07:04
Duplicate of #7126.

**Closed by alecpl** 2021-09-25 07:04 UTC
