### ISSUE TITLE
Further quota information?

### ISSUE THREAD

**Issue by ozgurkazancci** [roundcube/roundcubemail#9191] opened 2023-10-28 00:49 UTC
Hello, greetings.

Roundcube version: 1.6.4 - Server OS: OpenBSD

I don't know if such feature already exists or if it's a request for new feature - yet I just wanted to share it with you.

Using PostfixAdmin, I got my accounts with 0 quota limit (unlimited), it'd be nice if Roundcube could show the currently used disk space for the account, alongside the information of being 'unlimited', see please;

![here](https://i.ibb.co/bPWpLRZ/unlimited.png)

So, instead of "unlimited", perhaps something like: _Used: 160 MB / Limit: Unlimited_

Thank you very much in advance.

**Comment by alecpl** [comment] 2023-10-29 11:15
I consider this a duplicate of #5837. There's no IMAP command that returns mailbox size other than GETQUOTA. So, such solution would have to loop over all folders, and on some servers all messages. It could take a long time on a big mailbox.

So, unless there's something I don't know it won't be easy.

**Closed by alecpl** 2023-10-29 11:15 UTC
