### ISSUE TITLE
Clearing of Trash-Folder does not delete subfolders

### ISSUE THREAD

**Issue by danielh84** [roundcube/roundcubemail#5299] opened 2016-06-01 05:46 UTC
If i enable clearing of the trash folder on logout in my config it deletes all of my e-mails in this trash-folder.

Sub Folders are still in the trash-folder. The mails in the subfolder are also not delete.

Bug or Feature?

**Comment by alecpl** [comment] 2016-06-01 08:45
Duplicate of #1037

**Closed by alecpl** 2016-06-01 08:45 UTC
