### ISSUE TITLE
Signature placed incorrectly

### ISSUE THREAD

**Issue by ondras** [roundcube/roundcubemail#5642] opened 2017-02-13 15:39 UTC
Configuration:
  - Firefox 51
  - `top_posting: true`,
  - `sig_below: false`,
  - plaintext editing

When replying to an e-mail, the signature is inserted **below** the cited text. I believe that the culprit is https://github.com/roundcube/roundcubemail/blob/master/program/js/editor.js#L539, as the `get_caret_pos` function returns a large number that corresponds to the end of the message. Both `setlectionStart` and `selectionEnd` DOM properties of the `<textarea>` node are the same (equal to `.value.length`), meaning the caret is collapsed to the end of the text area.

Why does this code path even respect caret position? I would expect the settings above to result in sig being **always** inserted at the top...

**Comment by alecpl** [comment] 2017-02-13 16:00
Sounds like a duplicate of #5628.

**Closed by alecpl** 2017-02-13 16:00 UTC
Labels: bug, C: Mail composing, C: User Interface
