### ISSUE TITLE
Email won't send when popup blocker is enabled

### ISSUE THREAD

**Issue by jayhasgin** [roundcube/roundcubemail#7427] opened 2020-06-09 07:40 UTC
Tried using compose to send email. Then appears a notification on addon that one popup being blocked (didn't notice this for an hour). The message alert shown at the bottom says 'Sending ..' for sometime and then quietly serves 'Request failed', without any record in logs (all debug options enabled), or indicating that it was the popup blocker that failed. 

Is there a way to escape the popup blocker or at-least tell the user that they must disable popup, reload the page and try again.

Browser - Firefox 75.0 (64-bit) on Windows 7
Extension - https://addons.mozilla.org/en-US/firefox/addon/popup-blocker/

Hope someone can reproduce this issue.

**Comment by johndoh** [comment] 2020-06-09 12:04
What version of Roundcube? Which skin? Have you tried with all Roundcube plugins disabled? What is the URL the popup blocker is blocking?

**Comment by jayhasgin** [comment] 2020-06-09 22:50
Version is 1.4.4
Skin is elastic. 

I tried to debug this. The popup-blocker was blocking form submission on file 'program/app.js:4740'. Only then I noticed, it blocks all framing, including path '/?_task=mail&_mbox=INBOX'. 

So this is not related only to composing email. Maybe a warning/notice (to disable popup-blocker) can be issued at first occurrence.

**Comment by alecpl** [comment] 2020-06-10 07:58
I created a ticket in the plugin's tracker. What do you mean it blocks all framing? For me it blocks:
1. Email sending/saving a draft
2. Uploading a contact photo

And that's it. E.g. uploading attachments and importing email works.

**Comment by jayhasgin** [comment] 2020-06-10 08:40
Thanks. I couldn't reproduce them now. While debugging before, I came across several alerts for popup being blocked saying '/?_task=mail&_mbox=INBOX' path has been blocked, with accept or deny options. I also remember seeing one with 'REFRESH' keyword in it. I'll update here when I see them again.

**Comment by michaelrimbach** [comment] 2020-06-12 09:36
I have the same issue with Chrome. Its working in Chromes inkognito mode...

**Comment by chrestomanci** [comment] 2020-06-12 10:51
Perhaps the issue is with your chrome plugins. In incognito mode chrome (and firefox) runs without plugins. Could you do a test where you disable some plugins & try again and see if that makes the problem go away.

**Comment by alecpl** [comment] 2020-07-17 07:27
According to the popup-blocker author the issue is fixed in version 0.5.2 of the plugin.

**Closed by alecpl** 2020-07-17 07:27 UTC
Labels: need feedback
