### ISSUE TITLE
PHP error when attempting to open a message with a message/rfc822 part

### ISSUE THREAD

**Issue by GTMSMitch** [roundcube/roundcubemail#8953] opened 2023-03-23 17:23 UTC
This error occurs when attempting to view a message which has another message attached as a 'message/rfc822' part. RoundCube displays an "Oops.. Something went wrong!" internal error, and the error logs display "Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string" on line 2149 in rcube_imap.php. These messages display as expected in other email clients.

I am using Roundcube version 1.6.1, Apache version 2.4.56 and PHP version 8.2.4 but I have tried with previous versions of PHP and Apache and encountered the same issue.

I've attached an example email that causes the issue:
[DisplayErrorEmailText.txt](https://github.com/roundcube/roundcubemail/files/11053711/DisplayErrorEmailText.txt)

**Comment by GTMSMitch** [comment] 2023-03-24 15:42
Update: Can replicate simply by creating an email using RoundCube and either forwarding as an attachment or attaching an EML file using the attach file button on the right hand side.

I have previously seen attaching EMLs in this way working and displaying as normal because they were attached as a text/html part rather than a message/rfc822 part, however I'm unsure as to what combination of RC / Apache / PHP this was.

**Comment by alecpl** [comment] 2023-03-24 16:59
But it supposed to be fixed in 1.6.1 and I'm unable to reproduce using git-master. So, I'm not sure.

**Comment by alecpl** [comment] 2023-07-09 11:19
Actually this might be another issue. I was still not able to reproduce and I think it may depend on the content of your IMAP server response. Anyway, I added some code that should prevent the error to appear.

**Closed** 2023-07-09 12:51 UTC
Labels: bug, C: PHP backend
