### ISSUE TITLE
imap check_connection uses expired oauth credential

### ISSUE THREAD

**Issue by downtownallday** [roundcube/roundcubemail#8436] opened 2022-02-04 21:40 UTC
During an action `refresh`, if the oauth access_token is expired, the access_token is refreshed during initialization of the storage object within `program/lib/Roundcube/rcube.php::storage_init()` at the call `exec_hook("storage_init", $options)`.

The actual token refresh occurs in the hook handler function `program/include/rcmail_oauth.php::storage_init()`.

However, that function fails to update the password in $options which causes the storage object to have stale authorization.

I would suggest a fix:

In `program/include/rcmail_oauth.php::storage_init()`, add:

```
   // update the password in case the access_token was refreshed
   $options['password'] = $this->rcmail->decrypt($_SESSION['password']);
```

after the call to `check_token_validity()`

This may be related to issue #8388.

roundcube is v1.5.2

If you want a PR, kindly let me know.

**Comment by aleshaczech** [comment] 2022-06-15 23:49
Hi, I am facing this issue too and consider it a major bug for XOAuth2.

I have the OAuth2 access token set to expire in 5 minutes, meaning this error can occur as soon as 5 minutes after user logs in.

I can confirm @downtownallday 's description of the issue:
- the `storage_init` hook, initiated at `program/lib/Roundcube/rcube.php:355`, refreshes the OAuth2 token if it's expired
- however at that time, the `$options['password']` is already populated with the old access token at `program/lib/Roundcube/rcube.php:351`
- since the `storage_init` hook does not return the new token, the storage is being populated with outdated token at `program/lib/Roundcube/rcube.php:360`
- should the `rcmail_oauth::storage_init()` return the updated "password" (= access token) as suggested above, this would seem to fix the issue

@thomascube Is there any chance this seemingly one-liner fix would make it to 1.6?

**Comment by nick-oconnor** [comment] 2022-06-24 22:56
Same issue here. I would very much like to see a fix for this in 1.6. Thanks!

**Comment by nick-oconnor** [comment] 2022-06-26 19:19
I've been using this patch for a few days now. I"m not convinced this completely fixes the issue. I'd recommend testing against an OP with a 5m access token expiration. I've increased my OP's access token expiration to 1d for now.

**Closed** 2022-06-26 21:07 UTC
Labels: need feedback, C: OAuth

**Comment by nick-oconnor** [comment] 2022-06-27 01:06
Yep! Fixed. :pray: @thomascube. I was missing the undocumented `offline_access` scope for authelia.
