### ISSUE TITLE
BUG? elastic theme is showing html emails still with white background in dark mode.

### ISSUE THREAD

**Issue by f1-outsourcing** [roundcube/roundcubemail#9137] opened 2023-09-14 21:43 UTC
I have noticed that when using elastic theme all my plain text emails are nicely having the dark background. However recently I have been testing with some html emails send via php and these are having a white background.

If I do a show source of the html email, I do not really see anywhere that html is setting the background.

```
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
	xxxxxxxxxxxxxxxxxxxxxxxx

<tbody>
	<tr>
		<td style=3D"padding:40px 0  0 0;">
					<p=
>
					Hello Test,
					</p>

					<p>
					A pa=
ssword reset has been initiated on your  account. Use this link to suppl=
y a new password:
					</p>

					<p style=3D"color:#000;fon=
t-size: 16px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neu=
e',Helvetica,Arial,sans-serif;font-weight:normal;">
			
					</p>=

```

```

		=
			<p>
					Best regards,<br />
					Your  Support Team<br />=

										</p>
		</td>
	</tr>
</tbody>
```

Interestingly I noticed that proton mail has this similar bug. Maybe they are using your fontend ;)

**Comment by alecpl** [comment] 2023-09-15 06:12
It's just not that simple to do. Duplicate of #8964.

**Closed by alecpl** 2023-09-15 06:12 UTC
