### ISSUE TITLE
TinyMCE menu is totally broken

### ISSUE THREAD

**Issue by kolbma** [roundcube/roundcubemail#7756] opened 2020-11-30 09:51 UTC
TinyMCE 4.9.11 seems to have some problems at least with Firefox ESR.

The HTML menu in the email compose is enabled and it doesn't show the activated menu.  
What it shows depends on if we are scrolling down to see the header menu or on the width of the window.

I've attached some screenshots...

Here html is activated but the menu doesn't change...

![Screenshot_2020-11-30 Webmail Schreiben](https://user-images.githubusercontent.com/5228369/100593817-2beb0480-32f9-11eb-8e47-ff47d1e0f86a.png)

Here we simply scrolled down and the "correct" header menu appears then. But scrolling up it disappears again.

![Screenshot_2020-11-30 Webmail Schreiben(1)](https://user-images.githubusercontent.com/5228369/100593820-2c839b00-32f9-11eb-9289-20da4635a464.png)

Here the width of the window is narrower and it appears some formatting menu but the top menu line shows the button to activate html although it is already activated. 

![Screenshot_2020-11-30 Webmail Schreiben(2)](https://user-images.githubusercontent.com/5228369/100593821-2d1c3180-32f9-11eb-887f-a5e44edead8b.png)

**Comment by alecpl** [comment] 2020-11-30 09:54
What Roundcube version? What browser? Does it work with all plugins disabled? Are there any errors in browser console?

ps. that extra button/bar is controlled by Roundcube, so it has not much to do with TinyMCE.

**Comment by kolbma** [comment] 2020-11-30 20:26
Roundcube 1.4.9  
Firefox 78.5.0esr  

No errors:
1 deprecation warning in tinymce
1 warning about non-standard zoom property
And a not related warning but maybe good to know for you... 
```
Request to access cookie or storage on “https://webmail.../program/resources/dummy.pdf” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.
```

But I've retried with a **new browser profile** and it's a problem in **combination** with the **mailvelope** add-on: https://github.com/mailvelope/mailvelope

I think I'll will open there a new issue?!

Do you have any hint I could forward to the guys there?

**Comment by alecpl** [comment] 2020-12-03 13:20
Works for me with Mailvelope 4.4.0 and Firefox 83.

**Comment by kolbma** [comment] 2020-12-03 17:00
@alecpl Do you have configured the plugin for your roundcube domain? By default the plugin works only in the domains of public webmail providers.  
I've also disabled the API feature for the domain. Because although it says this should work for Roundcube I don't get the Mailvelope Button shown in Roundcube if I enable the API feature.

**Comment by alecpl** [comment] 2020-12-07 14:00
I'm using the Mailvelope API, as this is what we use and support in Roundcube. I'll see how it works with disabled API when I have time.

**Comment by kolbma** [comment] 2020-12-07 14:40
@alecpl Yes no problem.  
We are switching to the API as well. With the API it was just a problem behind the keyboard, because the UX is differently.  
When switching you are still expecting the Mailvelope button and not some in Roundcube embedded buttons.
Although this is of course nice, but you have to know it.

**Comment by alecpl** [comment] 2020-12-19 19:20
I'm unable to reproduce using git-master and Firefox 84. I'm closing this as this is not supported setup.

**Closed by alecpl** 2020-12-19 19:20 UTC
Labels: need feedback
