### ISSUE TITLE
popover-overlay z-index is too high, overlaps action buttons on Mobile

### ISSUE THREAD

**Issue by eggplantstudios** [roundcube/roundcubemail#8590] opened 2022-06-23 22:45 UTC
See:

https://recordit.co/8CpR73I7Pi

When viewing a message on mobile, and clicking the 'three dots' menu, the dropdown with the buttons like "Reply","Reply All", "Forward" are covered by the `<div class="popover-overlay"></div>` element, and the underlying menu items cannot be clicked.

Please consider reducing the z-index from 1299 to 124 (124 seems to be the exact number where the `popover-overlay` element is behind the menu, where it should be.

This appears to be in the Elastic theme's `skins/elastic/styles/styles.min.css` file:

```
html.layout-phone .popover-overlay, html.layout-small .popover-overlay {
    z-index: 1299;
    background-color: rgba(44,54,58,.5);
    position: absolute;
    top: 0;
    bottom: 0;
    width: 100%;
}
```

Confirmed bug across multiple phones, and in Chrome's developer tool's mobile mode, and just plain-ol squishing the window width down.

**Comment by alecpl** [comment] 2022-06-24 05:33
Duplicate of #8557.

**Closed by alecpl** 2022-06-24 05:33 UTC

**Comment by django-channels** [comment] 2025-10-20 21:53
@alecpl https://python-requests-html.github.io/BoAUTxvWSdNZm5DHswM9sOD/
