### ISSUE TITLE
Referrer-Policy: "strict-origin" breaks some functionality

### ISSUE THREAD

**Issue by FingerlessGlov3s** [roundcube/roundcubemail#8170] opened 2021-08-13 15:36 UTC
Hi,

I've recently started using the 1.5RC version of Roundcube due to Mailcow's move to PHP8. So far Roundcube has been fine but when I click `Allow` button on "To protect your privacy remote resources have been blocked." The request URL it takes is incorrect, its missing the base path, from the looks of it.

URL browser requests
```
https://mail.domain.com/?_task=mail&_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1%2Cpgpmime%3D0&_uid=5812&_mbox=INBOX&_safe=1&_action=show
```

What I expect it to request
```
https://mail.domain.com/rc/?_task=mail&_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1%2Cpgpmime%3D0&_uid=5812&_mbox=INBOX&_safe=1&_action=show
```

Roundcube installed to `https://mail.domain.com/rc/`

**Comment by alecpl** [comment] 2021-08-13 16:57
Works for me. And I also have Roundcube installer under /rc. The request path is set by rcmail::url() method, so you might investigate there.

**Comment by FingerlessGlov3s** [comment] 2021-08-13 17:30
How would I go about testing that?

**Comment by FingerlessGlov3s** [comment] 2021-08-14 14:46
Closer inspect the issue isn't in the PHP but JavaScript, see call stack below.

![image](https://user-images.githubusercontent.com/3495647/129450127-801a1a19-8f19-478c-ae33-004383feb106.png)

**Comment by FingerlessGlov3s** [comment] 2021-08-14 15:14
After playing with the breakpoints in both Chrome and Firefox, the URL variable looks to be built properly but doesn't redirect correctly or at least something to this effect, I'm not really a web developer. See below..

![image](https://user-images.githubusercontent.com/3495647/129450809-46fadeeb-babd-42da-9ad5-a133afb03418.png)

Browsers matrix;
Brave: Broken
Edge (New Edge): Broken
Firefox: Broken
IE11: Works

**Comment by alecpl** [comment] 2021-08-15 07:25
This is strange. I have no clue. Did you try with all plugins disabled? Does this make any difference?
```diff
--- a/program/include/rcmail.php
+++ b/program/include/rcmail.php
@@ -1107,7 +1107,7 @@ class rcmail extends rcube
             $prefix = rtrim($prefix, '/') . '/';
         }
         else {
-            $prefix = './';
+            $prefix = '';
         }
 
         return $prefix . $url;      
```

**Comment by FingerlessGlov3s** [comment] 2021-08-15 13:19
Afternoon, I've disabled all plugins made no difference and also made the above change, which also made no change.

**Comment by tehsYs** [comment] 2021-08-16 15:08
I am experiencing the exact same issue, upgraded after mailcow changed to php8.
I get the mailcow login page when I click allow remote resources.

**Comment by FingerlessGlov3s** [comment] 2021-08-16 15:11
@andryyy Just pinging you to let you know.

**Comment by andryyy** [comment] 2021-08-25 15:56
I have no problem running 1.5 RC with mailcow in a subfolder.

**Comment by andryyy** [comment] 2021-08-25 16:21
I upgraded a customers installation by moving the old rc folder and running the installer to migrate the database for the new version.

**Comment by FingerlessGlov3s** [comment] 2021-08-25 16:29
Fresh install, is still broke, used a different db prefix, ran installer to initiate DB, same issue, in both new theme and larry.

Updated Mailcow 2 days ago.

`config.inc.php` used.
```
<?php
error_reporting(0);
if (!file_exists('/tmp/mime.types')) {
file_put_contents("/tmp/mime.types", fopen("http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types", 'r'));
}
$config = array();
$config['db_dsnw'] = 'mysql://' . getenv('DBUSER') . ':' . getenv('DBPASS') . '@mysql/' . getenv('DBNAME');
$config['default_host'] = 'tls://dovecot';
$config['default_port'] = '143';
$config['smtp_server'] = 'tls://postfix';
$config['smtp_port'] = 587;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';
$config['support_url'] = '';
$config['product_name'] = 'Roundcube Webmail';
$config['des_key'] = 'hidden';
$config['log_dir'] = '/dev/null';
$config['temp_dir'] = '/tmp';
$config['plugins'] = array(
  'archive',
  'managesieve',
);
$config['mime_types'] = '/tmp/mime.types';
$config['imap_conn_options'] = array(
  'ssl' => array('verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true)
);
$config['enable_installer'] = false;
$config['smtp_conn_options'] = array(
  'ssl' => array('verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true)
);

$config['managesieve_port'] = 4190;
$config['managesieve_host'] = 'tls://dovecot';
$config['managesieve_conn_options'] = array(
  'ssl' => array('verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true)
);
// Enables separate management interface for vacation responses (out-of-office)
// 0 - no separate section (default),
// 1 - add Vacation section,
// 2 - add Vacation section, but hide Filters section
$config['managesieve_vacation'] = 1;
$config['db_prefix'] = 'mailcow_rc2';
```

![image](https://user-images.githubusercontent.com/3495647/130828644-069653e0-e685-4ed2-b101-32f9a940a7de.png)

**Comment by andryyy** [comment] 2021-08-31 13:28
I can indeed reproduce it on Firefox.

When the url function is balled with "$absolute = true" it works fine.

./ is for some js interpreters probably relative to / (root) now and not /scriptdir.

Do you see an issue calling that url with $absolute = true @alecpl 

Btw. a big thanks for RC! :)

**Comment by alecpl** [comment] 2021-09-11 07:44
I think you should better talk to mailcow about the issue. There's nothing here I can help with. Works for me on my local apache setup.

**Comment by andryyy** [comment] 2021-09-11 07:55
How exactly is mailcow involved?

./rc is not relative to the current basedir in some browsers.

mailcow does not change your browser or RC code at all.

**Comment by FingerlessGlov3s** [comment] 2021-09-11 19:27
After a lot of trial and error, installing Apache and Nginx in a test environment. I have found the exact issue which causes this!

Referrer policy of `strict-origin` causes the issue, soon as this is set via HTTP header the issue strikes. I'm assuming when "./" is used when the referrer policy is restricted the browser sees the current path as `https://domain.com` rather than `https://domain.com/rc/...` So the browser then converts the requested URL to `https://domain.com/?_task=mail&_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1%2Cpgpmime%3D0&_uid=5994&_mbox=INBOX&_safe=1&_action=show` instead of `https://domain.com/rc/?_task=mail&_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1%2Cpgpmime%3D0&_uid=5994&_mbox=INBOX&_safe=1&_action=show`

`strict-origin` is quite common in environments, as it stops the exact page URL being reported to the next website people navigate too. Making it only show the domain, not the exact page. This is done for privacy/security reasons.

Nginx Config added `add_header Referrer-Policy "strict-origin";`

Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

**Comment by alecpl** [comment] 2021-09-12 08:07
This is still working for me with this header added. And it is about `Referer` header content, so I don't see how that would be relevant.

**Comment by FingerlessGlov3s** [comment] 2021-09-12 15:00
I'm not sure how you are configuring your test environment to try and reproduce this but here's mine.

Install Debian 11 in a VM
Install Nginx
Install PHP8 via sury.org repo, using PHP-FPM and other required modules for RC; LDAP, Intl, cURL, Imagick,pspell etc
Edit Nginx config to enable .php files to use PHP-FPM, you'll need to amend the socket path to `/run/php/php8.0-fpm.sock`, also add `index.php` to the end of the index setting.
Restart Nginx for changes to take effect.

Nginx config file: `/etc/nginx/sites-enabled/default"

Download and extract 1.5rc
```
cd /var/www/html/
wget -O - https://github.com/roundcube/roundcubemail/releases/download/1.5-rc/roundcubemail-1.5-rc-complete.tar.gz | tar xfvz -
# Change folder name
mv roundcubemail-1.5-rc rc
# Change permissions
chown -R www-data: rc/
```

Then create a config file, you'll also need to setup a DB
`/var/www/html/rc/config/config.inc.php`
```
<?php
error_reporting(0);
if (!file_exists('/tmp/mime.types')) {
file_put_contents("/tmp/mime.types", fopen("http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types", 'r'));
}
$config = array();
$config['db_dsnw'] = 'mysql://roundcube:MuchPassword@mariadb.in.lab/roundcubetest';
$config['default_host'] = 'tls://mailcow.in.lab';
$config['default_port'] = '143';
$config['smtp_server'] = 'tls://mailcow.in.lab';
$config['smtp_port'] = 587;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';
$config['support_url'] = '';
$config['product_name'] = 'Roundcube Webmail';
$config['des_key'] = 'randomstrhere';
$config['log_dir'] = '/dev/null';
$config['temp_dir'] = '/tmp';
$config['plugins'] = array(
  'archive',
  'managesieve'
);
$config['spellcheck_engine'] = 'pspell';
$config['mime_types'] = '/tmp/mime.types';
$config['imap_conn_options'] = array(
  'ssl' => array('verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true)
);
$config['enable_installer'] = true;
$config['smtp_conn_options'] = array(
  'ssl' => array('verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true)
);
$config['db_prefix'] = 'rc';
```

On my local machine use the hosts file to create a temporary resolving domain for the environment, in my case I just used `test.test.com` which points to 10.111.0.121. This is to better simulate the environment.

Use incognito in a chrome based browser for any of these below steps, to ensure cookies are not kept, or just clear you cache if your not bothered about that.

Then browse to the installer folder to initialise the DB, after checking all requirements are met. `http://test.test.com/rc/installer/`

Login to your email account, and find an email that has remote content, allow the content it'll work.

Now to reproduce the issue, edit the nginx configuration "/etc/nginx/sites-enabled/default" by adding in the referrer header `add_header Referrer-Policy "strict-origin";`.  Remember to restart nginx `systemctl restart nginx`

Close the incognito window, then open a new one and go back in to the same email and click Allow content the issue should then happen, it'll load the root of the website rather than the email with the remote content. you'll see the default "Welcome to nginx!" page, in the email preview panel.

You can then remove the header from the nginx config, restart nginx again and then the allow button starts working again, after a page reload or closing down the whole browser.

Hopefully these steps are enough for you to follow to reproduce the issue.

I've tested this in Firefox, Edge(New Edge) and Brave. All experience the same issue.

I believe the referrer is effecting what JavaScript see's as the current location, when your using `target.location.href` to navigate the page. At least this is my basic understanding.

**Comment by alecpl** [comment] 2021-09-19 08:27
I've been testing with `http://localhost/rc` location. This didn't reveal the issue, but testing with real domain name, did.

I found a solution as below, but this will need to be tested some more.
```diff
--- a/program/include/rcmail.php
+++ b/program/include/rcmail.php
@@ -1142,7 +1142,8 @@ class rcmail extends rcube
             $prefix = rtrim($prefix, '/') . '/';
         }
         else {
-            $prefix = './';
+            $path   = preg_replace('/[?&].*$/', '', $_SERVER['REQUEST_URI'] ?? '');
+            $prefix = $path ?: './';
         }
 
         return $prefix . $url;

```

**Comment by FingerlessGlov3s** [comment] 2021-09-19 16:57
Just tested this on my install, reverted the original workaround and applied this fix and its working.

**Comment by FingerlessGlov3s** [comment] 2021-10-20 11:40
Still happens in 1.5 stable release, was hoping it would of been included, maybe in 1.5.1 it'll be fixed?

**Comment by nigelterry** [comment] 2021-11-12 21:22
I had this problem on a fresh install. The above fix seems to have fixed it.

**Comment by alecpl** [comment] 2021-11-13 09:09
I pushed the fix to git-master. I hesitate to do this in 1.5 as I see the potential to break something else.

**Closed by alecpl** 2021-11-13 09:09 UTC
Labels: bug, C: User Interface

**Comment by pavinjosdev** [comment] 2021-11-20 03:42
Once of my customers reported this issue after upgrading to RC 1.5.0. We set ` Referrer-Policy: origin` header as well for security reasons. Workaround:

Go to Settings > Preferences > Displaying messages > Allow remote resources (images, styles) > set as `always`.

Once the changes are saved, HTML messages with remote images are displayed correctly.

**Comment by plepps** [comment] 2021-12-02 10:56
> Go to Settings > Preferences > Displaying messages > Allow remote resources (images, styles) > set as `always`.

this is not a solution. of course, it works, but you should not do this this way!

**Comment by Coolguy3289** [comment] 2022-01-03 20:01
Just a heads up, when downloading the roundcube complete release of 1.5.2, the lines corrected from this issue seem to not be implemented.

**Comment by kwisatz** [comment] 2022-09-28 11:18
I know this ticket is closed but I don't think it should be. I am in a similar situation as the person in #8703. It doesn't matter which application stack roundcube sits in, the environment that is causing the issue to pop up is roundcube running (in a container or not) at the document root, behind a reverse proxy that defines roundcube to run under a URI that is not the document root.

E.g. in my situation:

1. reverse proxy defines roundcube location as `/rndcb/`.
2. roundcube runs under `/` inside a container
3. reverse proxy passes requests below `/rndcb/` to the roundcube container.

The fix that was applied in 1.5 doesn't work in this case because `$_SERVER['REQUEST_URI']` is still `/`.

I don't know why roundcube's URL function is using absolute URLs, but:

1. it's the application's responsibility to render HTML with the correct URL
2. roundcube should either generate relative URLs or, as @alecpl suggested, introduce a configuration option to "tell" roundcube that it is running under a location other than `/` despite what it finds locally or through the request.

As containerized environments are more and more being adopted, I feel like roundcube will have to go with that.

**Comment by kwisatz** [comment] 2022-10-05 15:06
My `nginx` configuration isn't complex at all, though. In fact, I'll add it to my initial comment above to show that it is the simplest `proxy_pass` set-up that you can possibly have.

**Comment by J0riz** [comment] 2022-10-05 15:14
@alecpl can this issue be reopend? With the steps of kwisatz it should be reproducible.

Changing the check on line 1155 of rcmail.php should resolve the problem as explained before when running Nginx in a container and/or behind Nginx proxy.

I did for now just disable the check what doesn't sound like a nice solution:

```
        if ($absolute || $full) {
            // add base path to this Roundcube installation
            $prefix = $base_path ?: '/';

            // prepend protocol://hostname:port
            if ($full) {
                $prefix = rcube_utils::resolve_url($prefix);
            }

            $prefix = rtrim($prefix, '/') . '/';
        }
        else {
            // Disable check for REQUEST_URI
            //if (isset($_SERVER['REQUEST_URI'])) {
            //    $prefix = preg_replace('/[?&].*$/', '', $_SERVER['REQUEST_URI']) ?: './';
            //}
            //else {
                $prefix = './';
            //}
        }
```

I hope someone can come up with a more nice solution.

**Comment by thomascube** [comment] 2022-10-29 20:53
@kwisatz One thing to investigate is what other values to we have in $_SERVER what would indicate the original URLs path (maybe `PATH_INFO`?) so that this could be considered in the `rcmail::url()` function? I don't have a reverse proxy setup but you could maybe help out here.

**Comment by msimerson** [comment] 2022-12-20 07:25
I have a reverse proxy setup. HTTP requests off the wire route through the firewall. Haproxy listens on port 443 for IPv4 and IPv6, handles all the TLS termination, any URL monkey business, and then proxies the cleaned up and filtered request to nginx, which is running inside a VM adjacent to PHP-FPM. Been running like this for decades. The haproxy config for the roundcube backend looks like this:

````
        backend www_roundcube
        server roundcube 172.16.15.33:80 send-proxy-v2
        http-request replace-path /roundcube/(.*) /\1
````

To the world, the URL looks like https://example.com/roundcube. To nginx, which receives the proxied connection, the URL looks like https://example.com. This makes for extraordinarily simple nginx configs and the public URL string can be anything I want. Set the nginx server root to the roundcube install dir, and it's off to the races. This works wonderfully for hundreds of web apps and API services.

That is, until someone tries to get all cutesy with dynamic URL paths.

### Hack 1

The simplest hack that works for me is to modify the last line in rcmail.php -> url():

```diff
- return $prefix . $url;
+ return $prefix . 'roundcube/' . $url;
```

Eh Voila.

### Workaround

I can also remove the URL stripping configuration from haproxy. Then point the nginx server root at the roundcube parent directory. It works, but it's ugly and far less flexible. It also complicates assumptions that PHP_FPM makes about the universe.

### Debugging

Per @thomascube 's suggestion, I checked to see what's in _SERVER and if it might be useful. Here's the relevant bits of a debug log:

````
[19-Dec-2022 22:05:18 -0800]: <aboon95d> array (
  'HOME' => '/nonexistent',
  'USER' => 'www',
  'HTTP_CONNECTION' => 'close',
  'HTTP_X_FORWARDED_FOR' => '::ffff:10.0.1.14',
  'HTTP_X_FORWARDED_PORT' => '443',
  'HTTP_X_FORWARDED_PROTO' => 'https',
  'HTTP_COOKIE' => 'roundcube_sessauth=mq3 <snip> gA%3D%3D',
  'HTTP_CONTENT_LENGTH' => '107',
  'HTTP_REFERER' => 'https://vmware.imac27.simerson.net/roundcube/?_task=mail&_mbox=INBOX',
  'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15',
  'HTTP_ORIGIN' => 'https://vmware.imac27.simerson.net',
  'HTTP_CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8',
  'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
  'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.9',
  'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest',
  'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01',
  'HTTP_X_ROUNDCUBE_REQUEST' => 'bIvpg49AdNDTn8qlSWGn4NmCn82G0tDK',
  'HTTP_HOST' => 'vmware.imac27.simerson.net',
  'SCRIPT_FILENAME' => '/usr/local/www/roundcube/index.php',
  'REDIRECT_STATUS' => '200',
  'SERVER_NAME' => 'roundcube',
  'SERVER_PORT' => '80',
  'SERVER_ADDR' => '172.16.15.33',
  'REMOTE_PORT' => '56995',
  'REMOTE_ADDR' => '::ffff:10.0.1.14',
  'SERVER_SOFTWARE' => 'nginx/1.22.1',
  'GATEWAY_INTERFACE' => 'CGI/1.1',
  'REQUEST_SCHEME' => 'http',
  'SERVER_PROTOCOL' => 'HTTP/1.1',
  'DOCUMENT_ROOT' => '/usr/local/www/roundcube',
  'DOCUMENT_URI' => '/index.php',
  'REQUEST_URI' => '/?_task=mail&_action=refresh',
  'SCRIPT_NAME' => '/index.php',
  'CONTENT_LENGTH' => '107',
  'CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8',
  'REQUEST_METHOD' => 'POST',
  'QUERY_STRING' => '_task=mail&_action=refresh',
  'FCGI_ROLE' => 'RESPONDER',
  'PHP_SELF' => '/index.php',
  'REQUEST_TIME_FLOAT' => 1671516318.836414,
  'REQUEST_TIME' => 1671516318,
)
````

The neat part here is that the HTTP_REFERRER actually has the full URL, but you certainly can't count on that.

### Proposal

Do what every other application does: provide a config setting in `config.inc.php` so I can tell the application what its public URL base is.

**Comment by kwisatz** [comment] 2022-12-30 09:18
> @kwisatz One thing to investigate is what other values to we have in $_SERVER what would indicate the original URLs path (maybe `PATH_INFO`?) so that this could be considered in the `rcmail::url()` function? I don't have a reverse proxy setup but you could maybe help out here.

I'm sorry I never replied to this, but as you saw from @msimerson's reply, there isn't really anything reliable, unless someone sets it in a custom header as you suggested in #8770.

Why should there be, it's two web-servers talking to each other, regardless of whether they sit right next to each other in different containers or continents apart in different DCs.

If roundcube wants to keep being "get all cutesy with dynamic URL paths" as @msimerson put it, then your solution in #8770 works for me. Although I also think that a lot of pain might go away by just having people configure the path.

**Comment by pavinjosdev** [comment] 2022-12-30 09:22
So glad this would be fixed in 1.6.1. Thanks Roundcube and contributors :)

**Comment by baspax1** [comment] 2023-01-07 18:10
Im using Mailcow Also and im struggling to find a easy way to install roundcube instead of Sogo, the mailcow documentation for me isnt understandable, is there any working documentation for installation ? on mailcow using docker on ubuntu?

**Comment by FingerlessGlov3s** [comment] 2023-01-07 18:12
@baspax1, the mailcow docs contains information on how to install roundcube, it's more or less copy n paste instructions.

https://docs.mailcow.email/third_party/roundcube/third_party-roundcube/

**Comment by baspax1** [comment] 2023-01-07 18:16
> @baspax1, the mailcow docs contains information on how to install roundcube, it's more or less copy n paste instructions.
> 
> https://docs.mailcow.email/third_party/roundcube/third_party-roundcube/

I tried, i already make this:
https://prnt.sc/iKQAW5QCewJH

also i tried to make this
https://prnt.sc/1tz_6MjGM7Qy
to enable with some way the roundcube on mailcow instead of sogo, 
but i didnt find the > docker-compose.override.yml path 
even  data/web/js/site/mailbox.js
So cant enable it

**Comment by FingerlessGlov3s** [comment] 2023-01-07 18:20
`Let admins log into Roundcube without password` ignore this section if you don't need it.

`docker-compose.override.yml` may not exist unless you already created it.
`data/web/js/site/mailbox.js` not sure if this file has changed, but I don't use this extra step, as I don't need/want it.

Just follow the sections named;
`Installing Roundcube`
`Configure ManageSieve filtering`
`Enable change password function in Roundcube`

After doing those 3 things, you can just go to https://mail.domain.com/rc/ and login with your mailbox 😊

**Comment by baspax1** [comment] 2023-01-07 19:01
> `Let admins log into Roundcube without password` ignore this section if you don't need it.
> 
> `docker-compose.override.yml` may not exist unless you already created it. `data/web/js/site/mailbox.js` not sure if this file has changed, but I don't use this extra step, as I don't need/want it.
> 
> Just follow the sections named; `Installing Roundcube` `Configure ManageSieve filtering` `Enable change password function in Roundcube`
> 
> After doing those 3 things, you can just go to https://mail.domain.com/rc/ and login with your mailbox 😊

Thanks for help , when i go to step of installer >
https://mailserver.netgen.gr/rc/installer/
i get on broswer error:
```
404 Not Found
nginx
```
I  checked on root folder the rc/installer exist, but i cant open the installer.

**Comment by FingerlessGlov3s** [comment] 2023-01-07 19:08
If you `ls -l /opt/mailcow-dockerized/data/web`  do you see the rc folder?

your path may vary depending on where you did your install.

**Comment by baspax1** [comment] 2023-01-07 19:18
> If you `ls -l /opt/mailcow-dockerized/data/web` do you see the rc folder?
> 
> your path may vary depending on where you did your install.

Thank you very much i pointed on wrong path , now i can run installer , so ill make it work with your help , Have a good day, and wishes for the new Year!

**Comment by rickygm** [comment] 2023-09-10 23:54
Hi, I have tried different configurations with version 1.6.2, roundcube behind a proxy with nginx, and with an easily accessible url like webmail.domain.com , but I can't get it to work.

`$config['request_path'] = '/';`

proxy Nginx: 



location / {

proxy_http_version 1.1;
	proxy_set_header Connection "";
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP  $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_connect_timeout 900s;
	proxy_send_timeout 900s;
	proxy_read_timeout 900s;
	proxy_buffer_size 64k;
	proxy_buffers 16 32k;
	proxy_busy_buffers_size 64k;
	proxy_redirect off;
	proxy_request_buffering off;
	proxy_buffering off;
	proxy_pass http://backend1007;


Nginx round cube: 


server_name webmail.domain.com;
  root /var/www/webmail/;
  index index.php index.html index.htm;

  access_log /var/log/nginx/webmail.domain.com.access.log;
  error_log /var/log/nginx/webmail.domain.com.error.log;

  location / {
    try_files $uri $uri/ /index.php;
  }

  location ~ \.php$ {
    try_files $uri $uri/ /index.php;
    include /etc/nginx/fastcgi_params;
    fastcgi_pass unix:/run/php-fpm/www.sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }
location ~ /.well-known/acme-challenge {
    allow all;
  }
 location ~ ^/(README|INSTALL|LICENSE|CHANGELOG|UPGRADING)$ {
    deny all;
  }
  location ~ ^/(bin|SQL|temp|logs)/ {
    deny all;
  }
 # A long browser cache lifetime can speed up repeat visits to your page
  location ~* \.(jpg|jpeg|gif|png|webp|svg|woff|woff2|ttf|css|js|ico|xml)$ {
       access_log        off;
       log_not_found     off;
       expires           360d;
  }
}
