### ISSUE TITLE
[FR] Show directory when searh in all directories

### ISSUE THREAD

**Issue by antiuser** [roundcube/roundcubemail#8952] opened 2023-03-23 05:00 UTC
Hi there!

Will be great to show directory name near message when showing search result using scope "all directories".
Now if i search message in all directories i cannot understand when search is found this message. Will be great to tag this messages.

Thanks!

**Comment by alecpl** [comment] 2023-03-25 08:36
Duplicate of #7950.

**Closed by alecpl** 2023-03-25 08:36 UTC
