### ISSUE TITLE
Changing subscribtion from folder scrolls to beginning of folder list 

### ISSUE THREAD

**Issue by blakawk** [roundcube/roundcubemail#5474] opened 2016-10-13 14:35 UTC
When checking or unchecking a folder from "Settings > Folders" list, the folder list scroll bar is reset to the top. This is annoying when unsubscribing from several folders in a row in a long folder list.

This issue happens only the first time the folder list is displayed, then the next selections correctly keep the folder list where it was before changing subscription.

Version is 1.2.1, skin is Larry.

**Comment by alecpl** [comment] 2016-10-13 14:53
Duplicate of #5447.

**Closed by alecpl** 2016-10-13 14:53 UTC
Labels: bug, C: User Interface
