### ISSUE TITLE
Failed logins info

### ISSUE THREAD

**Issue by grape6** [roundcube/roundcubemail#6809] opened 2019-06-19 09:25 UTC
If RCM has got ALERT response from IMAP server after AUTHENTICATE LOGIN,
seems it should be presented to user (not only "Login failed" msg) according to RFC 3501

for ex (from dovecot)
C: A0002 AUTHENTICATE LOGIN
...
S: A0002 NO [ALERT] country blocked

RCM git.

**Comment by alecpl** [comment] 2019-06-19 09:32
Duplicate of #5060.

**Closed by alecpl** 2019-06-19 09:32 UTC
