### ISSUE TITLE
Autofill the names of recipients

### ISSUE THREAD

**Issue by Pyanepsion** [roundcube/roundcubemail#6910] opened 2019-09-03 09:48 UTC
Hello,
- Debian 10
- Roundcube 1.3.8
- JQueryui 1.12.0
- Filesystem_attachments 1.0

Roundcube was installed at the same time as Debian.
When I type a name as a recipient, the complementation is only done on the names of the groups.
How to correct this?

**Comment by alecpl** [comment] 2019-09-03 10:10
What PHP version? SQL or LDAP addressbook? Any errors in log? You should try 1.3.10.

**Comment by Pyanepsion** [comment] 2019-09-03 10:35
PHP 7.3.9-1
The "u" appears in the names of the users and in those of the groups. Only groups appear when I type "u".
![roundcube-01](https://user-images.githubusercontent.com/28216827/64166226-fd0c8700-ce46-11e9-86a7-c81ce69f7961.png)
The "s" only appears in the names of the users. Nothing appears when I type s.
![roundcube-02](https://user-images.githubusercontent.com/28216827/64166228-fd0c8700-ce46-11e9-8ac8-6272551204c6.png)
When I create a contact in the contact list, the email field disappears from the information display, but still exists.
![roundcube-03](https://user-images.githubusercontent.com/28216827/64166229-fd0c8700-ce46-11e9-8b76-df4e3fcf708a.png)

I am on an ISPConfig NGINX server.
How to update on Roundcube 1.3.10?

**Comment by alecpl** [comment] 2019-09-03 10:57
This sounds like the bug fixed in 1.3.10. Ask ISPConfig for how to update. Duplicate of  #6744.

**Closed by alecpl** 2019-09-03 10:57 UTC
Labels: need feedback

**Comment by Pyanepsion** [comment] 2019-09-03 11:42
The bug has been fixed by the bug fix explanation in [parsing vCard data using PHP 7.3 due to an invalid regexp](https://github.com/roundcube/roundcubemail/commit/fe90903fa1ff59c0da278fee2ee6a0e1f6273a06).
Thank you.
