### ISSUE TITLE
Email control buttons disappear after browser window resized

### ISSUE THREAD

**Issue by darren12345** [roundcube/roundcubemail#9135] opened 2023-09-13 11:44 UTC
This has been happening for a while, and still exists in RC 1.6.2. I can't reliably reproduce it to understand the steps that trigger it, but it's definitely to do with the browser window being resized and then made maximum size again.
When this happens (presumably causing the interface to be redrawn), the buttons above the reading pane (reply, reply-all, delete etc) disappear. It takes a refresh to get them back. Screen shot attached.
My regular browser is Firefox, currently at v117.
![RC bug](https://github.com/roundcube/roundcubemail/assets/12751052/6b417a78-97d7-4a15-bad4-b0c4bddc3d6c)

**Comment by alecpl** [comment] 2023-09-14 06:15
Duplicate of #9085.

**Closed by alecpl** 2023-09-14 06:15 UTC
