### ISSUE TITLE
failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by crasheg** [roundcube/roundcubemail#5948] opened 2017-09-09 05:34 UTC
Rouncube 1.3.0
Windows 10

[16-Aug-2017 08:41:43 UTC] PHP Warning:  file_get_contents(D:\server\public_html\*\temp/47d3da756310a48c5c97ef4c74f96205.tmp): failed to open stream: No such file or directory in D:\server\public_html\*\program\steps\mail\get.inc on line 536

File really not exists. Any ideas?
Such log errors could be repeated 20-30 times per day with various files.

**Comment by alecpl** [comment] 2017-09-09 10:11
Duplicate of #5933.

**Closed by alecpl** 2017-09-09 10:11 UTC
