### ISSUE TITLE
Show only folders with unread messages

### ISSUE THREAD

**Issue by internationils** [roundcube/roundcubemail#7006] opened 2019-11-09 15:41 UTC
I am looking for a way to see only folders with unread messages. I have a lot of folders (server side filtering) and always need to scroll and look for the folders with unread mails. I don't want to just skip to the next unread mail since I often have some folders with unread mails left in them for later work / processing.

**Comment by alecpl** [comment] 2019-11-10 07:02
Duplicate of #5032.

**Closed by alecpl** 2019-11-10 07:02 UTC
