### ISSUE TITLE
rcmail_attachment_handler::body PHP warning at "file_get_contents" (no such file or directory)

### ISSUE THREAD

**Issue by codegain** [roundcube/roundcubemail#7876] opened 2021-02-08 16:10 UTC
Hi,

I don't know if this is a bug, but I'm getting a lot of these PHP warnings (like 60 time per day):

```
Warning: file_get_contents([roundcube-dir]/temp/RCMTEMPthumb1eb4874caaed0109e3c6a984ab0d4543.tmp): failed to open stream: No such file or directory
```

The stacktrace:
```
ErrorException: Warning: file_get_contents([roundcube-dir]/temp/RCMTEMPthumb1eb4874caaed0109e3c6a984ab0d4543.tmp): failed to open stream: No such file or directory
#3 /program/steps/mail/get.inc(528): rcmail_attachment_handler::body
#2 /program/steps/mail/get.inc(128): include_once
#1 /index.php(306): include
#0 /index.php(26): null
```
(Currently using Roundcube 1.4.10)

Query parameters:
```
_action=get
_embed=1
_mbox=INBOX
_mimeclass=image
_part=[some integer]
_thumb=1
_token=[some token]
_uid=[some uid]
```

This doesn't seem related to any user or browser as it happens to a variaty of users.
The `temp` folder exists and is writeable by apache and php. There are a lot of files with "RCMTEMPthumb..." inside of it.

Is this a bug or am I safe to ignore these warnings?

**Comment by alecpl** [comment] 2021-02-09 07:42
A duplicate of #6657. I've been never able to reproduce the issue. Might be some misconfiguration or bug somewhere.

The issue itself is probably harmless, but it would be nice to track it down. From the filename I see it's about a thumbnail of an image attachment. So, the worse case is that user will not see the thumbnail in mail preview. I'm guessing that maybe conversion to a thumbnail is not working, but the code still expects the file to exist, or it's some race condition where we remove the thumbnail before we actually want to use it.

**Comment by codegain** [comment] 2021-02-09 13:17
@alecpl Thanks for the explanation. I will report back if I have some additional information or was able to reproduce it myself.

**Comment by alecpl** [comment] 2021-07-18 07:51
Let's close this. We'll reopen if you provide any more information.

**Closed by alecpl** 2021-07-18 07:51 UTC
Labels: need feedback
