### ISSUE TITLE
Three SQL tables are missing primary key (cache, cache_shared, dictionary)

### ISSUE THREAD

**Issue by bluikko** [roundcube/roundcubemail#5647] opened 2017-02-15 14:38 UTC
The following tables are missing primary key:
- cache
- cache_shared
- dictionary

Galera replication for MySQL requires primary key on all tables. Would it be possible to add the required PK to those tables?

If I would like to add the PK by myself, is the `cache_key` unique (for the two cache tables)? For `dictionary` table, it would seem the `user_id` is unique already, or should it be (`user_id`,`language`)?

**Comment by alecpl** [comment] 2017-02-15 14:52
Duplicate of #5439. Fixed in 1.3-beta.

**Closed by alecpl** 2017-02-15 14:52 UTC

**Comment by bluikko** [comment] 2017-02-15 15:11
Oops. Searched only open issues. My apologies.
