### ISSUE TITLE
Spanish (Latin America) unusable

### ISSUE THREAD

**Issue by chriskulbacki** [roundcube/roundcubemail#7784] opened 2020-12-15 11:46 UTC
Hi all,
Just wanted to mention that the language Spanish (Latin America) never gets saved in the Roundcube preferences.

The code for Spanish (Latin America) is 'es_418':

program/localization/index.inc:
`'es_419' => 'Spanish (Latin America)',`

...while during the saving process digits are not allowed:

program/steps/settings/save_prefs.inc
`'language'     => rcmail_prefs_input('language', '/^[a-zA-Z_-]+$/'),`

Also, 'es_419' is 6 characters, while the type of the language column in the 'users' database table is varchar(5), so that probably should get updated as well.

**Comment by alecpl** [comment] 2020-12-15 11:55
Duplicate of #6851.

**Comment by thomascube** [comment] 2020-12-17 13:03
@alecpl What about the regex check in [rcmail_action_settings_prefs_save](https://github.com/roundcube/roundcubemail/blob/master/program/actions/settings/prefs_save.php#L42) aka save_pres.inc?

**Comment by alecpl** [comment] 2020-12-17 13:10
Oh, I missed the regex part.

**Comment by alecpl** [comment] 2020-12-19 08:07
Fixed.

**Closed by alecpl** 2020-12-19 08:07 UTC
Labels: C: Core functionality, bug
