### ISSUE TITLE
elastic: usability questions/annotations

### ISSUE THREAD

**Issue by HLeithner** [roundcube/roundcubemail#6400] opened 2018-08-19 08:23 UTC
Just some questions and annotations

* list view doesn't respect config settings "After message delete/move display the next message"
* selecting (click or keyboard) a closed threads opens the thread that's a bit annoying because dealing the thread is much harder (should only open if clicked on the arrow or pressing the right arrow key)
* deleting the first post of a thread doesn't decrease indent (don't know if this is easily fixable)
* Threads button on a mailbox with disabled thread view is useless, maybe it would be nice if you can active or disable thread view in this button?
* Compose button is really far away from main work space
* Will it be possible to resize the 3 frames
* Will it be possible to change the view to 2 columns only or 2columns + message area at the bottom?

Everything mentioned is only my opinion and sorry if you already answered it and I missed it.

**Comment by alecpl** [comment] 2018-08-20 06:57
> -  list view doesn't respect config settings "After message delete/move display the next message"

works for me

> - selecting (click or keyboard) a closed threads opens the thread that's a bit annoying because dealing the thread is much harder (should only open if clicked on the arrow or pressing the right arrow key)

I like the current behavior

> - deleting the first post of a thread doesn't decrease indent (don't know if this is easily fixable)

should be fixable

> - Threads button on a mailbox with disabled thread view is useless, maybe it would be nice if you can active or disable thread view in this button?

we have more such buttons that should be disabled when all options in their menu are disabled, so we'll need some more general aproach on these.

> - Compose button is really far away from main work space

That was a requested change to have it always available, not only from Mail UI. Another option would be to add Compose button also in the content toolbar. I'm not sure I'd like that.

> - Will it be possible to resize the 3 frames
> - Will it be possible to change the view to 2 columns only or 2columns + message area at the bottom?

Maybe in the future but not soon. Both are not easy to implement. I probably will not work on this.

**Comment by HLeithner** [comment] 2018-08-20 09:01
>> list view doesn't respect config settings "After message delete/move display the next message"

>works for me

Seams my fault, works if you activate the setting and save it^^

>> selecting (click or keyboard) a closed threads opens the thread that's a bit annoying because dealing the thread is much harder (should only open if clicked on the arrow or pressing the right arrow key)

> I like the current behavior

I get about 0-100 github notifications per hour for different issues, for many of them I check the subject and delete the thread or open the github page. That's the main use case for me. Real mailinglists done have the problem (at least for me).

Maybe an alternative way to delete the selected thread?

>> deleting the first post of a thread doesn't decrease indent (don't know if this is easily fixable)

> should be fixable

need an own issue?

>> Threads button on a mailbox with disabled thread view is useless, maybe it would be nice if you can active or disable thread view in this button?

> we have more such buttons that should be disabled when all options in their menu are disabled, so we'll need some more general aproach on these.

thx for the info

>> Compose button is really far away from main work space

> That was a requested change to have it always available, not only from Mail UI. Another option would be to add Compose button also in the content toolbar. I'm not sure I'd like that.

I understand but it's its still a bit miss placed as 'context' switching menu button^^

>> Will it be possible to resize the 3 frames
Will it be possible to change the view to 2 columns only or 2columns + message area at the bottom?

> Maybe in the future but not soon. Both are not easy to implement. I probably will not work on this.

ok thx for the info no problem for me.

**Comment by alecpl** [comment] 2018-08-20 09:13
>>>  selecting (click or keyboard) a closed threads opens the thread that's a bit annoying because dealing the thread is much harder (should only open if clicked on the arrow or pressing the right arrow key)

>>    I like the current behavior

> I get about 0-100 github notifications per hour for different issues, for many of them I check the subject and delete the thread or open the github page. That's the main use case for me. Real mailinglists done have the problem (at least for me).

Actually I see that in 1.3 we did not expand the thread, so it in fact might be a regression and we probably should fix it.

Feel free to create separate tickets for the bugs. The rest would probably be closed for now.

**Comment by thomascube** [comment] 2018-08-20 11:47
>>  Compose button is really far away from main work space

I agree to this.

> That was a requested change to have it always available, not only from Mail UI.

This sounds like a freak case to me.

> Another option would be to add Compose button also in the content toolbar. I'm not sure I'd like that.

Many modern apps (especially on mobile) have a round (+) button on the lower right corner which is used to create a new "something" depending on the context (e.g. mail => new message, contacts => new contact, folders => new folder)
I think this has become a well known and accepted UI pattern and we should follow that.

**Comment by alecpl** [comment] 2018-08-20 11:51
We have this on mobile. You say we should display that "round +" thing also on desktop?

I see nothing wrong with Compose button available from settings or addressbook, it's much faster to go directly to compose screen from these places. That being said, for Plesk/Kolab variant we moved the button from taskbar to content toolbar, but it's because Kolab is not so much mail oriented.

**Comment by alecpl** [comment] 2018-09-12 10:14
BTW, Gmail has the Compose button in the same position.
I created 
#6443 , #6444 and #6445. Closing this one.

**Closed by alecpl** 2018-09-12 10:14 UTC
Labels: C: User Interface

**Comment by HLeithner** [comment] 2018-09-12 12:04
Ok thx for creating the issues... I personally doesn't like gmail ;-)

Could you say anything to https://github.com/roundcube/roundcubemail/pull/6384 if you don't want to merge it or fix it in another way I have to integrate it in to my upgrade procedure. Just wanted to know.
