### ISSUE TITLE
IDNA_DEFAULT

### ISSUE THREAD

**Issue by syncgw** [roundcube/roundcubemail#6252] opened 2018-04-19 07:10 UTC
PHP Warning:  Use of undefined constant IDNA_DEFAULT - assumed 'IDNA_DEFAULT' 
rcube_utils.php: 908       $options = IDNA_DEFAULT;

**Comment by alecpl** [comment] 2018-04-19 07:12
Duplicate of #6244.

**Closed by alecpl** 2018-04-19 07:12 UTC

**Comment by syncgw** [comment] 2018-04-19 07:14
sorry...
