### ISSUE TITLE
Ouath not working

### ISSUE THREAD

**Issue by arunodhayam1998** [roundcube/roundcubemail#8321] opened 2021-11-20 08:56 UTC
Hi, I have keycloak and Roundcube webmail in docker. simply I have hosted in localhost. I have done integration of keycloak with roundcube. But there is a routing issue occured. which means
1. Put localhost:9005 its routed to roudcube webmail
![Screenshot from 2021-11-20 14-17-07](https://user-images.githubusercontent.com/71403617/142720400-c78c9054-17fe-4b6a-a83e-ff24fe1502bb.png)
2. When clicking the **log in with keycloak** Button it routed to keycloak login page
![Screenshot from 2021-11-20 14-17-17](https://user-images.githubusercontent.com/71403617/142720438-6b648809-edcc-401d-ae5a-bde81899ed91.png)
3. After adding the username and password to the keycloak login page it routed to the incompleted Roundcube webmail page again
![Screenshot from 2021-11-20 14-17-37](https://user-images.githubusercontent.com/71403617/142720461-c26ccce3-eb6a-4b76-a67a-b0e76537b50e.png)
Why it's routed to the webmail login page instead of roudcube webmail user dashboard??

**Roundcube Oauth Configurations**
![Screenshot from 2021-11-20 14-23-37](https://user-images.githubusercontent.com/71403617/142720547-babd8e6c-8bbe-4c16-b061-77127c538052.png)

**Keycloak configurations**
![Screenshot from 2021-11-20 14-24-45](https://user-images.githubusercontent.com/71403617/142720588-40ff5952-e48e-476d-9e84-e76e9b957fe0.png)
![Screenshot from 2021-11-20 14-25-02](https://user-images.githubusercontent.com/71403617/142720591-20d73d45-fc61-4bd4-a5bd-676dddc1dd86.png)

Please help with this..

**Comment by arunodhayam1998** [comment] 2021-11-20 09:05
I am using docker roundcube version 1.5 (roundcube/roundcubemail:1.5-beta-apache)

**Comment by stoffus** [comment] 2021-11-20 13:12
Just an observation - you are assigning an array to `$config['oauth_scopes']` when the comment states that it should be a string.

**Comment by arunodhayam1998** [comment] 2021-11-20 14:00
I have fixed the problem with add the this $config['assets_path'] = '/'; value in config.inc.php

**Comment by alecpl** [comment] 2021-11-21 07:31
Duplicate of #8144.

**Closed by alecpl** 2021-11-21 07:31 UTC
