### ISSUE TITLE
Html/plaintext button error

### ISSUE THREAD

**Issue by Rasmusbdk** [roundcube/roundcubemail#7175] opened 2020-01-15 09:59 UTC
After upgrading from RC I am suffering an error with the plaintext/html toggler in tinymce.

I am forcing htmleditor with the following settings in config:

```
$config['htmleditor'] = 1;
$config['dont_override'] = array('htmleditor');
```

However, only the icon is hidden in tinyMCE toolbar - the button itself is still present. When using the blank button to enable plaintext editing, theres no button to go back. 

Enabling plaintext:
![html1](https://user-images.githubusercontent.com/32739961/72424291-078c4500-3786-11ea-94dd-b0166af2c130.JPG)

Cant go back:
![html2](https://user-images.githubusercontent.com/32739961/72424290-078c4500-3786-11ea-94b8-07bce3aa7637.JPG)

**Comment by alecpl** [comment] 2020-01-15 10:12
Duplicate of #7143.

**Closed by alecpl** 2020-01-15 10:12 UTC
