### ISSUE TITLE
Immediate clicks after marking an email will trigger opening in new window

### ISSUE THREAD

**Issue by julmot** [roundcube/roundcubemail#5179] opened 2016-03-30 14:54 UTC
**Steps to reproduce:**
1. Mark a few emails
2. Thereafter rapidly try to drag & drop them into a folder

A selected email will be opened in a new window.

**Expected:**

Nothing happens if an email is seleted.

**Comment by alecpl** [comment] 2016-03-30 15:03
Two clicks in less than 500ms are handled as a double-click. We could consider to disable double-click when more than one email is selected. This however would not solve the case when you selected one message and "rapidly" try to drag it. Disabling double-click on any selected message is not what some would expect, I suppose.

**Comment by julmot** [comment] 2016-03-30 18:32
I agree with you, that generally preventing double click from triggering a new window to open would annoy some users. However, it is possible to detect if there are any delta cursor coordinates between those double clicks. If so, this indicates that a user tries to drag & drop an email. If not, this indicates that someone want to open the email in a new window.  
What do you think about it?

**Comment by alecpl** [comment] 2016-04-01 07:05
I'm not sure it would work. For some people double-click may move the cursor. So, how do we distinguish from intentional and not intentional cursor move. Once I was thinking about optionally disabling the double-click action or disabling it at all when preview pane is used. Maybe that would be some solution, but requires more thinking and discussion.

**Comment by alecpl** [comment] 2016-11-01 17:19
I actually cannot reproduce the described behavior.

**Comment by alecpl** [comment] 2016-11-21 17:33
Considering my previous comment and the fact in 1.3 we disabled double-click when preview pane is enabled, I'm closing this one.

**Closed by alecpl** 2016-11-21 17:33 UTC
Labels: bug, C: User Interface, minor
