### ISSUE TITLE
Roundcube Roundcube Webmail 1.5.2 bug/issue - theme Elastic

### ISSUE THREAD

**Issue by UnExpectedlol** [roundcube/roundcubemail#8557] opened 2022-06-08 13:59 UTC
Hi,
we have Roundcube webmail client installed on our server (centos/cpanel), the issue one of our users have is when using Roundcube through any browser specifically on mobile devices and with Roundcube theme Elastic, when accessing menu there is an overlay on top which doesn't let us click on any item of the menu (attached picture).
Ty
![Screenshot 2022-06-08 155749](https://user-images.githubusercontent.com/78380949/172635268-499abd26-8bcd-4a37-b414-6de887c054f7.png)
![Screenshot 2022-06-08 155726](https://user-images.githubusercontent.com/78380949/172635300-d118f681-28c3-404b-8b34-87dc87e3065e.png)

**Comment by georgetasioulis** [comment] 2022-06-16 21:11
I can confirm I'm experiencing this too on cPanel servers running v104.0.4 which ships with Roundcube v1.5.2

**Comment by alecpl** [comment] 2022-06-18 12:14
Please, try with all plugins disabled.

**Comment by zaigham** [comment] 2022-06-18 12:22
> Please, try with all plugins disabled.

Which plugins you are referring to?

**Comment by alecpl** [comment] 2022-06-18 12:23
All Roundcube plugins you have enabled in the config file.

**Comment by zaigham** [comment] 2022-06-18 13:31
> All Roundcube plugins you have enabled in the config file.

These are the defaults with cPanel:

```
// List of active plugins (in plugins/ directory)
$config['plugins'] = ['cpanellogin','cpanellogout','archive','calendar', 'return_to_webmail','carddav','markasjunk'];
```

Should we also disable these?

**Comment by alecpl** [comment] 2022-06-19 07:05
Yes. I suspect especially the ones that don't come from Roundcube.

**Comment by czeslaf** [comment] 2022-06-21 11:48
The problem is exactly with the .popover class. The z-index value is 125 in calendar.css, and it should be 1300, as in styles.min.css. However, the one in calendar.css is rendered first

**Comment by eggplantstudios** [comment] 2022-06-23 22:49
Confirmed this bug also. The z-index is being set as 1299, which makes it overlay everything, and prevents clicking on buttons/items below it.

When I set the z-index to 124-ish in developer tools, it pushes the .popover-overlay element back where it should be.

**Comment by alecpl** [comment] 2022-06-24 08:50
What version of calendar plugin is this? Using kolab/calendar 3.5.7 (and kolab/libkolab 3.5.6) I don't see calendar.css being used with the Elastic skin.

**Comment by alecpl** [comment] 2022-06-25 12:02
Plugin issue. Closing

**Closed by alecpl** 2022-06-25 12:02 UTC
Labels: need feedback
