### ISSUE TITLE
PCRE2 10.33 with PHP 7.3 causes preg_replace errors

### ISSUE THREAD

**Issue by philippetrov** [roundcube/roundcubemail#6903] opened 2019-08-28 18:39 UTC
My OS is FreeBSD 11.3
The PHP version is 7.3.8 running as PHP-FPM. The HTTP server is Apache
Roundcube version is 1.3.9

Roundcube is working fine when it is with PCRE2 10.32. Since I recently updated it to 10.33 the Contacts section of Roundcube stopped working and started to throw these errors in the log:

`PHP Warning:  preg_replace(): Compilation failed: escape sequence is invalid in character class at offset 8 in /var/www/html/roundcubemail-1.3.9/program/lib/Roundcube/rcube_vcard.php on line 547`

**Comment by alecpl** [comment] 2019-08-28 19:15
Duplicate of #6744. We'll release 1.3.10 soon.

**Closed by alecpl** 2019-08-28 19:15 UTC
