### ISSUE TITLE
Trouble configuring through Outlook OAuth (version 1.5)

### ISSUE THREAD

**Issue by GerginIvanov** [roundcube/roundcubemail#7936] opened 2021-03-11 09:54 UTC
Hello, I am currently configuring Roundcube with Outlook. I have created an app in Azure AD, verified publisher, because I want any account (multitenant) to have access to Microsoft APIs. Added your redirect URI as it is said it 'default.config.php' file. Now when I start Roundcube I am redirected to Microsoft Login page, then I enter my credentials. After that, I am redirected to our Azure App consent screen, where they ask me for permissions and I accept them. But finally when I have to be redirected It shows me this error in the console: 

The resource from “https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=-------&scope=openid+profile+email+https%3A%2F%2Foutlook.office.com%2FIMAP.AccessAsUser.All+https%3A%2F%2Foutlook.office.com%2FSMTP.Send+User.Read+offline_access&redirect_uri=https%3A%2F%2Fsocialcloudwm.com%2Fwebmailoffice365%2Findex.php%2Flogin%2Foauth&state=i2Mpcib7w2hk&nonce=426807409” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). <---- in Mozilla

And this warning is shown in Chrome:

Cross-Origin Read Blocking (CORB) blocked cross-origin response <URL> with MIME type text/html. See <URL> for more details.

Followed by these errors: 

Uncaught ReferenceError: rcube_webmail is not defined
 at oauth?code=0.AAAAq9SB-D-...

Uncaught ReferenceError: $ is not defined
at oauth?code=0.AAAAq9SB-D-...

 

Here is my config:
```

$config['default_host'] = 'ssl://outlook.office365.com';
$config['default_port'] = 993;
$config['smtp_server'] = 'tls://smtp.office365.com';
$config['smtp_port'] = 587;
$config['oauth_provider'] = 'outlook';
$config['oauth_provider_name'] = 'Outlook.com';
$config['oauth_client_id'] = "------";
$config['oauth_client_secret'] = "-----";
$config['oauth_auth_uri'] = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize";
$config['oauth_token_uri'] = "https://login.microsoftonline.com/common/oauth2/v2.0/token";
$config['oauth_identity_uri'] = "https://graph.microsoft.com/v1.0/me";
$config['oauth_identity_fields'] = null;
$config['oauth_scope'] = "openid profile email https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/SMTP.Send User.Read offline_access";
$config['oauth_auth_parameters'] = ['nonce' => mt_rand()];
$config['oauth_login_redirect'] = true;
$config['oauth_verify_peer'] = true;
```

**Comment by alecpl** [comment] 2021-03-11 09:58
Duplicate of #7923.

**Closed by alecpl** 2021-03-11 09:58 UTC
