### ISSUE TITLE
Make 'display name' apply to received mail

### ISSUE THREAD

**Issue by RhinosF1** [roundcube/roundcubemail#7062] opened 2019-11-21 22:04 UTC
If a user has set a display name for a contact, Roundcube should use that in exchange of the sender's email or name supplied when showing the sender on mail received from them.

VERSION: Roundcube Webmail 1.4-git [GIT 20190228.1414]

**Comment by alecpl** [comment] 2019-11-22 06:22
Duplicate of  #5048.

**Closed by alecpl** 2019-11-22 06:22 UTC
