### ISSUE TITLE
PHP Error: Invalid compose ID in - still exists in 1.3.8

### ISSUE THREAD

**Issue by iron-udjin** [roundcube/roundcubemail#6520] opened 2018-11-14 02:10 UTC
Hello,

The issue which is described in #6470 and has to be fixed in 1.3.8 still exists. It can be simple reproduced: open two tabs with roundcube. In the first one compose message and right after click on "Send" button switch to second tab and click "Compose". When you finish typing message in the second tab click "Send" you'll receive message "An internal error occurred. Please try again." and in the error log you'll find "PHP Error: Invalid compose ID in ..."

It doesn't metter what's set in $config['session_storage']. I tried 'php', 'db', 'redis', 'memcache' with the same result.

P.S: System environment and settings are the same as in https://github.com/roundcube/roundcubemail/issues/6470#issuecomment-425361409

**Comment by alecpl** [comment] 2018-11-18 07:47
I'm just not able to reproduce.

**Comment by mr-smit** [comment] 2018-12-20 17:44
yes the bug still exists, even with storage: php, its random and sometimes appear..

**Comment by mr-smit** [comment] 2019-01-14 21:30
i found that it was because session cache mechanism implemented by roundcube. Just disable session cache in code and all will be ok.

**Comment by mr-smit** [comment] 2019-02-06 17:34
ok the reason why it's happening, because you sending email while drafts are saving your email. So you have to wait until full save is done. Then send email. Or just disable drafts, or rewrite the code where drafts session will be stored in different variable name so it will not conflict with send mail. I am talking about this id:
?_task=mail&_action=compose&_id=19194202475c5b1a97c089

**Comment by mr-smit** [comment] 2019-02-12 21:49
finally i figured out, the problem is in $_SESSION (write) to db, when you press: Send email button, if some request is added between "requests" (uploading files.., sending email..) then you are screwd. This is because $_SESSION in db is not locked like if it was in default $_SESSION storage.

1. You are sending email with attachments
2. Some script is ajax requesting for example "new email received"
3. that script is updating some $_SESSION vars for example: $_SESSION['last_new_email_time'] = time();
4. but before that it gets all $_SESSION params from database
5. Your sending script is adding attachment to $_SESSION
6. Your updating script is adding last_new_email_time to $_SESSION and rewriting to database

so here you got, no locks big problems. The easy way to fix this without locks, just block all javascript request in background after you press "Send" button in compose.

**Comment by booshlinux** [comment] 2019-02-25 23:42
I still see this error from time to time as well. 1.3.8, PHP 7.0.
`PHP Error: Invalid compose ID in xxxxxx/program/steps/mail/sendmail.inc on line 37 (POST /?_task=mail&_unlock=loading1551102700942&_lang=en&_framed=1&_action=send)`

**Comment by zoobag** [comment] 2019-10-01 10:37
> ok the reason why it's happening, because you sending email while drafts are saving your email.

no, not only. You can turn off saving drafts but it will not work.

**Comment by alecpl** [comment] 2021-05-29 07:07
Duplicate of #5869.

**Closed by alecpl** 2021-05-29 07:07 UTC
Labels: need feedback
