### ISSUE TITLE
Plugin password - it is possible? If not this is feature request.

### ISSUE THREAD

**Issue by takenek** [roundcube/roundcubemail#8822] opened 2022-12-19 19:30 UTC
Hello,
I just get information my cowokers find a way to never change a password - they change password to new and click again and change back password to old one - there is any option in Plugin module "password" to disable this funtion? Something like "remember" in pam module - he remember last X password what user set? 
And another qustion this is possible to force user to change more than 1 char?
User set password: test1234 month later he set: test1235 and all the time change just one digit.

Thanks
TaKeN

**Comment by alecpl** [comment] 2022-12-20 06:36
Duplicate of #5118

**Closed by alecpl** 2022-12-20 06:36 UTC
