### ISSUE TITLE
 Microsoft OAuth Login Error

### ISSUE THREAD

**Issue by eduardosantanna** [roundcube/roundcubemail#9733] opened 2024-12-19 18:58 UTC
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

I'm trying to implement roundcube together with Office 365 OAuth, I configured config.inc.php as requested, but when I try to log in, I receive the error below. 

```
PHP Error: OAuth token request failed: Client error: `GET https://graph.microsoft.com/v1.0` resulted in a `401 Unauthorized` response:
{"error":{"code":"InvalidAuthenticationToken","message":"Access token validation failure. Invalid audience.","innerError (truncated...)
```

I'm using the LTS version, but the error also occurs in the stable version.

Example of what my configuration file looks like:

```
    $config['oauth_provider'] = 'outlook';
    $config['oauth_provider_name'] = 'Outlook.com';
    $config['oauth_client_id'] = "<HIDE>";
    $config['oauth_client_secret'] = "<HIDE>";
    $config['oauth_auth_uri'] = "https://login.microsoftonline.com/<HIDE TENANT ID>/oauth2/v2.0/authorize";
    $config['oauth_token_uri'] = "https://login.microsoftonline.com/<HIDE TENANT ID>/oauth2/v2.0/token";
    $config['oauth_identity_uri'] = "https://graph.microsoft.com/v1.0/me";
    $config['oauth_identity_fields'] = ['email', 'userPrincipalName'];
    $config['oauth_scope'] = "https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send User.Read offline_access";
    $config['oauth_auth_parameters'] = ['nonce' => mt_rand()];
```

### What browser(s) are you seeing the problem on?

Chrome, Edge

### What version of PHP are you using?

PHP 7.4.33

### What version of Roundcube are you using?

v1.5.9

**Comment by alecpl** [comment] 2024-12-21 15:34
Probably a duplicate of #9598.

**Closed by alecpl** 2024-12-21 15:34 UTC
