### ISSUE TITLE
SAVE option in preferences is off the screen

### ISSUE THREAD

**Issue by Abatjour3407** [roundcube/roundcubemail#6834] opened 2019-07-04 08:13 UTC
**Hi, I'm testing out the RC1 version and it's beautiful! Wow! You guys are doing a great job!**

**A minor bug though, under preferences>user interface I the see the save button is off the screen in some window sizes (even when there's a scroller and I scroll down to the bottom). I see the only tabs where it isn't off the screen on my laptop are mailbox view, contacts, special folders, and server settings (which is half off the screen). Zooming out to 90% (until I wouldn't need the scroll bar to see the save button) rectified the problem.**

_I am using the latest version and installed it with the elastic theme. The plugins installed are the following: 'acl', 'additional_message_headers', 'archive', 'attachment_reminder', 'emoticons', 'filesystem_attachments', 'hide_blockquote', 'identicon', 'identity_select', 'jqueryui', 'managesieve', 'markasjunk', 'newmail_notifier', 'password', 'show_additional_headers', 'subscriptions_option', 'userinfo', 'vcard_attachments', 'virtuser_file', 'virtuser_query', and 'zipdownload'. If you are struggling to recreate this problem and need more information let me know at ryan@legacy.live_

**Comment by alecpl** [comment] 2019-07-04 08:21
Duplicate of #6678.

**Closed by alecpl** 2019-07-04 08:21 UTC
