### ISSUE TITLE
kubernetes: install custom plugins via composer on startup

### ISSUE THREAD

**Issue by volker-raschek** [roundcube/roundcubemail#8185] opened 2021-08-29 10:27 UTC
Hi, 
I am writing currently a [helm chart](https://github.com/volker-raschek/roundcube-charts) for roundcube and I am looking for a missing feature to install custom plugins automatically.

I want to define the plugins which should be installed for a specific version via environment variable like the following pattern: `ROUNDCUBEMAIL_PLUGINS_CUSTOM="pf4public/fetchmail~1.0.11,roundcube/carddav>=4.1.2"`. 

When the environment variable is defined should be the plugins installed via composer. The compose must be pre-installed inside the container image. Is there already a feature like that, if yes, then I would be extremely happy for a link to the documentation, if not, consider this a feature request.

Volker

**Comment by alecpl** [comment] 2021-08-29 14:17
This is out of scope for the project.

**Closed by alecpl** 2021-08-29 14:17 UTC

**Comment by thomascube** [comment] 2021-08-29 15:19
This is basically a duplicate of this issue: https://github.com/roundcube/roundcubemail-docker/issues/97
Please follow-up there.

**Comment by thomascube** [comment] 2021-08-29 15:24
FWIW: additional plugin installation is explained here: https://github.com/roundcube/roundcubemail-docker/blob/master/examples/README.md#installing-roundcube-plugins
But I admit this is tricky to pack into a Kubernetes deployment or Helm chart.
