### ISSUE TITLE
Signature spoofing in PGP signed email (GUI layer)

### ISSUE THREAD

**Issue by jensvoid** [roundcube/roundcubemail#6462] opened 2018-09-25 14:04 UTC
Dear Roundcube devs,

In the scope of academic research we discovered a (minor) PGP signature validation issue in Roundcube based on how Roundcube presents the results of signature verification to the user.

*** Prerequirements ***

It is assumed that the attacker, Eve, can send an email to Bob which -- on the RFC822 layer -- looks like originating from Alice (using the *From:* header). Such email address spoofing should actually be prevented by digital signatures. The attacker's goal is to have a spoofed PGP signature being displayed by the mail client, so that Bob thinks there is cryptographic proof for Alice being the sender. The attack is successful if the fake signature is indistinguishable from a real signed message by Alice on the first level of the UI -- i.e. by just viewing the email without further investigating the signature details or performing a forensic analysis.

*** Attack Description ***

Roundcube displays the status of the signature within the mail content itself. However, this part of the UI is in control of the attacker. With modern HTML, CSS or inline images a graphic showing `valid signature', appearing like the real results of signature verification, can easily be forged. Note that this attack works for signed-only as well as for signed and encrypted messages because the HTML email content do display the fake signature can simply be encrypted using Bob's public key.

*** Countermeasures ***

The results of signature verification are not to be shown in attacker-controlled parts of the UI such as in the message content itself which may contain arbitrary graphics.

Feel free to contact me for any questions.

Greetings,
Jens Mueller

--
M.Sc. Jens Mueller
Research Assistant
Chair for Network and Data Security, Ruhr-University
Universitaetsstr. 150
Building ID 2/415
D-44780 Bochum
Phone: +49 (0) 234 / 32-29177

**Comment by alecpl** [comment] 2018-09-25 15:40
Duplicate of #6450.

**Closed by alecpl** 2018-09-25 15:40 UTC
