### ISSUE TITLE
Oauth (xoauth) token length

### ISSUE THREAD

**Issue by bolsunovskyi** [roundcube/roundcubemail#8190] opened 2021-08-30 08:11 UTC
Greeting, recently I tested new oauth feature in roundcube 1.5-rc and find a bug with token length. When oauth token is validated it processed like an IMAP password and rcmail checking it length for max length of 1024 characters.
https://github.com/roundcube/roundcubemail/blob/release-1.5/program/include/rcmail.php#L880 
In my case I'm using keycloak to test oauth and it generates JWT tokens with length 1481 chars, so I commented this validation to get a successful result.
So I think we need to add some condition in password validator to remove password length check on oath authentication.

**Comment by alecpl** [comment] 2021-08-30 08:19
Duplicate of #8178.

**Closed by alecpl** 2021-08-30 08:19 UTC
