### ISSUE TITLE
Login Failed for one user but others work fine

### ISSUE THREAD

**Issue by ajbeaven** [roundcube/roundcubemail#5988] opened 2017-10-10 22:57 UTC
I'm receiving the message "Login failed" when one user tries to log in. The username and password they are using is correct (I changed it to be extra sure) and other users can log in successfully. This user can successfully retrieve emails (via IMAP) and send emails in outlook using the same username/password details. The mail account itself is about 11GB in size.

I have recently migrated hMailServer and Roundcube to a new server, but I do not know if this is related. The databases that sit behind hMailServer and Roundcube are on a different server which has not changed as part of this migration.

Here are some logs that are added when the user tries to log in.

IMAP log:
```
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [F812] S: * OK IMAPrev1
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [F812] C: A0001 CAPABILITY
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [F812] S: * CAPABILITY IMAP4 IMAP4rev1 CHILDREN IDLE QUOTA SORT ACL STARTTLS NAMESPACE RIGHTS=texk
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [F812] S: A0001 OK CAPABILITY completed
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [F812] C: A0002 STARTTLS
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [F812] S: A0002 OK Begin TLS negotiation now
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [F812] C: A0003 CAPABILITY
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [F812] S: * CAPABILITY IMAP4 IMAP4rev1 CHILDREN IDLE QUOTA SORT ACL STARTTLS NAMESPACE RIGHTS=texk
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [F812] S: A0003 OK CAPABILITY completed
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [F812] C: A0004 LOGIN ****** [40]
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [F812] S: A0004 OK LOGIN completed
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [F812] C: A0005 NAMESPACE
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [F812] S: * NAMESPACE (("" ".")) NIL (("#Public" "."))
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [F812] S: A0005 OK namespace command complete
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [F812] C: A0006 LOGOUT
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [F812] S: * BYE Have a nice day
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [F812] S: A0006 OK Logout completed
```

SQL log:
```
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [1] SELECT `vars`, `ip`, `changed`, now() AS ts FROM `session` WHERE `sess_id` = 'n49t8sl1dpokeh1mhc69u6brsc';
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [2] DELETE FROM `session` WHERE `sess_id` = 'n49t8sl1dpokeh1mhc69u6brsc';
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [3] SELECT * FROM `users` WHERE `mail_host` = 'mail.mydomain.com' AND `username` = 'bob@anotherdomain.com';
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [4] INSERT INTO `users` (`created`, `last_login`, `username`, `mail_host`, `language`) VALUES (now(), now(), 'bob@anotherdomain.com', 'mail.mydomain.com', 'en_US');
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [5] DELETE FROM `session` WHERE `sess_id` = 'n49t8sl1dpokeh1mhc69u6brsc';
[10-Oct-2017 18:50:32 -0400]: <n49t8sl1> [6] INSERT INTO `session` (`sess_id`, `vars`, `ip`, `changed`) VALUES ('n49t8sl1dpokeh1mhc69u6brsc', 'bGFuZ3VhZ2V8czo1OiJlbl9VUyI7dGVtcHxiOjE7c2tpbnxzOjU6ImxhcnJ5IjtyZXF1ZXN0X3Rva2VufHM6MzI6IjlOSVphMHlvREtUeGhtNFRMbVU0ZzJKNTZEYnZRWEVMIjs=', '123.45.67.89', now());
```

Any guesses? Should I delete the user/identities record for this user in the roundcube database and try again or will that screw more stuff up?

**Comment by alecpl** [comment] 2017-10-11 05:48
Did you try to log in from a different computer/browser?

**Comment by ajbeaven** [comment] 2017-10-11 21:28
Yep, same thing occurs in Chrome (incognito) and Firefox.

**Comment by alecpl** [comment] 2017-10-12 06:08
You could set preferences column in users table to NULL, but copy the content for further investigation if that was indeed the culprit.

**Comment by ajbeaven** [comment] 2017-10-12 21:29
I set the preferences column to NULL which had no effect. I then deleted both the user and identity rows for this user, but this still had no effect.

Here are some more logs from the mailserver when the login fails in roundcube:
```
"TCPIP"	5452	"2017-10-12 17:08:34.723"	"TCP - 12.34.5.67 connected to 12.34.5.67:143."
"DEBUG"	5452	"2017-10-12 17:08:34.724"	"TCP connection started for session 14250"
"IMAPD"	5452	14250	"2017-10-12 17:08:34.724"	"12.34.5.67"	"SENT: * OK IMAPrev1"
"IMAPD"	5456	14250	"2017-10-12 17:08:34.734"	"12.34.5.67"	"RECEIVED: A0001 CAPABILITY"
"IMAPD"	5456	14250	"2017-10-12 17:08:34.735"	"12.34.5.67"	"SENT: * CAPABILITY IMAP4 IMAP4rev1 CHILDREN IDLE QUOTA SORT ACL STARTTLS NAMESPACE RIGHTS=texk[nl]A0001 OK CAPABILITY completed"
"IMAPD"	5444	14250	"2017-10-12 17:08:34.738"	"12.34.5.67"	"RECEIVED: A0002 STARTTLS"
"IMAPD"	5444	14250	"2017-10-12 17:08:34.738"	"12.34.5.67"	"SENT: A0002 OK Begin TLS negotiation now"
"DEBUG"	5452	"2017-10-12 17:08:34.739"	"Performing SSL/TLS handshake for session 14250. Verify certificate: False"
"TCPIP"	5452	"2017-10-12 17:08:34.760"	"TCPConnection - TLS/SSL handshake completed. Session Id: 14250, Remote IP: 12.34.5.67, Version: TLSv1.2, Cipher: ECDHE-RSA-AES128-GCM-SHA256, Bits: 128"
"IMAPD"	5452	14250	"2017-10-12 17:08:34.761"	"12.34.5.67"	"RECEIVED: A0003 CAPABILITY"
"IMAPD"	5452	14250	"2017-10-12 17:08:34.761"	"12.34.5.67"	"SENT: * CAPABILITY IMAP4 IMAP4rev1 CHILDREN IDLE QUOTA SORT ACL STARTTLS NAMESPACE RIGHTS=texk[nl]A0003 OK CAPABILITY completed"
"IMAPD"	5456	14250	"2017-10-12 17:08:34.764"	"12.34.5.67"	"RECEIVED: A0004 LOGIN bob@anotherdomain.com ***"
"IMAPD"	5456	14250	"2017-10-12 17:08:34.766"	"12.34.5.67"	"SENT: A0004 OK LOGIN completed"
"IMAPD"	5444	14250	"2017-10-12 17:08:34.768"	"12.34.5.67"	"RECEIVED: A0005 NAMESPACE"
"IMAPD"	5444	14250	"2017-10-12 17:08:34.768"	"12.34.5.67"	"SENT: * NAMESPACE (("" ".")) NIL (("#Public" "."))[nl]A0005 OK namespace command complete"
"IMAPD"	5456	14250	"2017-10-12 17:08:34.784"	"12.34.5.67"	"RECEIVED: A0006 LOGOUT"
"IMAPD"	5456	14250	"2017-10-12 17:08:34.784"	"12.34.5.67"	"SENT: * BYE Have a nice day[nl]A0006 OK Logout completed"
"DEBUG"	5452	"2017-10-12 17:08:34.785"	"Ending session 14250"
```

**Comment by alecpl** [comment] 2017-10-13 09:01
Looks like the imap connection is fine and the problem is with php session or sth. Did you try to access the user account from another computer? What plugins are you using? Try with disabled all plugins. What PHP version? What Roundcube version?

**Comment by ajbeaven** [comment] 2017-10-13 10:13
Just tried on my phone connected to a different network - same problem unfortunately.

It's a standard install with no additional plugins added. The ones that are installed are:

- archive
- zipdownload
- filesystem_attachments
- jqueryui

I disabled the first two that were listed in the plugins array. The last two I wasn't sure how to disable them or whether it was wise to strip them out, so I've left them in.

I also deleted all the session rows in the roundcube database just in case. Didn't seem to have any effect.

Roundcube: 1.3.1
PHP version: 7.1.7 (x64)

**Comment by alecpl** [comment] 2017-11-04 09:58
Any news? From the log you provided I think it might be SQL problem. How your database setup looks like? Are you using replication? Are you sure there were no errors in log?

**Comment by ajbeaven** [comment] 2017-11-04 18:13
MailServer is on machine A whereas the SQL Server database sits on machine B. No I'm not using replication. Other than the logs I've already provided, there is nothing I can find sorry.

**Comment by alecpl** [comment] 2018-01-03 08:16
This is strange and I'll not help much probably, but... There's sql log in the initial comment that would indicate that it creates user record, but I don't see a query to create identity record. That would mean that the first INSERT failed. However, in that case I'd expect an entry in error log. If you know some PHP you could try to do some debug in `rcube_user::create()`.

I'm closing this for now.

**Closed by alecpl** 2018-01-03 08:16 UTC
Labels: need feedback
