### ISSUE TITLE
[bug] No information about message folder location

### ISSUE THREAD

**Issue by 80kk** [roundcube/roundcubemail#8961] opened 2023-03-29 20:48 UTC
There is no information about message folder location other than web browser address bar. For instance message located in `Amazon` folder will have `%2FAmazon` appended:
```
https://domain/rc/?_task=mail&_mbox=INBOX%2FAmazon
```
The problem is that this trick doesn't work for messages returned from search query.

**Comment by alecpl** [comment] 2023-04-01 13:46
Duplicate of #7950.

**Closed by alecpl** 2023-04-01 13:46 UTC
