### ISSUE TITLE
Problem with quoted-printable Content-Transfer-Encoding in message/rfc822 attachment

### ISSUE THREAD

**Issue by mary-pe** [roundcube/roundcubemail#8426] opened 2022-01-28 12:26 UTC
Hi, 
in RC 1.5.0 I've problem in decoding messages with "Content-Transfer-Encoding:quoted-printable".

The problem does not occur when "Content-Transfer-Encoding: quoted-printable" is set for the body of the message, but when it is set for a message/rfc822 attachment.
I attached two samples.
[quoted-printable_ok.eml.txt](https://github.com/roundcube/roundcubemail/files/7958576/quoted-printable_ok.eml.txt)
[quoted-printable_notok.eml.txt](https://github.com/roundcube/roundcubemail/files/7958577/quoted-printable_notok.eml.txt)

**Comment by alecpl** [comment] 2022-01-30 08:27
Duplicate of #8408. Works for me in git-master.

**Closed by alecpl** 2022-01-30 08:27 UTC
