### ISSUE TITLE
elastic skin: make more friendly to colorblind people

### ISSUE THREAD

**Issue by syzop** [roundcube/roundcubemail#7225] opened 2020-02-14 20:00 UTC
The listing tbody td border-bottom is color ```#f1f3f4``` by default, which is very close to white.
To me personally this is not a problem, but the day after we introduced the elastic skin in our organization I already got 2 complaints from staff that they could not see the line. Now, both people have some "eye issues". One of them is colorblind and the other one suffers from another issue.
Still, when I see how similar ```#f1f3f4``` is to ```#ffffff```, I can imagine them not seeing it.
What is the problem exactly? Well, because they don't see the horizontal lines separating every message in the list, they have trouble figuring out which sender&date belongs to which subject (not just once but every time). This gives them a hard time navigating the message list.
I have manually adjusted the color to ```#d0d0d0``` and it was much better for them. However, I don't like the result of that myself. I think it shows the lines too prominently.
=> Perhaps a middle ground can be found? I am not a web designer. Perhaps do some testing with colorblind people? There are quite some of them in this world which means A) it is quite important, and B) it shouldn't be that hard to find testers.

They also complained about the currently selected message color which is ```#ebf9ff```. Again there too they could hardly see which message was selected, causing confusion. I changed that one to ```#d0f0f0``` which solved it for them. That is a color change I can live with myself.

**Comment by manfredu** [comment] 2020-02-14 20:52
I had the same issue at one of my computers and it was a monitor configuration, which reduced the amount of black (HDMI black level = low). Setting this to normal made the lines and light blue background of selected messages appear again.

**Comment by alecpl** [comment] 2020-02-19 08:31
Duplicate of #7126.

**Closed by alecpl** 2020-02-19 08:31 UTC
