### ISSUE TITLE
PHP Error: Unable to set image alpha channel in program/lib/Roundcube/rcube_image.php on line 171

### ISSUE THREAD

**Issue by localguru** [roundcube/roundcubemail#5412] opened 2016-08-24 09:44 UTC
Hi,

when opening a HTML formatted email with png image attached I get the following error:

imts6bmh> PHP Error: Unable to set image alpha channel in [...]/program/lib/Roundcube/rcube_image.php on line 171 (GET /mail/?_task=mail&_action=get&_mbox=INBOX&_uid=xxx&_token=xxx&_part=2&_embed=1&_mimeclass=image&_thumb=1)

The png image itself is presented fine and shown as little preview inside the email. Andy ideas?

roudcube version 1.2.1 from source
ii  imagemagick                         8:6.7.7.10-6ubuntu3.1 
ii  php5-imagick                        3.1.2-1build1  

Ciao!

**Comment by alecpl** [comment] 2016-08-24 10:01
Duplicate of #5376.

**Closed by alecpl** 2016-08-24 10:01 UTC
