### ISSUE TITLE
Multiple recipient warning bug

### ISSUE THREAD

**Issue by dardailler** [roundcube/roundcubemail#6090] opened 2017-12-12 15:48 UTC
Hello, I checked and didn't find this one.
When sending a message to several recipients, there's a popup warning about you really wanting to do that (large audience risk analysis, why not, I wish there was an option out of that), but one of the option labelled "Send Message" just doesn't do that, it just removes the popup and you need to hit Send again.
So: please provide an option to remove this warning popup
      please Send the message, or change the button to say "OK, Understood", but not "Send Message".

Thanks.

**Comment by alecpl** [comment] 2017-12-12 18:48
Duplicate of #5924. Update!

**Closed by alecpl** 2017-12-12 18:48 UTC
