### ISSUE TITLE
Compose window address book issue when Google Analytics cookies present

### ISSUE THREAD

**Issue by travisburnside** [roundcube/roundcubemail#5843] opened 2017-07-07 22:36 UTC
We ran into a strange issue with our install of Roundcube, duplicatable up to our current install of 1.2.5.

In the compose window, we have LDAP directory sources configured to show in the "contacts" left pane.  Ordinarily, users are accustomed to clicking on the various sources to show the contents of that directory source.  However, when Google Analytics cookies are present, this function breaks - the JSON returned contains an empty address list.  The log shows errors similar to the following:

[13-Jun-2017 14:36:15 -0700]: <cvo7s6vv> PHP Error: LDAP: ldap_list failed for dn=. No such object (GET /webmail/?_task=mail&_action=list-contacts&_source=SouthLane&_page=1&_remote=1&_unlock=loading1497389775863&_=1497389774060)

I tested inserting a bit of code into index.php to unset() the $_COOKIE superglobal for the three GA cookies, and this functioned as a workaround.

Any idea why the presence of these cookies would somehow break LDAP lookups?  I should note that they keystroke-based search box continues to function correctly, regardless.

Thanks.

**Comment by alecpl** [comment] 2017-07-08 06:23
Upgrade to 1.3. Duplicate of #5748.

**Closed by alecpl** 2017-07-08 06:23 UTC
