### ISSUE TITLE
stop removing style tags in wash_html

### ISSUE THREAD

**Issue by petersphilo** [roundcube/roundcubemail#9417] opened 2024-04-17 10:07 UTC
Hello,

First, thank you so much for your work on RoundCube!

Would it be possible to stop removing 'style' tags in wash_html?

That would allow us to use custom css classes in signatures (or even in the body)..

i understand the possibility of namespace conflicts, but that seems like a risk worth taking..
or perhaps adding a config option in the main config file that switches between excluding styles tag and not excluding it?

Thank You So Much!

**Comment by alecpl** [comment] 2024-04-17 10:21
I suppose it's a duplicate of #9338.

**Closed by alecpl** 2024-04-17 10:21 UTC

**Comment by petersphilo** [comment] 2024-04-17 10:24
Sorry about that!
i couldn't find the other one for some reason..
Thank You!
