### ISSUE TITLE
Engima plugin won't accept key passphrase for sending a new email signed or encrypted-CONTINUED

### ISSUE THREAD

**Issue by fsantiago07044** [roundcube/roundcubemail#5215] opened 2016-04-19 23:43 UTC
I've updated to crypt_gpg v1.4.1 and still same issue. now what?

**Comment by alecpl** [comment] 2016-04-20 06:03
If you updated also Roundcube to git-master you could enable enigma_debug option to get some debug info from gnupg.

**Comment by fsantiago07044** [comment] 2016-04-20 17:22
thanks.

i've merged the rc git-master branch.

strange issue now; when i try creating a new key in RC, i receive error:

Unable to import key(s)! Internal error.

in the webui.

my rc error log states:

tu9bljrs> PHP Error: Enigma plugin: Unknown error importing GPG key. Please use the 'debug' option when creating the Crypt_GPG object, and file a bug report at http://pear.php.net/bugs/report.php?package=Crypt_GPG in /var/www/roundcubemail-1.1.1/plugins/enigma/lib/enigma_engine.php on line 1069 (POST /mail/?_task=settings&_framed=1&_action=plugin.enigmakeys)

i do have in my enigma config as well:  $config['enigma_debug'] = true;

what can i try next? Thanks for your help.

**Comment by alecpl** [comment] 2016-04-20 18:00
You should have logs/enigma file then.

**Comment by fsantiago07044** [comment] 2016-04-20 18:02
i do not. sendmail and errors is all.

**Comment by alecpl** [comment] 2016-04-20 18:09
Strange. Are you really on git-master? Your directory path shows 1.1.1 version.

**Comment by fsantiago07044** [comment] 2016-04-20 18:11
that's just my folder name from my original install, i've since updated without bothering to rename it. 

i've set my git branch to origin/master:

git branch --set-upstream-to=origin/master

and running git pull produces:

Already up-to-date.

**Comment by fsantiago07044** [comment] 2016-04-21 14:10
i got it to finally create a new key but still won't accept my passphrase....same as before.

**Comment by alecpl** [comment] 2016-04-21 14:24
You need to use composer to update Crypt_GPG, did you do this? Did you try with some simple password e.g. "12345" (make sure there are only digits/letters).

**Comment by fsantiago07044** [comment] 2016-04-21 14:26
i did use composer for the crypt_gpg library and have v1.4.1 installed now and i have also tried simple password key creation with only lower case alpha / numerics. i have also tried other more complex or longer passwords but again, no special characters at the very least.

**Comment by alecpl** [comment] 2016-04-26 06:36
Please, verify that your /vendor/bin/crypt-gpg-pinentry looks like this https://github.com/pear/Crypt_GPG/blob/master/scripts/crypt-gpg-pinentry. Use gpg in command line to verify that the key/passphrase works there. Provide enigma_debug log.

**Comment by Driim** [comment] 2016-04-26 09:48
I got same issue. Enigma doesn't accept my password. I also update to git master and enable enigma_debug, I see debug message in browser, but i want to see them in log file.

**Comment by alecpl** [comment] 2016-04-26 09:59
if you have debug in browser, that would mean you didn't update Crypt_GPG to version 1.4.1.

**Comment by Driim** [comment] 2016-04-26 15:05
Upgrade to Crypt_GPG, now I have enigma log file. 

And now I see error:

GPG: ERROR: gpg: problem with the agent: No pinentry

**Comment by Driim** [comment] 2016-04-28 13:12
In my case, the problem was that there was no variable php in the env.

**Comment by alecpl** [comment] 2016-05-01 09:09
@fsantiago07044, how about you? Maybe that's the same issue?

**Comment by fsantiago07044** [comment] 2016-05-12 12:50
still doesn't work but i tried pinentry from the command line and received this:

PHP Fatal error:  XML definition file "/var/www/roundcubemail-1.1.1/vendor/pear-pear.php.net/Console_CommandLine/Console/CommandLine/../../data/xmlschema.rng" does not exists or is not readable in /var/www/roundcubemail-1.1.1/vendor/pear-pear.php.net/Console_CommandLine/Console/CommandLine.php on line 855

**Comment by fsantiago07044** [comment] 2016-05-12 13:00
but the file exists under here:

/var/www/roundcubemail-1.1.1/vendor/pear-pear.php.net/Console_CommandLine/data/Console_CommandLine/data/xmlschema.rng

**Comment by alecpl** [comment] 2016-05-12 13:00
Looks like another issue with installing pear package with composer. I see how that could be a problem when you used /vendor dir from Roundcube official package, but if you installed deps using composer it should work. The problem is with a path in validate() method in /vendor/pear-pear.php.net/Console_CommandLine/Console/CommandLine/XmlParser.php.

**Comment by fsantiago07044** [comment] 2016-05-12 13:02
can i fix with a symlink or do i need to run / re-run composer after doing something with packages?

**Comment by fsantiago07044** [comment] 2016-05-12 14:14
i did initially use the official package but have since been updating from git and then follow up with composer

**Comment by Driim** [comment] 2016-05-13 08:54
> PHP Fatal error: XML definition file "/var/www/roundcubemail-1.1.1/vendor/pear-pear.php.net/Console_CommandLine/Console/CommandLine/../../data/xmlschema.rng" does not exists or is not readable

I also had this issue, I corrected it by symlink and forgot to tell.

**Comment by fsantiago07044** [comment] 2016-05-13 18:37
Driim, where do i symlink the file to? the error msg's path isn't clear as far as where it's looking for it......

**Comment by fsantiago07044** [comment] 2016-05-13 18:52
when it says /../../data/xmlschema.rng, where is this pointing to?

**Comment by alecpl** [comment] 2016-05-16 06:46
vendor/pear-pear.php.net/Console_CommandLine/data/xmlschema.rng should point to
vendor/pear-pear.php.net/Console_CommandLine/data/Console_CommandLine/data/xmlschema.rng

**Comment by alecpl** [comment] 2016-05-22 06:11
https://github.com/pear/Console_CommandLine/pull/9

**Comment by fsantiago07044** [comment] 2016-05-25 23:27
all fixed now that i've up'd to rc 1.2.0 official release and updated my composer dependencies. case closed. works fine now.

**Comment by alecpl** [comment] 2016-05-26 07:12
It works in our official release because we patched Console_CommandLine. It also works if you use composer on your destination system. However, my PR has not been aplied yet, so I'll leave the ticket open until we have a new Console_CommandLine package that we can depend on.

**Comment by cweiske** [comment] 2016-07-14 06:06
@alecpl - fixed in Console_CommandLine 1.2.2

**Closed** 2016-07-14 18:05 UTC
Labels: bug, C: Plugins
