### ISSUE TITLE
 Open more than one web sessions

### ISSUE THREAD

**Issue by 97zgxgw** [roundcube/roundcubemail#6211] opened 2018-03-09 08:01 UTC
Hello 
In my server 5 domains, how i can open in one time 5 session to different mail domains?

**Comment by alecpl** [comment] 2018-03-09 08:39
You mean you want to access 5 separate accounts at the same time? It's not possible. Duplicate of #5075.

**Closed by alecpl** 2018-03-09 08:39 UTC

**Comment by 97zgxgw** [comment] 2018-03-09 10:03
Thank.
