### ISSUE TITLE
OAuth/XOauth support

### ISSUE THREAD

**Issue by rayflexcom** [roundcube/roundcubemail#6933] opened 2019-09-23 11:41 UTC
Hi All, I just got this Message from Office 365:

> `Beginning October 13, 2020, [we will retire Basic Authentication for EWS, EAS, IMAP, POP and RPS to access Exchange Online. Note: this change does not impact SMTP AUTH.](https://techcommunity.microsoft.com/t5/Exchange-Team-Blog/Upcoming-changes-to-Exchange-Web-Services-EWS-API-for-Office-365/ba-p/608055)

There are several actions that you and/or your users can take to avoid service disruptions on client applications, and we describe them below. If no action is taken, client applications using Basic Authentication for EWS will be retired on October 13, 2020.`

Is it possible to support Office 365 Oauth 2.0 By Default?

**Comment by alecpl** [comment] 2019-09-23 12:13
No it's not possible. Also, What has IMAP to do with EWS and basic auth, I don't know.

**Comment by rayflexcom** [comment] 2019-09-23 20:41
@alecpl We are connecting Roundcube with IMAP to Office 365 using a username/password combo. From 13 october 2020 that wont be possible anymore. Then only Oauth 2.0 will be possible.

**Comment by thomascube** [comment] 2019-09-30 19:55
I think this is a valid request for supporting the OAUTH2 (or XOAUTH2) auth tokens on IMAP (and SMTP) servers. Gmail supports this using the [XOAUTH2 mechanism](https://developers.google.com/gmail/imap/xoauth2-protocol).

Since logging in with OAuth changes the login process (redirect to authentication service, returning with authorization code), I think with would require a specific config (i.e. `imap_auth_type` = `oauth2`) plus additional options defining the authentication url and the secret. If those are set, the login screen shows a button to redirect the user the authentication service.

**Comment by thomascube** [comment] 2019-10-24 20:14
Submitted [PR55](https://github.com/pear/Net_SMTP/pull/55) for Net_SMTP in order to have XOAUTH2 support right there. IMAP and SMTP auth successfully tested with Gmail. Does anybody have more information regarding Office 365? Or even a test account?

**Comment by alecpl** [comment] 2019-10-25 06:22
You can create free accounts on outlook.com (I'm not sure it is the same as Office365). You said you tested it with Gmail, I didn't see a commit to rcube_imap_generic. Actually I expect some more code. Where is it? I'm wondering if it would make sense to integrate that with kolab_sso plugin, or you plan to do this in core?

**Comment by jtuta** [comment] 2019-10-30 08:12
Hello @thomascube  and @alecpl ,

Long time user of roundcoube here and I think I can provide some insight on OATUH and give something back to the opensource community that was so gracious in the past decade.
It was probably 2 years ago when I had a job of integrating roundcube into some specific web application which uses OAUTH/XOATH for authentication to the backend. Due to various reasons we had to therefore enable roundcube to use OAUTH/XOAUTH for authentication. I thought to roughly sketch how I achieved this, problems that I had to solve along the way and then I can also help with implementation of the solution.

**Prerequisites**: 
* I wanted OAUTH/XOAUTH support, as roundcube is included as iframe in to the main web application (based on Angular if that matters) and various coustom plugins communicate with the same backend – therefore goal was a single sign-in solution (provided by keycloak - https://github.com/keycloak/keycloak ) for all services.
* I wanted to do as much of the implementation as possible as a plugin and modify as little roundcube code al possible, therefore I used a lot of document (and some un documented, if I recall correctly) hooks provided by roundcube.

**Overview of the solution**: Developed a plugin with following hooks, utilize https://github.com/stevenmaguire/oauth2-keycloak as OAUTH provider for specific Keycloak server.
1. Startup hook: If user is logged-in, check if OAUH/XOAUTH token needs to be refreshed, if user is not logged-in do the OATUH/XOUATH procedure and save access token.
2. authenticate hook: set $args[‘user’] with oauth username and $args[‘pass’] with access token and a few other bits and pieces.
3. login_after hook – store access token
4. logout_after hook – redirect to logout url of the OAUTH/XOAUTH provider, clearing things in the roundcube
5. storage_connect hook: set correct user and pass.
6. smtp_connect hook and corresponding callback function: 
```
function smtp_connect($args) {
        //called on every SMTP connect, lets add XOAUTH2 auth protocol
        $args['smtp_auth_callbacks'] =[[
            'name' => 'XOAUTH2',
            'function' => array($this, 'smtp_connect_XOAUTH2')
        ]];
        return $args;
    }

public function smtp_connect_XOAUTH2($smtp_user, $smtp_pass, $smtp_authz, $Net_SMTP) {
        //XOAUTH2 login function
        $smtp_user = $this->getUsername($this->accessToken);
        $smtp_pass = $this->accessToken->getToken();

        $auth_str = base64_encode('user='.$smtp_user . "\001auth=Bearer " . $smtp_pass . "\001\001");

        return $Net_SMTP->command('AUTH XOAUTH2 '.$auth_str, 235);
    }
```
Therefore what is missing – I coudnt find similar to smtp_connect way to “inject” XOUATH2 into IMAP protocol implementation in the roundcube, therefore for the IMAP to work I had to modify rcube_imap_generic.php.
This required the only modification of the Roundcube code. As I am deploying everything as a docker contariner, I am replacing file lib/Roundcube/rcube_imap_generic.php with docker.

Changes:
In the connect function, I had to add XOUATH2 as auth method and corresponding XOUATH2 function:
```
class rcube_imap_generic
{
...
public function connect($host, $user, $password, $options = array())
{
...
// Authenticate
switch ($auth_method) {
    case 'CRAM_MD5':
        $auth_method = 'CRAM-MD5';
    case 'CRAM-MD5':
    case 'DIGEST-MD5':
    case 'PLAIN':
    case 'GSSAPI':
        $result = $this->authenticate($user, $password, $auth_method);
        break;
    case 'LOGIN':
        $result = $this->login($user, $password);
        break;
    case 'XOAUTH2':
        $result = $this->XOAUTH2($user, $password);
        break;
    default:
        $this->setError(self::ERROR_BAD, "Configuration error. Unknown auth method: $auth_method");
}
...
}
...
/**
 * Jure Tuta addon function -> login with XOAUTH2
 *
 * @param string $user - username
 * @param string $password - password
 * @return resource|int Connection resource on success, error code on error
 */
protected function XOAUTH2($user, $password)
{

    $reply = base64_encode('user='.$user . "\001auth=Bearer " . $password . "\001\001");

    list($result, $line) = $this->execute("AUTHENTICATE XOAUTH2", array($reply),
        self::COMMAND_LASTLINE | self::COMMAND_CAPABILITY | self::COMMAND_ANONYMIZED);

    if ($result == self::ERROR_OK) {
        // optional CAPABILITY response
        if ($line && preg_match('/\[CAPABILITY ([^]]+)\]/i', $line, $matches)) {
            $this->parseCapability($matches[1], true);
        }
        return $this->fp;
    }
    else {
        $this->setError($result, "AUTHENTICATE XOAUTH2: $line");
    }

    return $result;
}
...
}
```

At the time this project was taking 100% of my time therefore I didn't procede with making pull request or something else. Also as there is also beforemetioned plugin I didnt know what exactly  should go into main roundcube app and what should go in a seperate "roundcube-keycloak-oauth" plugin etc.

As stated I am willing to help and as said before I managed to get by without modifying Net_SMTP (in ref to @thomascube 's  PR55). Only thing required (beside digging throught roundcube code and developing massive custom plugin) was modification to `rcube_imap_generic` class. Would such change be acceptable to be integrated in the roundcube master?

**Comment by thomascube** [comment] 2019-10-30 10:10
@jtuta Thanks a lot for this. I'm already pretty far with integrating OAuth into Roundcube core and my changes include most of the points you outlines, except the logout part. If you find some time, please review my [recent commit](https://github.com/thomascube/roundcubemail/commit/db181d99bd7c2bc20440d47a462f5dec58ad5124) and add comments where you identify problems to make it generic. As said, I so far only tested with Google and namely the part where Roundcube needs to fetch the user's email address (identity) might not yet work for all providers.

**Comment by thomascube** [comment] 2019-10-30 10:12
> You said you tested it with Gmail, I didn't see a commit to rcube_imap_generic. Actually I expect some more code. Where is it?

I committed to a fork: https://github.com/thomascube/roundcubemail/commit/db181d99bd7c2bc20440d47a462f5dec58ad5124

**Comment by jtuta** [comment] 2019-10-30 10:27
@thomascube , sorry I didn't see this issue earlier, earlier comment might ease your work. Today I was just checking up on 1.4 release and went through open issues. Will check and try to use your code aginst my setup later today in the evening. Details of the setup:
* keycloak ( https://github.com/keycloak/keycloak ) for identity provider (IdP) 
* modified (in order to support XOAUTH2) mail server based on this docker immage https://github.com/tomav/docker-mailserver 

To add on the logout part, nowadays I use exclusivly XOAUTH2, therefore I auto redirect to the IdP if user is not loggied in, and of course to log user out (of all sites where this SSO is used) I redirect to IdP on logout. Some time ago I had to support simoutanisly XOAUTH2 and PLAIN login, and at that time I had a "dirty" hack in the code, where if password wold be shorter than 100 characers it would be threated as plain text login, if it was longer it would threat it as OAuth - I dont know if this is general, but due to my specific usecase and data stored in the token my tokens are veeeeeerry log strings. Looking back I should have checked if password is base64encoded valid json, and use that as an indicator of the login type....

**Comment by jtuta** [comment] 2019-10-30 12:40
Got a few minutes to play with your code.

1. I was *kinda* able to get imap working, will work on the smtp later - probably it doesn't work out-of the box due to Net_SMTP and PR55

2. I had to disable ssl certificate checking : added 'verify' => false, to both $options arrays of the ->post and ->get methods in rcmail_oauth.php

I fully understand that for the security reasons my 'dirty fix' is not good. But I insist, that administrator should be able to skip ssl-validation because in modern applications with gateways etc., there is often mismatch between ssl certificate and domain name - how come? In my case, docker container contains roundcube and container containing mail server are talking to each-other via private network (172.27.x.x/12) only by hostnames like 'ssl://mail:993', and not fully qualified domain names routable in the internet (e.g. ssl://mail.domain-example.com:993) for which my mail server has valid certificate, therefore there is certificate mismatch. 

Therefore I think there should be configuration possibility for the 'verify' options of the requests.

3. For my case rcube_imap.php -> function `connect($host, $user, $pass, $port=143, $use_ssl=null)`, has wrong `$user`, it has primary mail of the user and not the username. To get IMAP working I firstly mocked `$user = 'my-username';` in the first line of the function. After further inspection I can see in rcmail_oauth.php that you are defining `$username = $identity['email'];`, and if-I-recall-correctly there is no standard defining what the username is - therefore this should probably be changed and not hard-coded. (In my case it should be `$username = $identity['preferred_username'];`)

4. In the error logs it seems that oauth refresh token request always fails due to <url> malformed. I didn't yet digg into to see if this is due to my changes. On a second thought, it seem that this could be your fault as I think `$oauth_token_uri`, `$oauth_client_id` and `$oauth_client_secret` are not defined in the function `refresh_access_token`. - see: https://github.com/thomascube/roundcubemail/blob/db181d99bd7c2bc20440d47a462f5dec58ad5124/program/include/rcmail_oauth.php#L295 You are probably missing something like this at the top of the function
```php
        $oauth_token_uri = $this->options['token_uri'];
        $oauth_client_id = $this->options['client_id'];
        $oauth_client_secret = $this->options['client_secret'];
```
I also had to add 'verify' => false to this request, see [2.] for details.

Optional enhancement requests: 
* due to my usecase (and I suspect many others) auto redirect on login would be reasonable (also OP @rayflexcom probably has only way of signing in through Office 365, therefore showing login form is adding 1 extra click)
* already spoken logout feature (adding logout url to the config and redirecting when necesarry)

**Comment by jtuta** [comment] 2019-10-30 12:56
Of course after modifying Net_SMTP in the same way as in your PR smtp also works using `$username = $identity['preferred_username'];` discussed before. 

Due to my already existing smtp_conn_options config, certificate pose no problems here:
```
$config['smtp_conn_options'] = array('ssl' => array(
    'verify_peer'  => false,
    'verify_peer_name' => false,
    'allow_self_signed' => true
));
```

**Comment by thomascube** [comment] 2019-11-25 21:00
> @thomascube : Got a few minutes to play with your code.
>     2. I had to disable ssl certificate checking : added 'verify' => false, to both $options arrays of the ->post and ->get methods in rcmail_oauth.php
> 
> I fully understand that for the security reasons my 'dirty fix' is not good. But I insist, that administrator should be able to skip ssl-validation because in modern applications with gateways etc., there is often mismatch between ssl certificate and domain name - how come? In my case, docker container contains roundcube and container containing mail server are talking to each-other via private network (172.27.x.x/12) only by hostnames like 'ssl://mail:993', and not fully qualified domain names routable in the internet (e.g. ssl://mail.domain-example.com:993) for which my mail server has valid certificate, therefore there is certificate mismatch.

Why do you event use SSL when all nodes connect on a private network? That doesn't make sense to me.

> Therefore I think there should be configuration possibility for the 'verify' options of the requests.

Agreed.

> 
>     1. For my case rcube_imap.php -> function `connect($host, $user, $pass, $port=143, $use_ssl=null)`, has wrong `$user`, it has primary mail of the user and not the username. To get IMAP working I firstly mocked `$user = 'my-username';` in the first line of the function. After further inspection I can see in rcmail_oauth.php that you are defining `$username = $identity['email'];`, and if-I-recall-correctly there is no standard defining what the username is - therefore this should probably be changed and not hard-coded. (In my case it should be `$username = $identity['preferred_username'];`)

Yes, there's no standard defining what the username is. The current implementation uses what Google suggests. We might end up with another config option defining the identity field picked for the login username.

>     2. In the error logs it seems that oauth refresh token request always fails due to url being malformed. I didn't yet dig into to see if this is due to my changes. On a second thought, it seem that this could be your fault as I think `$oauth_token_uri`, `$oauth_client_id` and `$oauth_client_secret` are not defined in the function `refresh_access_token`.

Indeed. I wasn't able to test the refresh token part because for some reason my Google login doesn't return a refresh token.

> I also had to add 'verify' => false to this request, see [2.] for details.
> 
> Optional enhancement requests:
> 
>     * due to my usecase (and I suspect many others) auto redirect on login would be reasonable (also OP @rayflexcom probably has only way of signing in through Office 365, therefore showing login form is adding 1 extra click)

I think the login via OAuth should be an intentional action and I hesitate to do an automatic redirect here. Of course we can still add a config option for this.

>     * already spoken logout feature (adding logout url to the config and redirecting when necesarry)

Logging out of Roundcube doesn't necessarily need to terminate the authentication on the OAuth service.

>     * again due to the my use-case (and I didn't check if this is already possible) I think any plugin should be able to access the token - For example we are using this token to authenticate on the backend server and dynamically load address book from one of our servers, and much more.....

True. Masking it as we currently do probably isn't very helpful. We might consider encrypting it - or at least the refresh token which is a more precious value.

Thanks for your review, I'll follow up with some more changes and additions.

**Comment by jtuta** [comment] 2019-11-26 13:31
> Why do you event use SSL when all nodes connect on a private network? That doesn't make sense to me.

I agree that SSL wouldn't be required in this case, but as mail server is also accessible to the outside (using smtps/imaps) it is easier to utilise and then maintain ports and protocols which have to be configured anyway. Again I agree, not required, but we can probably agree that it doesn't introduce too big of an overhead on modern equipment and if due to the user count extra optimisations are not required. Off-topic here, lets continue.

> We might end up with another config option defining the identity field picked for the login username.

I think this should be the way to go, for example:
- Dovecot mail server [docs](https://wiki.dovecot.org/PasswordDatabase/oauth2) has parameter `username_attribute`

> I think the login via OAuth should be an intentional action and I hesitate to do an automatic redirect here. Of course we can still add a config option for this.

To show an example: when you go to [google drive](https://drive.google.com/drive/my-drive) it auto redirects to the oauth login on accounts.google.com. Of course it is ultimately your decision at the end, but I would strongly support config option for this. Setting up such system (IdP, mailserver with OAuth support, etc.) is not for beginners, my guess is that OAuth will be used in advanced scenarios where applications are similarly tightly connected (as in googles ecosystem or in mine usecase).

> Logging out of Roundcube doesn't necessarily need to terminate the authentication on the OAuth service.

Agreed that is doesn't necessarily need to terminate but it is a useful feature - e.g. when you log out of one of the google services, it logs you out from entire suite - gmail, calendar, .... And also the same argument about advanced tightly connected information systems. As developer and architect of such system (where security is an important feature) I rather see that client gets mistakenly logged-out "too-much", than that he/she mistakenly stays logged-into a system when leaving the computer.

Thank you for your work!

**Comment by dcoxjr** [comment] 2019-12-16 20:50
Does Google's announcement today weigh into the issue at all?

[Starting in June 2020, we’ll limit the ability for less secure apps (LSAs) to access G Suite account data.](https://gsuiteupdates.googleblog.com/2019/12/less-secure-apps-oauth-google-username-password-incorrect.html)

**Comment by thomascube** [comment] 2019-12-17 10:26
We're currently working on OAuth support for Roundcube and that'll include Gmail access. So no worries, we'll be ready by then.

**Comment by sombatos** [comment] 2019-12-25 12:19
Gmail OAuth and Standard PHP IMAP
https://github.com/google/gmail-oauth2-tools/issues/18

**Comment by thomascube** [comment] 2020-01-04 13:30
Current development version works with Gmail but I was unable to perform an IMAP login with an outlook.com (former Hotmail) account. Please somebody who has more experience with Microsoft services help testing. A complete build tarball is attached. Example config is shown in [defaults.inc.php](https://github.com/thomascube/roundcubemail/blob/pr-xoauth2/config/defaults.inc.php#L360). Copy the according lines to your config.inc.php file.

Feedback and suggestions for improvements are more than welcome.

[Uploading roundcubemail-dev-oauth.tar.gz…](roundcubemail-dev-oauth.tar.gz)

**Comment by jtuta** [comment] 2020-01-05 19:59
Trying to help with whole Microsoft mail thing - have you seen this: https://stackoverflow.com/questions/29747477/imap-auth-in-office-365-using-oauth2

**Comment by thomascube** [comment] 2020-01-07 20:50
Yes, `CAPABILITY` says `XOAUTH2` is supported and it was an announcement from Microsoft that started this ticket in the first place. I just didn't find the right place to get help from Microsoft on this.

**Comment by jtuta** [comment] 2020-01-09 09:30
Hey @thomascube , I don't know how far were you able to get in the login/imap process. I was able to obtain token (got: "Auth code success" in ouath2.log), but then the imap session looks like:

```
[09-Jan-2020 07:35:55 +0000]: <58400257> [AEB7] Connecting to tls://outlook.office365.com:143...
[09-Jan-2020 07:35:55 +0000]: <58400257> [AEB7] S: * OK The Microsoft Exchange IMAP4 service is ready. [QQBNADAAUABSADAANgBDAEEAMAAwADQANgAuAGUAdQByAHAAcgBkADAANgAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]
[09-Jan-2020 07:35:55 +0000]: <58400257> [AEB7] C: A0001 CAPABILITY
[09-Jan-2020 07:35:55 +0000]: <58400257> [AEB7] S: * CAPABILITY IMAP4 IMAP4rev1 LOGINDISABLED STARTTLS SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
[09-Jan-2020 07:35:55 +0000]: <58400257> [AEB7] S: A0001 OK CAPABILITY completed.
[09-Jan-2020 07:35:55 +0000]: <58400257> [AEB7] C: A0002 STARTTLS
[09-Jan-2020 07:35:55 +0000]: <58400257> [AEB7] S: A0002 OK Begin TLS negotiation now.
[09-Jan-2020 07:35:55 +0000]: <58400257> [AEB7] C: A0003 CAPABILITY
[09-Jan-2020 07:35:55 +0000]: <58400257> [AEB7] S: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
[09-Jan-2020 07:35:55 +0000]: <58400257> [AEB7] S: A0003 OK CAPABILITY completed.
[09-Jan-2020 07:35:55 +0000]: <58400257> [AEB7] C: A0004 ID ("name" "Roundcube" "version" "1.5-git" "php" "7.3.11" "os" "Linux" "command" "/index.php/login/oauth?code=OAQABAAIAA****")
[09-Jan-2020 07:35:55 +0000]: <58400257> [AEB7] S: A0004 BAD ID failed
[09-Jan-2020 07:35:55 +0000]: <58400257> [AEB7] C: A0005 AUTHENTICATE XOAUTH2 ***
[09-Jan-2020 07:35:56 +0000]: <58400257> [AEB7] S: A0005 NO AUTHENTICATE failed.
```

Is this the point where you are also stuck?

Interesting observation - if I try to validate access token on the  https://jwt.io/ i get **Invalid Signature**. I know - if I would be implementing XOUATH2 on the imap server, I'd check validity of the token and return *AUTHENTICATE failed* if it wouldn't be valid. What do you think, could problem actually be here?

**Comment by thomascube** [comment] 2020-01-09 10:03
@jtuta This is exactly how far I got: successfully obtained an access token and username from the JWT returned with the OAuth response but then failed to authenticate via IMAP using these credentials (`NO AUTHENTICATE failed`) without any further explanation (Gmail for example also returns a reason if `AUTHENTICATE XOAUTH2` fails).

Please don't get confused with the JWT: the OAuth service may return a JWT (`id_token`) that contains identity information which we use to extract the username from. This is not the access token! For XOAUTH2 authentication we need both the username and the access token. Don't expect a valid result when pasting the access token to jwt.io. You'd need to grab the `id_token` value from the [OAuth response](https://github.com/thomascube/roundcubemail/blob/06c67bc002ed77d088fed167ab7271ff6d5b5f30/program/include/rcmail_oauth.php#L226) for this.

**Comment by thomascube** [comment] 2020-01-09 10:07
> What do you think, could problem actually be here?

The problem is that `outlook.office365.com` doesn't accept our `AUTHENTICATE XOAUTH2` request using the username and access token we get from their OAuth service. Maybe we use the wrong scopes or anything else. I have no idea and wasn't able to find any information so far.

**Comment by alecpl** [comment] 2020-01-09 10:44
Did you try `wl.imap wl.offline_access` scope?

**Comment by jtuta** [comment] 2020-01-09 10:56
I tried all *mail* scopes - `email Mail.Read Mail.Read.Shared Mail.ReadBasic Mail.ReadWrite Mail.ReadWrite.Shared Mail.Send Mail.Send.Shared MailboxSettings.Read MailboxSettings.ReadWrite offline_access openid profile User.Read`, did not found `wl.imap` anywhere in the app config....

**Comment by dvdp** [comment] 2020-01-28 13:30
I'm testing this out with GMail - got stuck close to the end - any advice very welcome ...
I grabbed the roundcubemail-dev-oauth.tar.gz, configured things in the google console and updated the config.inc.php with the (hopelfully) correct settings.
My RC login page now has a button 'Login with Google'. If I hit that button I get directed to the Google accounts page. After picking the right account I get a page indicating RoundCube wants to a access my GMail (RoundCube is the name of the OAuth 2.0-client-ID). So for so good but if I then click 'Allow' I'm getting directed back to an unformatted RC login page.  Something I missed I guess, any idea?

**Comment by dvdp** [comment] 2020-01-28 13:54
This might explain:
 PHP Error: OAuth token request failed: cURL error 60: SSL certificate problem: unable to get local issuer certificate;  in /home/....

**Comment by dvdp** [comment] 2020-01-28 21:05
... fixed some things in php.ini - working fine now, great work - thx.
So the big question: when will this get implemented a new RC release ?

**Comment by demeritcowboy** [comment] 2020-02-13 02:12
Hi, I see above some people have said this is working with google but I'm wondering if anyone has it working with a regular gmail.com email not a gsuite email? If I try to get a client id/secret at the google developer console with a regular gmail account it doesn't let me create an _internal_ application.

**Comment by dvdp** [comment] 2020-02-13 15:15
Just go for an external application - that should work. I just did a quick test and managed to create a id/secret using a non-GSuite account for an external application. I haven't gone all the way down to configure RC for it so I leave that up to you to try.
Internal app = restricted  to G-Suite users only indeed.
Actually, I see little use in using RC to read you personal gmail - unless you really hate the GMail client ...  We're using it because we can customize it and have it pull the address book from our LDAP server.

**Comment by demeritcowboy** [comment] 2020-02-13 15:25
Ok thanks for the reply. I was able to create an id/secret but it said the application was unpublished and I figured I was maybe going down the wrong path since it seemed to be getting more complicated than most things. I'll keep going and see.

**Comment by thomascube** [comment] 2020-02-19 12:15
> Hi, I see above some people have said this is working with google but I'm wondering if anyone has it working with a regular gmail.com email not a gsuite email?

Yes, that worked for me. I just created a public application in Google's developer console and access to my Gmail account works. The application however was sent for verification by Google which never passed (for obvious reasons). Although login generally works, you'll see some warnings at Google login that you're about to give access to an unverified and likely suspicious app. Also, I never get a refresh token from these logins which end up in Roundcube sessions expiring after a short time.

**Comment by demeritcowboy** [comment] 2020-02-19 17:22
Yes thanks I was able to get it going and as you note there's a scary warning message but it seems there's no way around that. But at least it lets you give access anyway.

**Comment by Jost-Philip** [comment] 2020-03-18 21:26
Hi! Just to understand this correctly:
Is there anything in your OAuth code specific to MS or Google, or is this intended to work with other arbitrary standard compliant auth providers too?
What I'm asking is: could I also use this to authenticate against my personal (properly configured) dovecot and/or nextcloud server without requiring a 3rd party, or is the use case limited to "the big players"?

**Comment by jtuta** [comment] 2020-03-18 21:32
Yes, if you have your dovecot (or other systems) configured for oauth. I have tested it with my combination of dovecot and keycloack.

**Comment by dvdp** [comment] 2020-04-06 07:46
My users are complaining about timeouts / authentication failures after spending some amount of time in RC authenticated to GMail. I've checked and tweaked (at least tried to) the timeout settings in the RC config but so far no improvement. Anyone else had the same issues - recommendations ?
TIA

**Comment by miximka** [comment] 2020-05-06 21:57
Hi! Just stumbled upon this issue while searching for a solution to a problem we have with a mobile e-mail app connecting to Office 365 via IMAP/SMTP + OAuth2.
We also stuck at the point where IMAP server responds with `NO AUTHENTICATE failed` and SMTP server with `535 5.7.3 Authentication unsuccessful`. Tried every combination of scopes - nothing works so far... 
Just FYI: MS recently (30.04.2020) announced OAuth 2.0 support for IMAP+SMTP protocols: https://developer.microsoft.com/en-us/graph/blogs/announcing-oauth-2-0-support-for-imap-smtp-client-protocols-in-exchange-online/
Unfortunately, the detailed step-by-step instructions for [authenticating to IMAP, SMTP AUTH protocols using OAuth](https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth) only worked to the point where IMAP and SMTP servers reject provided XOAuth token.
There seems to be some fundamental issue with Office 365 at this point - the same task with Gmail worked like a charm.

**Comment by reubenr0d** [comment] 2020-05-14 15:33
> Also, I never get a refresh token from these logins which end up in Roundcube sessions expiring after a short time.

I was recently tasked with integrating XOauth with RC, and everything you have works great (I have only tested Gmail so far) other than the refresh token, `$token['refresh_token']` seems like is not defined [here](https://github.com/thomascube/roundcubemail/blob/db181d99bd7c2bc20440d47a462f5dec58ad5124/program/include/rcmail_oauth.php#L372); did you to figure this out, @thomascube ?

**Comment by thomascube** [comment] 2020-05-15 06:39
> seems like is not defined here; did you to figure this out?

Unfortunately not. According to the documentation it should be there but I assume Google doesn't issue a refresh token in my case because the app I registered for development is not official and was never approved by Google.

**Comment by thomascube** [comment] 2020-05-15 06:42
> We also stuck at the point where IMAP server responds with `NO AUTHENTICATE failed` and SMTP server with `535 5.7.3 Authentication unsuccessful`. Tried every combination of scopes - nothing works so far...
> Unfortunately, the detailed step-by-step instructions for authenticating to IMAP, SMTP AUTH protocols using OAuth only worked to the point where IMAP and SMTP servers reject provided XOAuth token.

@miximka Thanks for the links! The permission scopes `IMAP.AccessAsUser.All` and `SMTP.Send` seem to be new information and I'll give it another try with Outlook soon.

**Comment by miximka** [comment] 2020-05-15 07:22
@thomascube I got it finally working.
The key was to request the security scopes exactly as they described in the [documentation](https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth#get-an-access-token), not as they presented in the Azure Active Directory! Totally confusing, but maybe it is just still work in progress...
So this is the list of scopes to request when talking to `https://login.microsoftonline.com/common/oauth2/v2.0/authorize` that worked for us:
```
https://outlook.office365.com/IMAP.AccessAsUser.All
https://outlook.office365.com/SMTP.Send
offline_access
```
and this is how AD shows the scopes:

<img width="1019" alt="Screenshot 2020-05-14 at 11 47 11" src="https://user-images.githubusercontent.com/5834051/82022071-5098cb00-968c-11ea-89cd-9353b69b8ce8.png">

I didn't realize the difference until I found [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1528136) from Thunderbird.

**Comment by thomascube** [comment] 2020-05-23 20:39
@miximka I tried with the hints you gave me but failed so far. When requesting a token with fully qualified scope URIs (`https://outlook.office365.com/IMAP.AccessAsUser.All`) the auth request is rejected with an error about invalid scope values. Did you successfully connect to a free personal Microsoft (e.g. Hotmail) account? Maybe you can share your app manifest from portal.azure.com with us?

**Comment by miximka** [comment] 2020-05-25 11:15
@thomascube I don't know if the IMAP/SMTP security scopes work for personal microsoft accounts, we only needed support for organizational accounts (managed by Azure AD) and it seems to work for now. Here is [the manifest file](https://github.com/roundcube/roundcubemail/files/4676914/Manifest.json.zip) and here a[ gist file](https://gist.github.com/miximka/21dbf7d73a67a64ac7b62de95654aee8) showing how we did MS OAuth on our side (exchangeCodeForToken method). I hope it helps.

**Comment by miximka** [comment] 2020-05-25 11:21
Small clarification to the [gist](https://gist.github.com/miximka/21dbf7d73a67a64ac7b62de95654aee8) i posted:
`authURL` is the URL we present to user in WebView to sign in and `exchangeCodeForToken` is the method we call as soon as we get an auth token from the WebView to exchange it for an access and refresh tokens.

**Comment by reubenr0d** [comment] 2020-05-27 16:11
> Unfortunately not. According to the documentation it should be there but I assume Google doesn't issue a refresh token in my case because the app I registered for development is not official and was never approved by Google.

So I happened to figure this out, @thomascube. Turns out Google doesn't provide a refresh token for unverified apps if the consent prompt is not requested every time, works good after the change in config.

`$config['oauth_auth_parameters'] = ['access_type' => 'offline', 'prompt' => 'consent'];` 

Maybe you can drop this into the defaults for Google? Or maybe not, once an app is verified don't think the consent screen is still needed.

**Comment by Project0** [comment] 2020-05-27 17:53
any chance this gets into upstream? What is still missing?

**Comment by Faillinx** [comment] 2020-05-27 18:08
Should I use the dev version posted in the comments to try this out with Oauth gsuite or is there a git version that has everything in it?

**Comment by thomascube** [comment] 2020-06-07 21:03
@Faillinx The current development version is at https://github.com/thomascube/roundcubemail/tree/pr-xoauth2

A pull request for merging into master will follow soon.

**Comment by GalacticLion7** [comment] 2020-06-10 09:13
Does this issue want Roundcube to be the OAuth2 server or client?

**Comment by TuxCoder** [comment] 2020-07-01 20:50
@GalacticLion7  Roundcube need to be a `client`, the mail server is then the `resource` in the Oauth2 context.

Oauth2 Server is for example google or your own oauth2 server (keyclock, hydra, gitlab, ...) in the infrastructure.

**Comment by thomascube** [comment] 2020-08-10 19:42
Pull request merged into Git master. Adding another test and example config with Yahoo mail would be nice.

**Comment by thomascube** [comment] 2020-09-27 19:00
> Adding another test and example config with Yahoo mail would be nice.

Since Yahoo requires an individual application to get email access grants for OAuth, this is not a use-case of general interest.

We consider this feature request now as complete. Please create follow-up tickets if there's something missing or dysfunctional.

**Closed by thomascube** 2020-09-27 19:00 UTC
Labels: C: IMAP, C: SMTP, enhancement
