### ISSUE TITLE
Can "Place replies in the folder of the message being replied to" also work when composing new mail when in folder ?  #bug? #feature?

### ISSUE THREAD

**Issue by kiceki** [roundcube/roundcubemail#7775] opened 2020-12-11 16:38 UTC
All in title : I find disturbing that while the option "Place replies in the folder of the message being replied to" is checked and work on replying messages in folder, it doesn't do the same for composing new message while located in a folder.

Is it a bug ? Is it a feature request ?

It would be great if it worked the way i hoped i does.

**Comment by alecpl** [comment] 2020-12-11 20:36
Duplicate of #7166

**Closed by alecpl** 2020-12-11 20:36 UTC
