### ISSUE TITLE
Add folder Path for search results with automatic translation for german

### ISSUE THREAD

**Issue by tronx2100** [roundcube/roundcubemail#9107] opened 2023-08-27 17:55 UTC
simple add direct after this block: and then minify the app.js and create a new app.min.js with minified content

    // build subject link
    if (cols.subject) {
      var action  = flags.mbox == this.env.drafts_mailbox ? 'compose' : 'show',
        uid_param = flags.mbox == this.env.drafts_mailbox ? '_draft_uid' : '_uid',
        query = { _mbox: flags.mbox };
      query[uid_param] = uid;
      cols.subject = '<a href="' + this.url(action, query) + '" onclick="return rcube_event.keyboard_only(event)"' +
        ' onmouseover="rcube_webmail.long_subject_title(this,'+(message.depth+1)+')" tabindex="-1"><span>'+cols.subject+'</span></a>';
    }
    

// beginn folder path for search results with German translations
// insert this

    if (uid && this.env.search_request) {
        var mmbox = this.get_message_mailbox(uid);
        var labels = {
            'inbox': 'Posteingang',
            'sent': 'Gesendet',
            'drafts': 'Entwürfe',
            'spam': 'Spam',
            'deleted': 'Gelöscht',
            'archive': 'Archiv',
            'notes': 'Notizen'
        };

        // Prüfen, ob der Browser Deutsch verwendet
        var isGerman = false;

        if (navigator.languages) {
            for (var i = 0; i < navigator.languages.length; i++) {
                var language = navigator.languages[i];
                if (language.toLowerCase().startsWith('de')) {
                    isGerman = true;
                    break;
                }
            }
        } else if (navigator.language) {
            if (navigator.language.toLowerCase().startsWith('de')) {
                isGerman = true;
            }
        }

        for (var label in labels) {
            if (mmbox.toLowerCase().startsWith(label)) {
                var translatedLabel = isGerman ? labels[label] : label;
                mmbox = mmbox.replace(new RegExp(label, 'i'), translatedLabel);
                break; 
            }
        }
        if(mmbox) {
          mmbox = mmbox.replace(/\./g, '/');
          mmbox = mmbox.replace(new RegExp(label, 'i'), translatedLabel);
               if (cols.subject) {
                 cols.subject =  cols.subject + '<br /><span style="color:blue;font-size:smaller;">' + mmbox + '</span>' ;
              }
        }
    }

**Comment by alecpl** [comment] 2023-09-14 06:29
Duplicate of #7950 and the suggested solution is very bad.

**Closed by alecpl** 2023-09-14 06:29 UTC
