### ISSUE TITLE
Managesieve plug-in UI issue in 1.4.0 release

### ISSUE THREAD

**Issue by sffax** [roundcube/roundcubemail#7012] opened 2019-11-11 02:27 UTC
Login as a user, go to Settings --> Filters --> managesieve --> select any filter .

At this point it is impossible to navigate away from the Filters UI (contacts, mail, settings, logout) unless you click "Save" first (even without making any changes). The issue doesn't seem to be skin specific.

**Comment by alecpl** [comment] 2019-11-11 07:04
Duplicate of #7007.

**Closed by alecpl** 2019-11-11 07:04 UTC
Labels: C: User Interface, bug
