### ISSUE TITLE
Deprecation message: implode with glue string after array

### ISSUE THREAD

**Issue by rivimey** [roundcube/roundcubemail#7856] opened 2021-01-27 13:16 UTC
On PHP 7.4.14, the running of the cleandb.sh script results in this message, 4 times:

    PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 918

line 918 of rcube_db.php is:

    return implode($name, '.');

and should be:

    return implode('.', $name);

**Comment by alecpl** [comment] 2021-01-27 13:25
I think you should upgrade Roundcube. It's been fixed long time ago. Duplicate of #6866.

**Closed by alecpl** 2021-01-27 13:25 UTC

**Comment by rivimey** [comment] 2021-01-29 04:05
I have upgraded to the latest stable version... it's just a long way behind HEAD.

A new stable please?
