### ISSUE TITLE
Composer issue when updating from 1.2.1 to 1.2.3

### ISSUE THREAD

**Issue by Yannik** [roundcube/roundcubemail#5556] opened 2016-12-09 15:28 UTC
Hi,

as instructed by `bin/installto.sh` ("NOTE: Update dependencies by running `php composer.phar update --no-dev"), I just tried to update my roundcube installations composer dependencies (I updated roundcube from 1.2.1 to 1.2.3).

However, this fails with the following error:

```
# composer update --no-dev
Loading composer repositories with package information
Initializing PEAR repository https://pear.php.net
Updating dependencies                                          
                                                                               
  [Composer\DependencyResolver\SolverProblemsException]                        
    Problem 1                                                                  
      - The requested package pear-pear.php.net/crypt_gpg ~1.4.2 exists as pe  
  ar-pear.php.net/Crypt_GPG[1.6.0b3] but these are rejected by your constrain  
  t.  
```

**Comment by Yannik** [comment] 2016-12-09 15:41
I managed to fix this by copying `composer.json-dist` over `composer.json`.

Shouldn't this be handled by `bin/installto.sh` though?

**Comment by alecpl** [comment] 2016-12-11 08:41
The script already has code to update dependencies in composer.json, but it depends on a couple of facts:
1. composer.json file exists and is writable
2. composer.json-dist file exists and is readable
3. composer.phar file exists or PHP 5.4 is in use

Didn't you get "WARNING: unable to update composer.json!"?

**Comment by Yannik** [comment] 2016-12-12 16:02
1. satisfied
2. satisfied as well
3. php 5.6 was in use for this update. a composer.phar file did not exist, but `composer` did.

No, I did not notice this warning. As a composer.json file did exist and was writable (and the update was done as root), just as a json-dist file did exist and was readable (atleast after the update), this should probably have not happened.

Any ideas why?

**Comment by alecpl** [comment] 2016-12-23 08:54
I can't reproduce. `composer.json-dist` in 1.2.1 and 1.2.3 are the same. So, what did you change in `composer.json`? I guess maybe `minimum-stability` and/or crypt_gpg version, but still works for me. So, I'd need you `composer.json` file from before the upgrade.

**Comment by Yannik** [comment] 2017-01-03 14:40
Unfortunately, I do not have access to the old composer.json anymore.

**Comment by alecpl** [comment] 2017-01-05 20:20
We'll get back to this when we have a possibility to reproduce the issue. Closing now.

**Closed by alecpl** 2017-01-05 20:20 UTC
Labels: C: Installer, need feedback
