### ISSUE TITLE
E-mail attachments are not visible

### ISSUE THREAD

**Issue by ner00** [roundcube/roundcubemail#6279] opened 2018-05-03 17:40 UTC
I recently came across an issue with an e-mail message in Roundcube's inbox that was forwarded from an account using Outlook 2007. The forwarded e-mail contains 2 images as attachments but Rouncube (1.3.6) does not show those attachments.

Curiously, if I try to forward this message then the 2 attachments will show up in the message editor, it is actually the only way of accessing the attachments through Roundcube.

I made a dummy EML based on the original message, it is zipped and attached below.
[FW Some random e-mail.zip](https://github.com/roundcube/roundcubemail/files/1972014/FW.Some.random.e-mail.zip)

**Comment by alecpl** [comment] 2018-05-04 07:44
This is because the attachments have Content-ID specified as they were an inline images. Duplicate of #5051.

**Closed by alecpl** 2018-05-04 07:44 UTC

**Comment by Neustradamus** [comment] 2024-01-26 16:08
Linked to:
- https://github.com/roundcube/roundcubemail/pull/9150
- https://github.com/roundcube/roundcubemail/issues/5051
- https://github.com/roundcube/roundcubemail/issues/6279
- https://github.com/roundcube/roundcubemail/issues/7117
- https://github.com/roundcube/roundcubemail/issues/7122
- https://github.com/roundcube/roundcubemail/issues/7214
- https://github.com/roundcube/roundcubemail/issues/7293
- https://github.com/roundcube/roundcubemail/issues/7414
- https://github.com/roundcube/roundcubemail/issues/7440
- https://github.com/roundcube/roundcubemail/pull/7441
