### ISSUE TITLE
Double click does not open email

### ISSUE THREAD

**Issue by deZillium** [roundcube/roundcubemail#5828] opened 2017-06-30 07:44 UTC
Hello,

Roundcube version: 1.3.0

Plugins enabled:
attachment_reminder	1.1
emoticons	2.0
filesystem_attachments	1.0
jqueryui	1.12.0
markasjunk2	dev-master

OS: Debian 9 Stretch

Roundcube upgraded from previous version using https://github.com/roundcube/roundcubemail/releases/download/1.3.0/roundcubemail-1.3.0-complete.tar.gz

When double clicking on an email, the email is not opened as with previous versions. Enabling the "open in new window" doesn't work either, the email just gets previewed as if double clicking isn't recognized.

JS console, web server logs don't show any errors.

**Comment by alecpl** [comment] 2017-06-30 07:45
This is an intentional change. It was needed because we wanted to eliminate 500ms delay in message loading on a single click. We can't do this with double-click handler enabled. So, double-click is working only if you have the preview pane hidden. So, wontfix.

**Closed by alecpl** 2017-06-30 07:45 UTC

**Comment by deZillium** [comment] 2017-06-30 07:58
I might be blind, but I don't see an option to hide the preview panel.

**Comment by deZillium** [comment] 2017-06-30 08:04
More appropriate: List options > Layout > List

**Comment by thomascube** [comment] 2017-06-30 08:06
Duplicate of #5823, related to #5817
