### ISSUE TITLE
feature request: subscribe multiple folders at once.

### ISSUE THREAD

**Issue by xxxmicrobexxx** [roundcube/roundcubemail#8608] opened 2022-07-07 08:42 UTC
I am in the middle of importing mail for a customer.  There are hundreds (!) of folders.  When they are imported they are not subscribed by default.  I am having to go through the list and subscribe them manually which is tedious to say the least.

It would be a good feature to be able to "select all" folders and do a mass subscribe.

**Comment by alecpl** [comment] 2022-07-09 06:51
Duplicate of #5090.

**Closed by alecpl** 2022-07-09 06:51 UTC
