### ISSUE TITLE
Help not found

### ISSUE THREAD

**Issue by Bad-and-Mad** [roundcube/roundcubemail#9622] opened 2024-09-02 05:47 UTC
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

An error has been encountered in accessing this page.

1. Server: docs.roundcube.net
2. URL path: /doc/help/1.1/en_US/mail/index.html
3. Error notes: NONE
4. Error type: 404
5. Request method: GET
6. Request query string: _framed=1
7. Time: 2024-09-02 05:39:22 UTC (1725255562)

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Other

### What version of PHP are you using?

8.1 and 8.2

### What version of Roundcube are you using?

1.6.9

### JavaScript errors

no

### PHP errors

no

**Comment by pabzm** [comment] 2024-09-02 12:56
This is a duplicate of https://github.com/roundcube/roundcubemail-helpdocs/issues/2

Apparently sourceforge.net made some changes, so now the help docs aren't reachable there anymore.
 
Unfortunately these docs received little love in the last years and are severely outdated, which is why I hesitate to just re-publish them on a different server. We/you/someone would need to bring them back into the present (adapt texts and screenshots to the "elastic" skin) before they are usable.

**Closed** 2024-09-02 12:56 UTC

**Comment by alecpl** [comment] 2024-09-02 12:58
@pabzm The docs are referred by our core "help" plugin. Maybe there's something we should do about it.

**Comment by pabzm** [comment] 2024-09-02 14:23
@alecpl I agree, that's why https://github.com/roundcube/roundcubemail-helpdocs/issues/2 is still open.
I can organise a new hosting, but the docs still need to be updated.

**Comment by pabzm** [comment] 2024-10-17 08:33
https://docs.roundcube.net//doc/help/1.1/en_US/ is back online!

(The attempt at localizing the docs isn't finished/fixed, though. I couldn't make sense of it.)
