### ISSUE TITLE
roundcube error rcmail_action line 239

### ISSUE THREAD

**Issue by happypeoplepickleball** [roundcube/roundcubemail#9132] opened 2023-09-12 00:34 UTC
Hi! I have an error on my wordpress website and I don't know how to resolve (or find the page, or what it means) I am not a developer, but I can recommend great pickleball clothes. I welcome any HELP to get this fixed. Thank you

Undefined array key "message" in /usr/local/cpanel/base/3rdparty/roundcube/program/include/rcmail_action.php on line 239

**Comment by alecpl** [comment] 2023-09-14 06:09
Duplicate of #9098. The fix will be available soon as 1.6.3 release.

**Closed by alecpl** 2023-09-14 06:09 UTC
