### ISSUE TITLE
rows is a reserved word in MariaDB 10.2.4+

### ISSUE THREAD

**Issue by JBtje** [roundcube/roundcubemail#5805] opened 2017-06-19 14:20 UTC
**Problem:**
New reserved word: ROWS. This can no longer be used as an identifier without being quoted.

**Error:**
[19-Jun-2017 14:28:18 +0100]: <dfj1haob> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows FROM \`contacts\` AS c WHERE c.\`del\` <> 1 AND c.\`user_id\` = '5' AND ((((\`emai' at line 1 (SQL Query: SELECT COUNT(c.\`contact_id\`) AS rows FROM \`contacts\` AS c WHERE c.\`del\` <> 1 AND c.\`user_id\` = '5' AND ((((\`email\` LIKE 'Mailer-Daemon@s1.someserver.com' OR \`email\` LIKE 'Mailer-Daemon@s1.someserver.com,%' OR \`email\` LIKE '%,Mailer-Daemon@s1.someserver.com,%' OR \`email\` LIKE '%,Mailer-Daemon@s1.ocdserver.nl'))))) in /var/www/html/roundcubemail-1.2.5/program/lib/Roundcube/rcube_db.php on line 539 (GET /roundcube/?_task=addressbook&_action=photo&_email=Mailer-Daemon%40s1.someserver.com)

**Solution:**
use \`rows\`

**More information:**
https://mariadb.com/kb/en/mariadb/mariadb-1024-release-notes/

**Comment by alecpl** [comment] 2017-06-19 14:26
Duplicate of #5774.

**Closed by alecpl** 2017-06-19 14:26 UTC
