### ISSUE TITLE
Show password being entered in webmail login interface

### ISSUE THREAD

**Issue by testesho** [roundcube/roundcubemail#9094] opened 2023-08-09 00:04 UTC
I would like to suggest the possibility of having an option in the "password" field of the webmail login interface to show the entered password. This would be extremely important for several users who frequently use this interface to log into their email accounts:

https://gofile.io/d/AuQ66j

Would it be possible for this feature of displaying the entered password to be made available natively?

**Comment by alecpl** [comment] 2023-08-09 05:38
Duplicate of #7250.

**Closed by alecpl** 2023-08-09 05:38 UTC
