### ISSUE TITLE
[Feature Request] Allow identity specific IMAP / SMTP data

### ISSUE THREAD

**Issue by HannesJo0139** [roundcube/roundcubemail#8209] opened 2021-09-22 17:55 UTC
I look for a solution like roundcube with multiple sets of IMAP and SMTP data in order to manage all my email accounts at one place. Unfortunately, roundcube plugins are maintained very poorly. 

Eg there are two plugins for additional smtp data. The first one has not been updated since over a year. It cannot be installed via composer since it requires out-of-date packages. Installation by hand works but the plugin is simply not working anymore. I can set settings, everything looks fine, but sending a mail is not possible. Github tickets are being ignored for over a year. The second plugin has not maintained since 2017. It works in general but breaks the function to create another identity. 

Same problem with all other types of plugins.

All in all roundcube is a very lovely piece of software with a very sad small plugin community. So I wonder if it is possible to allow at least multiple imap and smtp accounts out-of-the-box.

**Comment by schnudeldudel** [comment] 2021-09-24 10:06
#4972 ?

**Comment by schnudeldudel** [comment] 2021-09-24 10:07
Duplicate of #4972 ?

**Closed** 2021-09-24 10:13 UTC
