### ISSUE TITLE
Field 'contact_id' doesn't have a default value roundcube

### ISSUE THREAD

**Issue by paxomoschkin** [roundcube/roundcubemail#7457] opened 2020-06-27 12:33 UTC
After the curve update, the address book stopped working, old entries are edited, and new ones are not created.

**Comment by alecpl** [comment] 2020-06-27 18:25
I have no idea what are you talking about. What problem do you have and how to reproduce? What version, what plugins?

**Comment by paxomoschkin** [comment] 2020-06-27 22:01
Version 1.4.6 but the error could not have popped up due to the update, since during the update the virtual server fell into a swap and something could go wrong.
An error in the logs is written as:
DB Error: [1364] Field 'contact_id' doesn't have a default value (SQL Query: INSERT INTO `contacts` (`user_id`, `changed`,`del`, `vcard`, `name`, `email`, `words`) VALUES (15, now(), 0, (POST /?_task=mail&_framed=1'BEGIN:VCARD\r\nVERSION:3.0\r\nFN:GitHub\r\nEMAIL;TYPE=INTERNET:noreply@github.com\r\nEND:VCARD', ' noreply@github.com github')) in /var/www/mail/program/lib/Roundcube/rcube_db.php on line 543 &_action=addcontact)
plugins:
'acl', 'additional_message_headers', 'attachment_reminder', 'emoticons', 'enigma', 'globaladdressbook', 'hide_blockquote', 'http_authentication', 'identity_select', 'managesieve', 'markasjunk2', 'new_user_dialog', 'newmail_notifier', 'password', 'rcguard', 'redundant_attachments', 'show_additional_headers', 'vcard_attachments', 'virtuser_query', 'zipdownload');

**Comment by alecpl** [comment] 2020-06-28 06:30
It does not make sense. `contact_id` is an auto_increment field. What database engine/version?

**Comment by paxomoschkin** [comment] 2020-06-28 07:39
Тип сервера: MySQL
Версия сервера: 8.0.20-0ubuntu0.20.04.1 - (Ubuntu)
Кодировка сервера: UTF-8 Unicode (utf8mb4)
Apache/2.4.41 (Ubuntu)
Версия клиента базы данных: libmysql - mysqlnd 7.4.3
Версия PHP: 7.4.3

**Comment by alecpl** [comment] 2020-06-28 08:21
Could you check `SHOW CREATE TABLE contacts`? For me it looks like some problem with MySQL (or the schema).

Btw, the error entry you posted looks malformed, which might be misleading.

**Comment by paxomoschkin** [comment] 2020-06-28 08:28
ALTER TABLE `contacts`  ADD `contact_id` INT UNSIGNED NOT NULL AUTO_INCREMENT  FIRST;
MySQL Answer: Documentation

# 1075 - Incorrect table definition: only one auto-increment column can exist, and it must be defined as a key

**Comment by alecpl** [comment] 2020-06-28 08:30
Why you're adding a column that already exists? Show the current table schema.

**Comment by paxomoschkin** [comment] 2020-06-28 08:40
And I made a clean installation and noticed a difference in the scheme, and the lack of intex, I try to apply the detected errors, but fail, I deleted the defective column and try to create a model

**Comment by alecpl** [comment] 2020-06-28 08:43
I will close this ticket as it is obviously not Roundcube issue. We can re-open if you prove otherwise.

**Closed by alecpl** 2020-06-28 08:43 UTC
Labels: need feedback

**Comment by paxomoschkin** [comment] 2020-06-28 08:48
yes thanks, the problem was the lack of intex
PRIMARY BTREE t contact_id
