### ISSUE TITLE
Very slow loading of data:image content into HTML editor

### ISSUE THREAD

**Issue by uli-heller** [roundcube/roundcubemail#8108] opened 2021-07-02 05:08 UTC
I'm using version 1.4.11 of roundcube.

I have an email which I cannot forward or answer to.
Trying to do so produces something like this:

![image](https://user-images.githubusercontent.com/1677414/124223704-8739db00-db04-11eb-957d-79d26a114856.png)

I can provide more details upon request, but I don't want to upload the complete email here.

**Comment by alecpl** [comment] 2021-07-02 05:53
Check browser console for errors.

**Comment by uli-heller** [comment] 2021-07-02 06:08
I had to change a setting within roundcube to get the console for the "reply" (no new window):
![image](https://user-images.githubusercontent.com/1677414/124228237-3332f480-db0c-11eb-8898-8b4939f45b80.png)

Here is a screenshot of the message I'd like to reply to:
![image](https://user-images.githubusercontent.com/1677414/124228347-61183900-db0c-11eb-9688-f0db4ceeb01d.png)

And here the screenshot after clearing the console and pressing reply:
![image](https://user-images.githubusercontent.com/1677414/124228483-8dcc5080-db0c-11eb-96ce-9cbe124a27f5.png)

Please note: "To"(An) now contains a value - probably because I changed the roundcube settings?

**Comment by alecpl** [comment] 2021-07-02 06:46
Strange that there's no error, because the page looks exactly like when some js code wasn't executed, usually stopped by an error.

**Comment by uli-heller** [comment] 2021-07-02 07:07
Yes, but I didn't made it up. Now that you mention it, I sometimes "see" a screen like the one above for other mails, too. But it disappears pretty soon, probably due to javascript actions. I'll try again using firefox...

**Comment by uli-heller** [comment] 2021-07-02 07:16
Here are my observations:

- it looks pretty similar in firefox at first
- after a couple of seconds (10-30), the reply mail window changes and looks fine
- I tried again with chrome
- after 2 minutes, the window is still garbled up
- you cannot work within chrome any more, everything is extremely slow
- even closing the window takes time
- closing all roundcube windows/tabs makes chrome snappy again

So: Maybe some kind of javascript loop?

**Comment by alecpl** [comment] 2021-07-08 06:14
I see that there's quite a big inline image in the html content. Maybe this is the problem. Could you confirm it works with html email that have no such base64 images? You could also try 1.5-rc where we updated TinyMCE version.

**Comment by uli-heller** [comment] 2021-07-08 06:16
Hey @alecpl , I'll try do verify this. Will probably take a couple of hour since I'm @work at the moment...

**Comment by uli-heller** [comment] 2021-07-08 07:30
Here is what I did using firefox (FF) and chrome (C):

- (1-FF) Look for the mail message creating the issue
- (2-FF) Open as new message -> change "To:" to myself -> send the mail
- (3-C) Try to reply to the mail received by 2-FF -> reproduced the initial issue (good)
- (4-FF) Open the same message again and modify it -> send the mail
    * To: -> to myself
    * Replace the pictures by smaller ones
- (5-C) Try to reply to the mail received by 4-FF -> works without any issues

So: I can confirm, it works with smaller base64 images.

**Comment by alecpl** [comment] 2021-07-08 08:06
Thanks, we're getting somewhere. Could you try upgrade to 1.5-rc? Or send me (alec at alec dot pl) an example that I could test with (I could create one, but it takes time I don't have).

**Comment by uli-heller** [comment] 2021-07-08 08:51
I've sent the mails to you. I'll try 1.5-rc, but this will take a little bit of time

**Comment by alecpl** [comment] 2021-07-08 09:46
With the sample I can confirm that using 1.5-rc Firefox needs 15 seconds to complete the rendering. In Chrome it never ends and makes the page unusable. The length of the data:image/png string here is ~4MB.

Possible solutions:
1. Convert the data URI into a normal attachment.
2a. See if a fix for TinyMCE is possible.
2b. Make sure to load the content to html editor at the end of the page rendering.

**Comment by alecpl** [comment] 2021-07-15 12:14
More details. This is really not a TinyMCE issue. This is  web browsers not being able to process such a big textarea content fast. Chrome is really bad at this.

The solution for the issue is to put the content initially in a hidden input and then load it to TinyMCE using it's setContent() method. I confirm it works, and is very fast, but it is not a simple change, so I'll need more time to work on this.

ps. on the server loading such a ~4MB message takes 36MB memory in peak. It would be nice to take a look at this to, as it's quite a lot.

**Comment by alecpl** [comment] 2021-07-16 09:03
Putting a long text in a HTML attribute might not be that good idea. Some browsers may not support that. Another possibility is to hide the textarea initially (but this creates small visual issue in Elastic, the editor border is not visible for a couple of seconds). Another option would be a separate hidden textarea.

Considering that this has potential BC breaks and side effects, and that we're after 1.5-rc release, this is probably going to be fixed in 1.6 only.

**Comment by uli-heller** [comment] 2021-11-02 06:25
I finally got roundcube-1.5.0 installed. I tried to answer to the original message and got the same issue as before using Google Chrome. I didn't check with FireFox.
Note to myself: 2021-06-25 12:28 GarminConnectWeb

Could you please treat this as "low prio". I was not aware of the huge pictures when I opened the issue. Thx

**Comment by alecpl** [comment] 2022-04-03 10:30
Fixed.

**Closed by alecpl** 2022-04-03 10:30 UTC
Labels: bug, C: User Interface, C: Mail composing
