### ISSUE TITLE
Unsubscribe IMAP error toast when refreshing GMail account

### ISSUE THREAD

**Issue by bobpullen** [roundcube/roundcubemail#6923] opened 2019-09-13 11:22 UTC
Running 1.4-rc1 configured to connect to GMail's IMAP server at imap.gmail.com (elastic skin, but not sure that matters).

The logic that tries unsubscribing from NonExistent folders on mailbox refresh results in an ugly/intrusive toast pop-up indicating that there's been an error (attached).

As per IMAP logs:-
```
[12-Sep-2019 19:03:26 +0100]: <107eghbl> [01E8] S: * LIST (\HasChildren \NonExistent \Subscribed) "/" "[Gmail]"
[12-Sep-2019 19:03:26 +0100]: <107eghbl> [01E8] S: * LIST (\HasNoChildren \Subscribed) "/" "[Gmail]/All Mail"
[12-Sep-2019 19:03:26 +0100]: <107eghbl> [01E8] S: * LIST (\HasNoChildren \Subscribed) "/" "[Gmail]/Bin"
[12-Sep-2019 19:03:26 +0100]: <107eghbl> [01E8] S: * LIST (\HasNoChildren \Subscribed) "/" "[Gmail]/Drafts"
[12-Sep-2019 19:03:26 +0100]: <107eghbl> [01E8] S: * LIST (\HasNoChildren \Subscribed) "/" "[Gmail]/Important"
[12-Sep-2019 19:03:26 +0100]: <107eghbl> [01E8] S: * LIST (\HasNoChildren \Subscribed) "/" "[Gmail]/Sent Mail"
[12-Sep-2019 19:03:26 +0100]: <107eghbl> [01E8] S: * LIST (\HasNoChildren \Subscribed) "/" "[Gmail]/Spam"
[12-Sep-2019 19:03:26 +0100]: <107eghbl> [01E8] S: * LIST (\HasNoChildren \Subscribed) "/" "[Gmail]/Starred"
[12-Sep-2019 19:03:26 +0100]: <107eghbl> [01E8] S: A0005 OK Success
[12-Sep-2019 19:03:26 +0100]: <107eghbl> [01E8] C: A0006 UNSUBSCRIBE "[Gmail]"
[12-Sep-2019 19:03:26 +0100]: <107eghbl> [01E8] S: A0006 NO [NONEXISTENT] Folder doesn't exist (Failure)
```
It would be preferable to either have an option to change this behaviour, or alternatively inhibit the visual cue.
![roundcube_imap_error](https://user-images.githubusercontent.com/8457144/64859038-0f45ac80-d621-11e9-8634-0c9a809efac2.jpg)

**Comment by alecpl** [comment] 2019-09-13 19:40
I see the UNSUBSCRIBE command in debug log, but I don't get that error message in UI. Maybe that's already fixed somehow in git-master.

We still might want to skip the code that tries to unsubscribe the `[Gmail]` folder (if we detect this is Gmail server we're talking with).

**Comment by alecpl** [comment] 2019-09-13 19:53
And I was able to reproduce the error message when using Refresh button. That should not happen, the errors is not preventing a refresh and should not appear. So, this looks like not gmail specific issue, and should be fixed separately.

**Comment by bobpullen** [comment] 2019-09-14 00:40
Any merit in treating \HasChildren folders differently?

**Comment by alecpl** [comment] 2019-09-14 06:11
What do you mean? It's not about \HasChildren. It's about \NonExistent and \Subscribed. Roundcube unsubscribes non-existent folders. While it's allowed by IMAP standard it has not much sense to keep these. And \HasChildren have nothing to do with subscriptions, right?

**Comment by bobpullen** [comment] 2019-09-14 09:01
@alecpl understood. The [GMail] folder has child folders that _are_ existent and _are_ subscribed though. I just wondered if it was worth treating \NonExistent and \Subscribed folders differently by not attempting to unsubscribe if they have folders underneath them.

**Comment by alecpl** [comment] 2020-01-12 09:32
A workaround for this is `imap_force_lsub=true`, it's because in LSUB responses Gmail does not send the `\NonExistent` flag.

Fixed by ignoring the error on UNSUBSCRIBE call when auto-unsubscribing non-existent folders.

**Closed by alecpl** 2020-01-12 09:32 UTC
Labels: C: IMAP connection, bug
