### ISSUE TITLE
Failure to render login page after oauth failure [trunk]

### ISSUE THREAD

**Issue by trybowski** [roundcube/roundcubemail#7812] opened 2021-01-05 01:37 UTC
After oauth authorization fails (for whatever reason), the redirection to login screen kicks in. Then RCM falls into some sort of a loop, tries rendering the login page for like... 10 (?) times, and eventually I see a login page without any styles, without a message about oauth failure and the URL is ..._index.php/login/oauth?code=0.AQUAgRF8rLws8kat_...

Funny, the code many times reaches "exit" in rcmail_output_html->send but then the execution of index.php repeats. I suspect something like a js redirection bug.

**Comment by thomascube** [comment] 2021-01-05 20:42
Please provide some more information about our oauth setup. Which provider? `oauth_login_redirect` set to true?
Do you see any entries in the logs? If the authorization code cannot be turned into an access code, this should be reported in the logs.

**Comment by skug67** [comment] 2021-01-07 00:40
I'm experiencing something similar using my own Keycloak server and w/o oauth_login_redirect being set.

**Comment by thomascube** [comment] 2021-01-10 12:33
I could reproduce the problem with `oauth_login_redirect` = true and invalid credentials that will make the server-to-server request for obtaining an access token fail. That should certainly be fixed. But @trybowski @skug67 please respond to my question about messages in the logs. I'd like to find out more about the underlying reason for the behavior in order to fix it.

**Comment by skug67** [comment] 2021-01-10 13:26
Not sure how helpful this log will be, but here you go......

[roundcube-oauth-debug.txt](https://github.com/roundcube/roundcubemail/files/5792637/roundcube-oauth-debug.txt)

**Comment by thomascube** [comment] 2021-01-14 19:41
> Not sure how helpful this log will be, but here you go......

@skug67 Nothing suspicious to see in here. Could you enable [IMAP logging](https://github.com/roundcube/roundcubemail/wiki/Howto-Report-Issues#enable-debug-logging) and check what the server responds on the authentication request? Maybe your IMAP server simply rejects the access token due to wrong scopes or other reasons.

**Comment by skug67** [comment] 2021-01-14 22:34
Sorry to say, imap logging _was_ on......  And looking at the logs for the imap server, it looks like there's no attempt being made to even contact the imap server.  Do I need to fill in some imap specific setting other than default_host?

**Comment by thomascube** [comment] 2021-01-18 20:34
Strange. Basically the oauth config should include values for the following options:
- 'default_host'
- 'smtp_server'
- 'oauth_provider'
- 'oauth_provider_name'
- 'oauth_client_id'
- 'oauth_client_secret'
- 'oauth_auth_uri'
- 'oauth_token_uri'
- 'oauth_scope'

**Comment by skug67** [comment] 2021-01-18 23:07
I've got all those set....

**Comment by skug67** [comment] 2021-03-02 20:26
Not much more to add except that I was browsing old issues and I noted references in https://github.com/roundcube/roundcubemail/pull/7425#issuecomment-653071547 to Keycloak producing a different set of parameters than what Roundcube might be expecting (in particular Keycloak sending a session_state parameter but not a scope parameter).  That is definitely happening to me as well in case it might be helpful in tracking down whatever is causing the glitchy behavior.

**Comment by skug67** [comment] 2021-03-07 01:42
Took a fair bit of experimentation but here's what is now working for me with Keycloak and Dovecot

Roundcube (config.inc.php)

> $config['oauth_provider'] = 'generic';
> $config['oauth_provider_name'] = 'Keycloak';
> $config['oauth_client_id'] = "myclient";
> $config['oauth_client_secret'] = "mysecret";
> $config['oauth_auth_uri'] = "https://my.host.tld/keycloak/realms/myrealm/protocol/openid-connect/auth?";
> $config['oauth_token_uri'] = "https://my.host.tld/keycloak/realms/myrealm/protocol/openid-connect/token";
> $config['oauth_identity_uri'] = "https://my.host.tld/keycloak/realms/myrealm/protocol/openid-connect/userinfo";
> $config['oauth_scope'] = "email profile openid";
> $config['oauth_auth_parameters'] = ['access_type' => 'offline'];
> $config['oauth_identity_fields'] = ['preferred_username'];
> 

Dovecot (dovecot-oauth2.conf.ext)

> tokeninfo_url = https://my.host.tld/keycloak/realms/myrealm/protocol/openid-connect/userinfo?access_token=
> introspection_url = https://myclient:mysecret@my.host.tld/keycloak/realms/myrealm/protocol/openid-connect/token/introspect
> introspection_mode = post
>

**Comment by alecpl** [comment] 2021-03-13 07:49
@thomascube if you just access `index.php/login/oauth` without any oauth configuration the page is broken, so atleast this part is easily reproducible.

**Comment by thomascube** [comment] 2021-03-15 20:02
I see now why this always worked for me: I have set `$config['assets_path'] = '/path/to/roundcube';` in my config. With that option set, the page loaded at `/path/to/roundcube/index.php/login/oauth` renders just fine because scripts and styles are loaded with an absolute path.

**Comment by thomascube** [comment] 2021-03-15 20:27
Login page rendering fixed in git master. No feedback from @trybowski thus closing the issue.

**Closed by thomascube** 2021-03-15 20:27 UTC
Labels: need feedback
