### ISSUE TITLE
Git.kolab.org offline

### ISSUE THREAD

**Issue by uhlhosting** [roundcube/roundcubemail#9128] opened 2023-09-09 22:34 UTC
It seems the composer will fail at upgrade:

```
[root@cp roundcube]# composer update --no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file
Package operations: 0 installs, 15 updates, 19 removals
  - Downloading dasprid/enum (1.0.5)
  - Downloading symfony/deprecation-contracts (v3.3.0)
  - Downloading psr/http-message (2.0)
  - Downloading psr/http-client (1.0.2)
  - Downloading psr/http-factory (1.0.2)
  - Downloading guzzlehttp/psr7 (2.6.1)
  - Downloading guzzlehttp/promises (2.0.1)
  - Downloading guzzlehttp/guzzle (7.8.0)
  - Downloading jfcherng-roundcube/cloudview (0.6.17)
  - Downloading pear/pear-core-minimal (v1.10.13)
  - Syncing kolab/net_ldap3 (v1.1.5) into cache
    Authentication required (git.kolab.org):
      Username: 
      Password: 

In Git.php line 235:
                                                                            
  [TypeError]                                                               
  rawurlencode(): Argument #1 ($string) must be of type string, null given  
                                                                            

Exception trace:
  at phar:///.socket/php/pear/composer.phar/src/Composer/Util/Git.php:235
 rawurlencode() at phar:///.socket/php/pear/composer.phar/src/Composer/Util/Git.php:235
 Composer\Util\Git->runCommand() at phar:///.socket/php/pear/composer.phar/src/Composer/Util/Git.php:296
 Composer\Util\Git->syncMirror() at phar:///.socket/php/pear/composer.phar/src/Composer/Util/Git.php:329
 Composer\Util\Git->fetchRefOrSyncMirror() at phar:///.socket/php/pear/composer.phar/src/Composer/Downloader/GitDownloader.php:78
 Composer\Downloader\GitDownloader->doDownload() at phar:///.socket/php/pear/composer.phar/src/Composer/Downloader/VcsDownloader.php:73
 Composer\Downloader\VcsDownloader->download() at phar:///.socket/php/pear/composer.phar/src/Composer/Downloader/DownloadManager.php:223
 Composer\Downloader\DownloadManager->Composer\Downloader\{closure}() at phar:///.socket/php/pear/composer.phar/src/Composer/Downloader/DownloadManager.php:235
 Composer\Downloader\DownloadManager->download() at phar:///.socket/php/pear/composer.phar/src/Composer/Installer/LibraryInstaller.php:114
 Composer\Installer\LibraryInstaller->download() at phar:///.socket/php/pear/composer.phar/src/Composer/Installer/InstallationManager.php:277
 Composer\Installer\InstallationManager->downloadAndExecuteBatch() at phar:///.socket/php/pear/composer.phar/src/Composer/Installer/InstallationManager.php:218
 Composer\Installer\InstallationManager->execute() at phar:///.socket/php/pear/composer.phar/src/Composer/Installer.php:789
 Composer\Installer->doInstall() at phar:///.socket/php/pear/composer.phar/src/Composer/Installer.php:614
 Composer\Installer->doUpdate() at phar:///.socket/php/pear/composer.phar/src/Composer/Installer.php:288
 Composer\Installer->run() at phar:///.socket/php/pear/composer.phar/src/Composer/Command/UpdateCommand.php:247
 Composer\Command\UpdateCommand->execute() at phar:///.socket/php/pear/composer.phar/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///.socket/php/pear/composer.phar/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at phar:///.socket/php/pear/composer.phar/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar:///.socket/php/pear/composer.phar/src/Composer/Console/Application.php:382
 Composer\Console\Application->doRun() at phar:///.socket/php/pear/composer.phar/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///.socket/php/pear/composer.phar/src/Composer/Console/Application.php:145
 Composer\Console\Application->run() at phar:///.socket/php/pear/composer.phar/bin/composer:88
 require() at /.socket/php/pear/composer.phar:29

update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>...]

[root@cp roundcube]# composer dump-autoload
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? 
Generating autoload files
Generated autoload files
[root@cp roundcube]# 
```

i  believe is time to clone the repos when get back online.

**Comment by alecpl** [comment] 2023-09-10 04:48
Duplicate of #9104. Remove git.kolab.org repository reference from the composer.json file.

**Closed by alecpl** 2023-09-10 04:48 UTC
