### ISSUE TITLE
Preview pane display delay too long - RC feels sluggish

### ISSUE THREAD

**Issue by bostjan** [roundcube/roundcubemail#5199] opened 2016-04-13 15:22 UTC
When preview pane is displayed and user clicks on the email, half a second is spent waiting in order to differentiate between single and double click, and only then message preview is displayed (500ms wait + server response (100-200ms) + another 300-500ms for rendering =~ more than 1s, where 1s is roughly considered as a limit between fast enough and too slow (ref1)).

**RC preview pane therefore feels... sluggish.**

Relevant code parts:
https://github.com/roundcube/roundcubemail/blob/master/program/js/app.js#L52
https://github.com/roundcube/roundcubemail/blob/master/program/js/app.js#L1797
https://github.com/roundcube/roundcubemail/blob/master/program/js/app.js#L1819

To make RC feel fast I removed the 500ms doubleclick detection delay entirely, trading faster UX for some more HTTP requests.

I know not everyone would agree with removal of this delay entirely, so let me quickly explain how I would improve this part of RC to everyone's satisfaction.
## Improvement proposal

There are two methods of selecting messages that result in preview pane being updated:
- click on message in message list
- selecting message with up/down keys

**Click:**
With this one, I would cancel out the delay entirely. User wants to see exactly this message - if double click follows, ok, we have 2 HTTP requests instead of one, not that much of a difference.

**Keyboard select:**
Here a detection of consecutive keypresses is needed, in order to avoid excessive HTTP calls when user is rapidly skimming over msglist subjects. I would go by this logic:
- if less than kbd_seq_select_timeout (around 300ms) time has passed since last message was selected, schedule preview with delay
- otherwise, display preview immediately.

Could someone who is involved with frontend RC development comment on this?

Tnx,
b.

ref1: https://www.nngroup.com/articles/response-times-3-important-limits/

**Comment by mceyran** [comment] 2016-04-13 15:24
Why not make it configurable?

**Comment by bostjan** [comment] 2016-04-13 15:38
And the sample code:

```diff
diff --git a/program/js/app.js b/program/js/app.js
index 8fbccc4..01f7dd9 100644
--- a/program/js/app.js
+++ b/program/js/app.js
@@ -49,6 +49,8 @@ function rcube_webmail()
   this.menu_stack = [];
 
   // webmail client settings
+  this.preview_delay_select = 350;   // ms
+  this.preview_delay_click  = 0;     // ms
   this.dblclick_time = 500;
   this.message_time = 5000;
   this.identifier_expr = /[^0-9a-z_-]/gi;
@@ -1762,10 +1764,35 @@ function rcube_webmail()
       this.select_all_mode = false;
 
     // start timer for message preview (wait for double click)
-    if (selected && this.env.contentframe && !list.multi_selecting && !this.dummy_select)
-      this.preview_timer = setTimeout(function() { ref.msglist_get_preview(); }, 0);
-    else if (this.env.contentframe)
+    if (selected && this.env.contentframe && !list.multi_selecting && !this.dummy_select) {
+//      this.preview_timer = setTimeout(function() { ref.msglist_get_preview(); }, 0);
+
+      // Try to be responsive, and try not to overload the server when
+      // client is pressing up/down key repeatedly.
+      // If time between this and previous selection is less than configured delay,
+      // user is selecting messages repeatedly, wait until this ends (use larger delay).
+      // If this selection has occured after a while, display message previes immediately.
+      now = new Date();
+
+      if (null == this._last_msglist_select_time) { // First request only
+        this._last_msglist_select_time = now.getTime();
+      }
+
+      current_time = now.getTime();
+      time_diff = current_time - this._last_msglist_select_time;
+
+      if (time_diff < this.preview_delay_select) {
+        preview_pane_delay = this.preview_delay_select
+      } else {
+        preview_pane_delay = 0
+      }
+      this._last_msglist_select_time = current_time;
+
+      this.preview_timer = setTimeout(function() { ref.msglist_get_preview(); }, preview_pane_delay);
+
+    } else if (this.env.contentframe) {
       this.show_contentframe(false);
+    }
   };
 
   // This allow as to re-select selected message and display it in preview frame
@@ -1785,7 +1812,7 @@ function rcube_webmail()
       if (this.preview_read_timer)
         clearTimeout(this.preview_read_timer);
 
-      this.preview_timer = setTimeout(function() { ref.msglist_get_preview(); }, this.dblclick_time);
+      this.preview_timer = setTimeout(function() { ref.msglist_get_preview(); }, this.preview_delay_click);
     }
   }; 
```

**Comment by bostjan** [comment] 2016-04-13 15:39
@mceyran: Yes, I had that in mind too, it should be simple enough to do it.

**Comment by bostjan** [comment] 2016-04-13 15:48
Would pull request for this be based on master or 1.1 branch? Would it be merged into both, since defaults would retain previous behaviour?

**Comment by mceyran** [comment] 2016-04-13 15:48
I was kind of fast when I wrote my message, then I had the impression that it already was configurable while looking through the code, so I deleted my message since it was a mistake. But yeah, maybe it could be made configurable. Lacking good knowledge of the code, I can not imagine a comfortable way of configuring it, though.

**Comment by alecpl** [comment] 2016-04-13 15:52
I thought about this in the past and all I could figure out is that it have to be configurable. Like "Open a message on double-click" checkbox in Preferences > Mailbox View > Main options. The checkbox should be inactive (and disabled) if preview pane is enabled. Still, am not sure this is clear enough. Are there users that using preview pane would like to still be able to open the message (not in new window)?
On a code side this would probably involve changes in list.js.
PRs for master only, please.

**Comment by bostjan** [comment] 2016-04-13 16:12
@alecpl:
I think you are talking about 3 separate RC design traits:
- single click vs double click to open a message
- RC has two modes of operation (preview pane available or not) that interact with clicks differently
- message selection in mailbox list

Take Gmail for example:
- no preview pane
- message selection is not done by whole <tr> (or <li>), but with separate checkbox
- this enables them to have single click to open a message

You could only do that in RC if you disable preview pane AND make selecting messages NOT use the same area that is used for opening them.

(FTR I am not saying Gmail is better, just that they have it easier because of certain design decisions they have done in the past)

Since RC has message selection by clicking on it, it can only have either preview pane for single click, or double click to open in new window/tab/on new page.

So, I do not think you can do much about it unless certain design changes are implemented first.

Just my 2 cents.
b.

(this probably deserves another issue subject!)

**Comment by alecpl** [comment] 2016-04-13 18:01
I just wanted to point out that double-click opens a message in full window no matter if the preview pane is visible or not. And it actually may be used by preview pane users, e.g. to display a message in "full screen" that does not fit well in preview pane. I'm not saying it's good or not. It's how it works now.

**Comment by alecpl** [comment] 2016-11-01 12:33
I pushed to dev-layouts branch a change that disables double-click when preview pane is on.

**Comment by bostjan** [comment] 2016-11-02 17:38
Thumbs up! Will this be backported to 1.2.x by any chance?

**Comment by thomascube** [comment] 2016-11-06 17:42
Although it might confuse the user when double-click sometimes works and sometimes doesn't but with the preview pane one at least has the ability to open a message in a new window through the according button/icon in the preview itself. Thus, we should add merge change and see of anybody complains.

**Comment by alecpl** [comment] 2016-11-20 18:07
Merged into master.

**Closed by alecpl** 2016-11-20 18:07 UTC
Labels: C: User Interface, enhancement

**Comment by tjharman** [comment] 2017-05-03 22:29
Is this change why double clicking on a message now no longer opens it full screen?
If so, this is a very annoying regression.  Could it be made an option?

**Comment by onlime** [comment] 2017-07-06 19:25
Some of our customers start complaining about this new feature which in their eyes is a great regression. Could you introduce double click again as a user defined option? thx @thomascube for listening.
