### ISSUE TITLE
Sieve filter not being displayed

### ISSUE THREAD

**Issue by darkbasic** [roundcube/roundcubemail#9121] opened 2023-09-02 13:25 UTC
I'm using roundcube 1.4.13+dfsg.1-1~deb11u1 and the following filter is not being displayed in the web interface:

```
# rule:[Copy ML posts to Inbox if someone wrote my name]
if allof (body :text :contains ["niccol","darkbasic"], not allof (header :contains "From" ["darkbasic@domain.it", "niccolo.belli@domain.it"], anyof (exists "List-ID", exists "X-Mailing-List", exists "List-Post")))
{
    Keep;
}
```

Is the syntax wrong? Should I expect it to still work?

**Comment by f1-outsourcing** [comment] 2023-09-03 09:10
Afaik only things are shown that are 'coded'. We had someone code something for auto archiving. Annoying is that this functionality is coded in the managesieve plugin dir, so that is not to nice for upgrading.

**Comment by darkbasic** [comment] 2023-09-03 10:34
It would be nice to at least show the sieve code for not-coded functionalities, to at least know that the rule is there.

**Comment by johndoh** [comment] 2023-09-03 10:40
dupe of #8448

**Comment by f1-outsourcing** [comment] 2023-09-03 10:43
> It would be nice to at least show the sieve code for not-coded functionalities, to at least know that the rule is there.

Why would you want to see that? Roundcube is not a frontend for sieve debugging not?

**Comment by darkbasic** [comment] 2023-09-03 11:10
How talked about debugging? I could see the rule and even edit it (by simply hand editing the test).

**Comment by f1-outsourcing** [comment] 2023-09-03 12:12
Editing 'test' sieve rules manually on the fly, qualifies to me as debugging ;)

As if any webmail interface is expecting its users to even understand sieve language rules. Afaic I don't want my users to see or even touch sieve rules. 

Anyway it should be not that difficult to adapt/create a plugin that relays raw data between the sieve host.

**Comment by darkbasic** [comment] 2023-09-03 14:00
No, it qualifies as an easy to implement fallback for missing features. Obviously everybody would prefer every single sieve rule to be implemented and have a nice clean interface to show, but reality is that not all features are implemented and I'd rather allow my users to manually write their sieve rules rather than not being able to.

**Comment by alecpl** [comment] 2023-09-09 06:11
This is not a proper place to solve Sieve issues.

**Closed by alecpl** 2023-09-09 06:11 UTC

**Comment by darkbasic** [comment] 2023-09-09 08:19
@alecpl and what's the proper place to track a feature (displaying certain sieve rules) that Roundcube doesn't support?
