### ISSUE TITLE
Preferences Save button should reflect the presence of changes (that the user should save)

### ISSUE THREAD

**Issue by jidanni** [roundcube/roundcubemail#9395] opened 2024-03-23 11:08 UTC
In Preferences there is a blue Save button at the bottom.

It should look e.g., grey ("don't bother pushing me"), until there is something altered on the form which to save. Only then it should turn blue.

**Comment by alecpl** [comment] 2024-03-24 06:29
Duplicate of #5134.

**Closed by alecpl** 2024-03-24 06:29 UTC
