### ISSUE TITLE
Attachment not shown

### ISSUE THREAD

**Issue by thomasysliu** [roundcube/roundcubemail#5453] opened 2016-10-01 16:40 UTC
The attachment cannot have download link for the email below
[attachment.eml.zip](https://github.com/roundcube/roundcubemail/files/504482/attachment.eml.zip)

**Comment by alecpl** [comment] 2016-10-02 10:20
What version? I cannot reproduce with 1.2.2. There was the same issue fixed in 1.3 too (#5357).

**Comment by alecpl** [comment] 2016-10-05 17:17
????

**Comment by alecpl** [comment] 2016-10-12 06:54
No feedback.

**Closed by alecpl** 2016-10-12 06:54 UTC
Labels: need feedback
