### ISSUE TITLE
SMTP Login on port 25 with tls

### ISSUE THREAD

**Issue by BigWhoopM** [roundcube/roundcubemail#8682] opened 2022-08-20 09:23 UTC
Hi Guys,
when i write this to the config.inc it results in an error:

> $config['smtp_host'] = 'tls://xxx.xxxxxxxxxx.de:25';

The Errormessage is:
> "PHP Fatal error:  Uncaught Error: Call to undefined method Net_SMTP::starttls() in ***/program/lib/Roundcube/rcube_smtp.php:164"

**Comment by alecpl** [comment] 2022-08-23 17:54
You need more recent Net_SMTP version, i.e. 1.10.0. Normally it is in the vendor folder together with the Roundcube "complete" package and/or can be installed/updated with the composer.

If you did an upgrade then maybe this is a duplicate of #8642.

**Closed by alecpl** 2022-08-23 17:54 UTC
