### ISSUE TITLE
Managesieve: Spell ACTIVE after the active script

### ISSUE THREAD

**Issue by dilyanpalauzov** [roundcube/roundcubemail#8819] opened 2022-12-17 14:37 UTC
Currently the manage sieve script does grey out inactive scripts.  This color-based distinction is hard to perceive.

Please spell in addition `(active)` after the active script.

**Comment by alecpl** [comment] 2023-04-10 11:30
I'm closing this as a duplicate of #8523.

**Closed by alecpl** 2023-04-10 11:30 UTC
Labels: enhancement, C: User Interface, C: Plugins
