### ISSUE TITLE
PHP Error: Invalid plugin name with Roundcube 1.4.4 

### ISSUE THREAD

**Issue by Bojo78** [roundcube/roundcubemail#7397] opened 2020-05-20 17:42 UTC
After upgrading to Roundcube 1.4.4  I get the following errors in logs when I click on Help->About
```
roundcube: PHP Error: Invalid plugin name: mobiledetect/mobiledetectlib in /var/www/roundcubemail-1.4.4/program/lib/Roundcube/rcube_plugin_api.php on line 297 (GET /mail/?_task=settings&_action=about&_framed=1&_framed=1)
roundcube: PHP Error: Invalid plugin name: pear/net_sieve in /var/www/roundcubemail-1.4.4/program/lib/Roundcube/rcube_plugin_api.php on line 297 (GET /mail/?_task=settings&_action=about&_framed=1&_framed=1)
roundcube: PHP Error: Invalid plugin name: pear/crypt_gpg in /var/www/roundcubemail-1.4.4/program/lib/Roundcube/rcube_plugin_api.php on line 297 (GET /mail/?_task=settings&_action=about&_framed=1&_framed=1)
roundcube: PHP Error: Invalid plugin name: kolab/libcalendaring in /var/www/roundcubemail-1.4.4/program/lib/Roundcube/rcube_plugin_api.php on line 297 (GET /mail/?_task=settings&_action=about&_framed=1&_framed=1)
roundcube: PHP Error: Invalid plugin name: kolab/libkolab in /var/www/roundcubemail-1.4.4/program/lib/Roundcube/rcube_plugin_api.php on line 297 (GET /mail/?_task=settings&_action=about&_framed=1&_framed=1)
roundcube: PHP Error: Invalid plugin name: kolab/libkolab in /var/www/roundcubemail-1.4.4/program/lib/Roundcube/rcube_plugin_api.php on line 297 (GET /mail/?_task=settings&_action=about&_framed=1&_framed=1)
roundcube: PHP Error: Invalid plugin name: kolab/libcalendaring in /var/www/roundcubemail-1.4.4/program/lib/Roundcube/rcube_plugin_api.php on line 297 (GET /mail/?_task=settings&_action=about&_framed=1&_framed=1)
roundcube: PHP Error: Invalid plugin name: kolab/libkolab in /var/www/roundcubemail-1.4.4/program/lib/Roundcube/rcube_plugin_api.php on line 297 (GET /mail/?_task=settings&_action=about&_framed=1&_framed=1)
roundcube: PHP Error: Invalid plugin name: sabre/vobject in /var/www/roundcubemail-1.4.4/program/lib/Roundcube/rcube_plugin_api.php on line 297 (GET /mail/?_task=settings&_action=about&_framed=1&_framed=1)
roundcube: PHP Error: Invalid plugin name: pear/http_request2 in /var/www/roundcubemail-1.4.4/program/lib/Roundcube/rcube_plugin_api.php on line 297 (GET /mail/?_task=settings&_action=about&_framed=1&_framed=1)
roundcube: PHP Error: Invalid plugin name: caxy/php-htmldiff in /var/www/roundcubemail-1.4.4/program/lib/Roundcube/rcube_plugin_api.php on line 297 (GET /mail/?_task=settings&_action=about&_framed=1&_framed=1)
roundcube: PHP Error: Invalid plugin name: caxy/php-htmldiff in /var/www/roundcubemail-1.4.4/program/lib/Roundcube/rcube_plugin_api.php on line 297 (GET /mail/?_task=settings&_action=about&_framed=1&_framed=1)
```

**Comment by alecpl** [comment] 2020-05-20 19:24
Duplicate of #7364.

**Closed by alecpl** 2020-05-20 19:24 UTC
