### ISSUE TITLE
Images copied from another mail and pasted into new mail not received by recepient

### ISSUE THREAD

**Issue by brandelf68** [roundcube/roundcubemail#8196] opened 2021-09-02 10:45 UTC
Hello,

Images are not shown if message was composed with images pasted from clipboard after copy to clipboard from another message in Roundcube.
In problem mail body source we will see hyperlink image:
```html
<p><img src=3D"https://roundcube.host.local/roundcube/?_task=3Dmail&amp;_a=
ction=3Dget&amp;_mbox=3DINBOX&amp;_uid=3D324081&amp;_token=3D4hpK8ZcvriXeka=
isNB7JobHaXQSD7XMH&amp;_part=3D2.2&amp;_embed=3D1&amp;_mimeclass=3Dimage" /=
></p>
```
Thus, for another user on same Roundcube instance or another mail client when opened this message image on this link not accessed with code 404.
Also this bug reproduced in another Roundcube instance with non-stock plugins off.
Roundcube version 1.4.11
PHP 7.2.4
Nginx 1.18

**Comment by alecpl** [comment] 2021-09-02 10:55
Duplicate of #6938.

**Closed by alecpl** 2021-09-02 10:55 UTC
