### ISSUE TITLE
release-1.3: PHP 7.2 Warning: exif_read_data: Illegal IFD size

### ISSUE THREAD

**Issue by quicktrick** [roundcube/roundcubemail#6165] opened 2018-02-07 09:11 UTC
Branch: release-1.3

    Feb 01 21:45:48 mail roundcube[2120]: PHP Warning:  exif_read_data(d22b0a43332840a26c237f5acedebc9e.tmp): Illegal IFD size: 2 + 0x0E00*12 = 0xA802 &gt; 0x0100 in /srv/www/mydomain.tld/roundcubemail/program/lib/Roundcube/rcube_image.php on line 261

**Comment by alecpl** [comment] 2018-02-11 10:03
Duplicate of #6169

**Closed by alecpl** 2018-02-11 10:03 UTC
