### ISSUE TITLE
Attached JPEG image does not appear

### ISSUE THREAD

**Issue by conathan** [roundcube/roundcubemail#9147] opened 2023-09-20 06:05 UTC
We have a client who reported that a jpeg image he emailed to himself did not show up as an attachment in roundcubemail.  Tested on 1.6.2 and 1.6.3

This attachment appears in Outlook and Thunderbird
![roundcube_noimage](https://github.com/roundcube/roundcubemail/assets/2858011/bc8ce539-314d-421c-ac9d-2f898885474d)
I am expecting there to also be a Attach1.jpg.

[158813.eml.txt](https://github.com/roundcube/roundcubemail/files/12669106/158813.eml.txt)
* Uploading as a text file, as eml was not a valid filetype for github
* Modified from original to remove client information

**Comment by alecpl** [comment] 2023-09-20 06:30
Duplicate of #8870.

**Closed by alecpl** 2023-09-20 06:30 UTC

**Comment by conathan** [comment] 2023-09-20 06:55
Regarding duplicate of, This was also a email from vzwpix.com.
