### ISSUE TITLE
implement oauth authentication for managedsieve

### ISSUE THREAD

**Issue by ibotty** [roundcube/roundcubemail#8019] opened 2021-04-21 11:13 UTC
It would be great to also support oauth authentication with managesieve plugin.

**Comment by alecpl** [comment] 2021-04-21 11:17
Duplicate of #7925.

**Closed by alecpl** 2021-04-21 11:17 UTC

**Comment by ibotty** [comment] 2021-04-21 11:18
strange why my issues search did not find this issue.  Sorry for the noise!
