### ISSUE TITLE
Duplicated signature when using Back button in Chrome

### ISSUE THREAD

**Issue by uli-heller** [roundcube/roundcubemail#5809] opened 2017-06-21 09:06 UTC
I'm using roundcube-1.2.5.

Sometimes, the signature gets duplicated:

1. Start entering a new message
2. Select "Change Sender" ("Absender ändern")
3. Somehow, I'm stuck on this. There is no easy way to get back to the message :(
    Maybe this is worth another ticket?
4. So: I click on "browser - back"
5. Now the message shows up again, but the signature is in there twice

![image](https://user-images.githubusercontent.com/1677414/27376180-ae2886b0-5671-11e7-9c46-1c43aaab0d93.png)

**Comment by alecpl** [comment] 2017-06-21 09:11
What do you mean you're stuck in 3 exactly? Any errors? Did you try with disabled all plugins? Provide your settings from Preferences > Composing Messages? I feel this may be related to the fact you're using non-standard signature separator.

**Comment by uli-heller** [comment] 2017-06-21 09:20
> What do you mean you're stuck in 3 exactly? Any errors? 

No, no errors. The browser window changes, it looks like a settings windows.
There is no "button" that leads back to the original message.

> Did you try with disabled all plugins?

No. I explicitely activated the managesieve plugin only. I can try again if it helps.

> Provide your settings from Preferences > Composing Messages?

![image](https://user-images.githubusercontent.com/1677414/27376722-5185a90e-5673-11e7-9faa-b06ccf31ee36.png)

>  I feel this may be related to the fact you're using non-standard signature separator.

I've change it to "-- ", but no improvements.

Thanks for taking the time + best regards, Uli

**Comment by uli-heller** [comment] 2017-06-21 09:24
I tried again without specifying a signature separator. Roundcube seems to add it automagically.
But: Still a duplicate signature.

**Comment by alecpl** [comment] 2017-06-21 09:32
Ok, I get it. First, there's localization issue the "Absender ändern" link is "Edit identities" in English version. So, it takes you to the identities settings correctly. If you want to change the sender, just select it, don't use the link.

Anyway, I'm not able to reproduce the issue when using Back button in the browser. What browser are you using?

**Comment by uli-heller** [comment] 2017-06-21 09:42
> Ok, I get it. First, there's localization issue the "Absender ändern" link is "Edit identities" in English version.

Sorry for that. I switched the UI language to English now.

> So, it takes you to the identities settings correctly. If you want to change the sender, just select it, don't use the link.

Selecting the sender works. I clicked on the link because I wanted to enter an ad-hoc identity like
uli.heller+1234@... I see this is not possible there, no problem. So it is a bad idea to use the link.

And I see: When I entered something in the message area, a popop shows up before changing into the settings dialog. This is good, so I will not lose lots of input.

> Anyway, I'm not able to reproduce the issue when using Back button in the browser. What browser are you using?

I'm using google chrome. I double-checked with firefox: no issue, the signature shows up just once.

Proposal: Let's close the issue? It is a very minor problem...

**Comment by alecpl** [comment] 2017-06-21 09:48
Ok. I can reproduce using Chromium. Will see what we can do about it.

**Comment by uli-heller** [comment] 2017-06-21 10:00
Thanks a lot, I'm happy ;)

**Comment by alecpl** [comment] 2017-06-21 17:47
Ok. Looks like we might need a political decision here. Do we want to keep Chrome's behavior of using previous content on Back-to-compose or not. If not, this could be fixed this way:
```
--- a/program/js/app.js
+++ b/program/js/app.js
@@ -4187,6 +4187,11 @@ function rcube_webmail()
     }                                                                                                                                                
                                                                                                                                                      
     if (!html_mode) {                                                                                                                                
+      // On Back button Chrome will overwrite textarea with old content                                                                              
+      // causing e.g. the same signature is added twice (#5809)
+      if (input_message.value && input_message.defaultValue !== undefined)
+        input_message.value = input_message.defaultValue;
+
       pos = this.env.top_posting && this.env.compose_mode ? 0 : input_message.value.length;
 
       // add signature according to selected identity
```
In the other case we'd need to modify rcube_text_editor.change_signature() to remove signature from the content, by looping over all signatures instead of using only the current one (this is needed because we don't know which signature was inserted to the content).

**Comment by rmcaninch** [comment] 2017-06-22 20:21
I like your approach. (If I'm understanding correctly). I would expect an empty compose window with default signature the same as if I just hit the compose button in the top navigation menu.

Normally I would use the compose navigation button and not use the browser back button, as I'm accustomed to the browser back button breaking stuff in web applications (maybe that's showing my age as they seem to do better these days).

**Comment by alecpl** [comment] 2017-06-28 06:52
@thomascube your opinion?

**Comment by alecpl** [comment] 2017-07-13 14:13
Fixed with the proposed patch.

**Closed by alecpl** 2017-07-13 14:13 UTC
Labels: bug, C: User Interface
