### ISSUE TITLE
Progressive Web App (PWA)

### ISSUE THREAD

**Issue by 532910** [roundcube/roundcubemail#7710] opened 2020-11-04 11:17 UTC
What about webapp support. Like Discourse for example.

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps
https://developer.mozilla.org/en-US/docs/Web/Manifest

**Comment by alecpl** [comment] 2020-11-04 11:28
Duplicate of #6510.

**Closed by alecpl** 2020-11-04 11:28 UTC
