### ISSUE TITLE
[FR] Delete button on mouse hover, when hovering on mail in mail list view

### ISSUE THREAD

**Issue by Offerel** [roundcube/roundcubemail#7934] opened 2021-03-11 08:24 UTC
Currently there is a "mark as important" button, when the mouse hovers a mail in the mail list view
![image](https://user-images.githubusercontent.com/14041522/110757020-3186ad80-824b-11eb-97a5-cdb5b11cc3d4.png)

Is it possible to have also a delete button? I know this could be problematic, because of the limitation in space and maybe not that touch friendly, but in most other mail guis like gmail or outlook.com such a button exists. Would be nice to have this here to.

Maybe, we can have an option in the settings, to specify what buttons we can have as a sort of "quick buttons". But this only an personal idea. I don't know if this could be implemented in an easy way.

**Comment by alecpl** [comment] 2021-03-11 08:49
Duplicate of #7141.

**Closed by alecpl** 2021-03-11 08:49 UTC
