### ISSUE TITLE
'Enigma' Plugin Provides No Way (or documentation) For Creating ecdsa / ed25519 keys

### ISSUE THREAD

**Issue by Librechain** [roundcube/roundcubemail#7473] opened 2020-07-06 06:19 UTC
## This is an Urgent Issue (Not Exaggerating) 

Perhaps I've missed it (doubtful), but I'm mystified as to how one would configure the Enigmail plugin so that it will provide more options other than the two default ones (RSA2048 / 4096). 

It doesn't seem apparent in Enigma's documentation how one would go about doing this either - which I find to be extremely strange (given that we're now halfway through 2020). 

### Questioning the Reason for the Lack of Support For Various Algorithmic Keys 

At this point, there is no justification for not providing this option by default. 

But if you need justification for **why you should**, please look no further than below: 

1. OpenPGP standards accept up to ed25519 keys (compliance isn't an issue) 

2. GPG 2+ library has long since provided support for ed25519 - so has OpenSSL 

3. Mailvelope (an additional add-on which Enigmail boasts they're compatible with) provides users with the option to create PKI using the ed25519 algorithm. 

### Does Enigma Want its Users to Be Secure? 

Perhaps I am being presumptuous here - but it seems that Enigma / Enigmail serve no function other than to provide a unique, convenient and **useful** interface to e-mail encryption, signing and authentication (for recipients). 

So operating on the idea that this is essentially the **sole premise of the project**, it seems unconscionable to me that in its decade+ life span, that the maintainer has **never even considered updating the algorithms since its inception**. 

## Until a PR is Made Addressing This - There's No Reason Why Anyone Should Trust Enigma / Enigmail 

If there's one thing that a community should scrutinize, it should be a developer's unwillingness to make decisions that would clearly be for the benefit of the community. 

Hopefully no more runaround answers / responses are given that don't address the glaring issue here - which is that Enigmail is **purposefully restricting users from creating stronger GPG **.

**Comment by alecpl** [comment] 2020-07-06 06:24
Duplicate of #6853. Pull requests welcome.

**Closed by alecpl** 2020-07-06 06:24 UTC
