### ISSUE TITLE
Threading for github mail doesn't work

### ISSUE THREAD

**Issue by HLeithner** [roundcube/roundcubemail#6379] opened 2018-08-05 17:42 UTC
It seams that RC doesn't group messages for github mails.

Github uses 'References' header ex.

```References: <joomla/joomla-cms/pull/21306@github.com>```

Should this work?

![image](https://user-images.githubusercontent.com/1497730/43688366-a0dc6efe-98e7-11e8-864f-70b124978977.png)

tested with last weeks git version.

**Comment by alecpl** [comment] 2018-08-06 07:11
What IMAP server? We depend on imap server response to threads command, so it would be a server issue. Enable imap_debug in Roundcube to see imap conversation in logs.

**Comment by HLeithner** [comment] 2018-08-06 08:39
We use Dovecot 2.2.31, but I think I found the problem.

THREAD gives (39294 39296 39295) for 3 messages that are working see log file.

For the not working example I get
((39338)(39339))

So the parser seams to be unable to handle THREADs which doesn't start with an empty bracket.

https://github.com/roundcube/roundcubemail/blob/cb53f46d10fd87caf5db8dc2a0bd01cb0d668913/program/lib/Roundcube/rcube_result_thread.php#L565-L648

I will try to solve the problem, but if you are faster I would appreciate.

I think that are the important parts of the imap log:

```
[06-Aug-2018 10:11:53 +0200]: <d985bd13> [E9CA] C: A0003 CAPABILITY
[06-Aug-2018 10:11:53 +0200]: <d985bd13> [E9CA] S: * CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVE
L=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE NOTIFY COMPRESS=DEFLATE QUOTA ACL RIGHTS=texk
[06-Aug-2018 10:11:53 +0200]: <d985bd13> [E9CA] S: A0003 OK Capability completed (0.001 + 0.000 secs).


[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] C: A0003 SELECT INBOX
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft Junk $Forwarded shortcircuit $label4 $label3 $label1 $label2 $label5 $NotJunk $Junk)
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft Junk $Forwarded shortcircuit $label4 $label3 $label1 $label2 $label5 $NotJunk $Junk \*)] Flags permitted.
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: * 484 EXISTS
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: * 0 RECENT
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: * OK [UNSEEN 8] First unseen.
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: * OK [UIDVALIDITY 1457553573] UIDs valid
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: * OK [UIDNEXT 39342] Predicted next UID
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: * OK [HIGHESTMODSEQ 118181] Highest
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: A0003 OK [READ-WRITE] Select completed (0.001 + 0.000 secs).
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] C: A0004 UID THREAD REFS US-ASCII ALL
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: * THREAD (16380 16381)(16392 16393)(16400)(16464)(16098)(17844)(17947)(20079)(21660)(21697)(21773)(21785)(22216)(22457)(23261)(21644 21646 23503 23630 23644)(23757)(23763)(24051)(24092)(24842)(24904 24944)(24955)(25356)(25408)(25734
)(25984)(26104)(26210)(26667)((26748)(26764))(26775)(26786)(26821)((25328 25363 (25365)(26846 26917))(26910 26912 26918 26936 26981 26992))(27148)(27687)(27741)(27779 27791 28026)(28081)(28104)(28219)(28327 28359)(28417)(28419)(28530)(28548)(28618)(28634)(28809)(28828)(28830)(28957)
(29036)(29138)(29147)(29214)((23046)(23047 (23048)(23049 23050 23051 23052 23053))(29243))(29001 29282)(29314)(29315)(29317)(29323)(29325)(29324)(29330)(29333)(29334)(29335)(29065 29336)(29350)(29219 29362)(29385)(29387)(29340 29377 29417)(29468)(29472)(29501)(29536)(29549)(29568)(2
9583)(29640)(29723 29730)(29755)(29821)(29849)(29852)(29897)((29898)(29899))(29937)(29809 29953)(29954)(29956)(29955 29958)(29900)((29886)(30015)(30022))(30053)(29725 30004 30055 30056)(30057)(30084)(30098)(30112)(30114)(30275)(30316)(30376)(30377)(30381)(29584 29940 30487)(30489)(3
0524)(30525 30531)(30535)(30554)((30439)(30581))(30609)(30619)(30643)(30651)(30574 30656)(30667)(30509 30684)(30688)(30407 30694)(30744)(30786)(30788)(30791)(30685 (30697 (30699 30706 30784)(30735))(30797 (30801)(30835 30849)))(30600 30753 30756 30889)(30007 30897)(30900)(27222 2722
5 27231 27236 (27242)(27243 27260 (27263 28631 (28673 28973)(30438 (30442)(30443 30909)))(28524 28632 28662)))(30843 30917)(30933)(30954)(30967)(30999)(31027)(31043)(31057)(31094)(31105)(31106)(31107)(31104 31128)(31134)(31102 (31109)(31110 31136))(31142)(31149)(31150)(31233)(31387)
(31396)(31397)(31419)(31539)(31541)(31542)(31543)(31197 31472 31554 31556 31557)(31558 31565)(31571)(31593)(31635 31668)(31709 31711)(31778)(31832)(31850)(31870)(31872)(31931)(31938 31986)(31990)(31937 31999)(32090)(32110)(32131)(32260)(32286)(32345)(32346)(32361)(32433)(32483)(3251
5)(32879)(32923)(32936)(32990)(28418 29250 29686 30136 30144 30375 33065)(33194 33195 33196)(33213)(33220)(33179 33231)(33055 33239)(33240)(33277)(33253 33257 33334 33335 33339)(33503)(33504)(33512)(33661)(32469 33560 33592 33642 33672 33674 33675)(33680)(33710)(33736)(33765)(34369)
(34463)(34534)(34535)(34536)(34730)(34754)(32180 (33237)(33268)(33591 33676 34759))(34816)(28492 34824)(34861)(35020)(34873 (34895)(34939)(34946))(34956)((34994)(34995))(34976)(34982)(34986)(34992)(35028)(35054)(35089)(35138)(35146)(35177)(35277)(35279)(35280)(35285)(35330)(35342)(3
5343)(34896 34998 35401 35412)(35488)(35929)(35945 35947 35949 35956)(36084)((36253)(36254))(36288)(36334)(36384)(33771 33895 34689 34696 36453)(36510)((30707)(30708 (30795)(30796 31235 31236 36451 36516)))(36520)(36522)(36530)(36809)(36975)(36972 36986)(37324)(37414)((37606)(37607)
)(37629)(37644)(37640)(37679)(37776)(37832)(37833)(37834)(34633 37614 37844)(37854)(37980)(38055)(38058)(38056 38060)(38062)(38057 38063)(38074)(38067)(38077)((38083)(38084))(38061 38082 38085)(38089)(38095)(38090)(38091)(38092)(38111)(38140)(38166 38177)(38184)(38198)(38286)(38276
38301)(38312)(38603)(38257 38530 38633)(38656)(38794)(38815 38817)(38846)(38856)(38862)(38938)(38980)(39225)((39246)(39247))(39250)(39264)(39265)(39266)(39267)(39294 39296 39295)(39325)(39332)(39333)((39334)(39335))(39336)(39337)((39338)(39339))(39340)(39341)
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: A0004 OK Thread completed (0.006 + 0.000 + 0.005 secs).

[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: * 471 FETCH (UID 39294 RFC822.SIZE 22294 FLAGS (\Deleted \Seen) INTERNALDATE "05-Aug-2018 22:20:59 +0200" BODY[HEADER.FIELDS (DATE FROM TO SUBJECT CONTENT-TYPE CC REPLY-TO LIST-POST DISPOSITION-NOTIFICATION-TO X-PRIORITY)] {478}
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: From: Gedare Bloom <gedarebloom@gmail.com>
Date: Sun, 5 Aug 2018 09:17:27 -0400
Subject: Re: [GSoC Mentors] Work product format
To: Thomas Levine <thomas.levine@gmail.com>
Cc: GSoC Mentors <google-summer-of-code-mentors-list@googlegroups.com>
Content-Type: multipart/alternative; boundary="00000000000033079b0572affc7f"
List-Post: <https://groups.google.com/group/google-summer-of-code-mentors-list/post>,
 <mailto:google-summer-of-code-mentors-list@googlegroups.com>


[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: )
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: * 472 FETCH (UID 39295 RFC822.SIZE 20286 FLAGS (\Deleted \Seen) INTERNALDATE "05-Aug-2018 22:21:01 +0200" BODY[HEADER.FIELDS (DATE FROM TO SUBJECT CONTENT-TYPE CC REPLY-TO LIST-POST DISPOSITION-NOTIFICATION-TO X-PRIORITY)] {478}
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: From: Gedare Bloom <gedarebloom@gmail.com>
Date: Sun, 5 Aug 2018 12:48:12 -0400
Subject: Re: [GSoC Mentors] Work product format
To: Thomas Levine <thomas.levine@gmail.com>
Cc: GSoC Mentors <google-summer-of-code-mentors-list@googlegroups.com>
Content-Type: multipart/alternative; boundary="000000000000efd3fd0572b2eda3"
List-Post: <https://groups.google.com/group/google-summer-of-code-mentors-list/post>,
 <mailto:google-summer-of-code-mentors-list@googlegroups.com>


[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: )
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: * 473 FETCH (UID 39296 RFC822.SIZE 17433 FLAGS (\Deleted \Seen) INTERNALDATE "05-Aug-2018 22:21:12 +0200" BODY[HEADER.FIELDS (DATE FROM TO SUBJECT CONTENT-TYPE CC REPLY-TO LIST-POST DISPOSITION-NOTIFICATION-TO X-PRIORITY)] {444}
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: From: Thomas Levine <thomas.levine@gmail.com>
To: Gedare Bloom <gedarebloom@gmail.com>
Cc: GSoC Mentors <google-summer-of-code-mentors-list@googlegroups.com>
Content-Type: text/plain; charset="UTF-8"
Subject: Re: [GSoC Mentors] Work product format
Date: Sun, 05 Aug 2018 13:30:47 +0000
List-Post: <https://groups.google.com/group/google-summer-of-code-mentors-list/post>,
 <mailto:google-summer-of-code-mentors-list@googlegroups.com>


[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: )











[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: * 481 FETCH (UID 39338 RFC822.SIZE 6805 FLAGS (\Deleted \Seen shortcircuit) INTERNALDATE "06-Aug-2018 09:25:33 +0200" BODY[HEADER.FIELDS (DATE FROM TO SUBJECT CONTENT-TYPE CC REPLY-TO LIST-POST DISPOSITION-NOTIFICATION-TO X-PRIORITY
)] {706}
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: Date: Mon, 06 Aug 2018 00:25:31 -0700
From: Aleksander Machniak <notifications@github.com>
Reply-To: roundcube/roundcubemail <reply+0016da82ec2fce29137ffe61024c98aad5e56ecc4f9d879392cf00000001177fb9eb92a169ce14b9bc74@reply.github.com>
To: roundcube/roundcubemail <roundcubemail@noreply.github.com>
Cc: Harald <leithner@itronic.at>,
 Author <author@noreply.github.com>
Subject: Re: [roundcube/roundcubemail] [Elastic] Delete button position
 (#6378)
Content-Type: multipart/alternative;
 boundary="--==_mimepart_5b67f7ebe1358_83d3fe6c1ad45c03613c";
 charset=UTF-8
List-Post: <mailto:reply+0016da82ec2fce29137ffe61024c98aad5e56ecc4f9d879392cf00000001177fb9eb92a169ce14b9bc74@reply.github.com>


[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: )
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: * 482 FETCH (UID 39339 RFC822.SIZE 7818 FLAGS (\Deleted \Seen shortcircuit) INTERNALDATE "06-Aug-2018 09:25:33 +0200" BODY[HEADER.FIELDS (DATE FROM TO SUBJECT CONTENT-TYPE CC REPLY-TO LIST-POST DISPOSITION-NOTIFICATION-TO X-PRIORITY
)] {707}
[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: Date: Mon, 06 Aug 2018 00:25:31 -0700
From: Aleksander Machniak <notifications@github.com>
Reply-To: roundcube/roundcubemail <reply+0016da82ec2fce29137ffe61024c98aad5e56ecc4f9d879392cf00000001177fb9eb92a169ce14b9bc74@reply.github.com>
To: roundcube/roundcubemail <roundcubemail@noreply.github.com>
Cc: Harald <leithner@itronic.at>,
 Author <author@noreply.github.com>
Subject: Re: [roundcube/roundcubemail] [Elastic] Delete button position
 (#6378)
Content-Type: multipart/alternative;
 boundary="--==_mimepart_5b67f7ebb5540_73223fd65f2be6282782e";
 charset=UTF-8
List-Post: <mailto:reply+0016da82ec2fce29137ffe61024c98aad5e56ecc4f9d879392cf00000001177fb9eb92a169ce14b9bc74@reply.github.com>


[06-Aug-2018 10:11:54 +0200]: <d985bd13> [0B45] S: )
```

**Comment by alecpl** [comment] 2018-08-06 08:52
`((1)(2))` can't be displayed as one thread because there's no parent message to connect with. So, it's not only about parsing, but also displaying. It will be not simple to implement.

**Comment by alecpl** [comment] 2018-08-06 08:55
This is actually a duplicate of #4999.

**Closed by alecpl** 2018-08-06 08:55 UTC
Labels: need feedback

**Comment by HLeithner** [comment] 2018-08-06 10:33
I created a possible fix for this. https://github.com/roundcube/roundcubemail/issues/6379
