### ISSUE TITLE
Bug with interpunction in urls

### ISSUE THREAD

**Issue by thomascube** [roundcube/roundcubemail#6812] opened 2019-06-20 06:09 UTC
When typing an url and adding a comma, it is taken into account in the url :

www.test.com,

When one than removes the comma, it is still part of the real hyperlink, so one needs to modify it using ctrl+k.

[submitted via email]

**Comment by thomascube** [comment] 2019-06-20 06:10
This is observable in HTML composition mode and is likely an issue of TinyMCE.

**Comment by thomascube** [comment] 2019-06-20 06:13
We might consider to disable url conversion (`convert_urls` option) or try to catch the cases using `urlconverter_callback`.

**Comment by alecpl** [comment] 2019-06-20 06:27
I'm unable to reproduce. What are the precise steps? Did you try that on https://www.tiny.cloud? maybe it's fixed in TinyMCE5.

**Comment by alecpl** [comment] 2019-10-01 08:25
@thomascube, ping.

**Comment by thomascube** [comment] 2019-10-01 11:02
Still reproducible with 1.4RC2 (Firefox on Mac). Same on www.tiny.cloud.
However, I tried a bit with `urlconverter_callback` but that doesn't seem to be a working approach. Maybe we should just report this to TinyMCE.

**Comment by alecpl** [comment] 2019-10-01 11:42
Tried again and now I can reproduce. Looks like a bug in autolink plugin of TinyMCE. I searched on https://github.com/tinymce/tinymce/issues and didn't find a similar issue, so we should create a ticket there.

I guess, disabling the plugin is not really a solution.

**Comment by alecpl** [comment] 2019-11-18 11:50
I created https://github.com/tinymce/tinymce/issues/5263. There's not much we can do.

**Closed by alecpl** 2019-11-18 11:50 UTC
Labels: need feedback
