### ISSUE TITLE
Links without defined protocol are replaced with ./#NOP on message content

### ISSUE THREAD

**Issue by lucasmarin** [roundcube/roundcubemail#7454] opened 2020-06-25 23:43 UTC
Links without protocol on href attribute on "A" html tag are replaced with ./#NOP on the message view

A message with this html content:

```
<html><head><meta http-equiv=3D"Content-Type" content=3D"text/html; charset=
=3DUTF-8" /></head><body style=3D'font-size: 10pt; font-family: Verdana,Gen=
eva,sans-serif'>
<div><a href=3D"www.lalala.com.br">teste</a></div>
<div>&nbsp;</div>
<div>&nbsp;</div>
<div>&nbsp;</div>
<div><br />
</div>
</body></html>
```

is replaced by:

```
<div class="rcmBody" style="font-size: 10pt; font-family: Verdana,Geneva,sans-serif">
<div><a href="./#NOP" onclick="return false" rel="noreferrer">teste</a></div>
<div>&nbsp;</div>
<div>&nbsp;</div>
<div>&nbsp;</div>
</div>
```

Examples of messages with this behaviour

[teste1.eml](https://skybox.skymail.net.br/s/YeyuLMS9dBWmkKH/download)
[teste2.eml](https://skybox.skymail.net.br/s/kCdiTLCj1Fu7nFX/download)

I tested on gmail, hotmail and outlook and the protocol http:// is inserted on link.

RC Version: 1.4.6

**Comment by smares** [comment] 2020-06-26 06:14
Duplicate of #7413

**Comment by alecpl** [comment] 2020-06-26 06:33
This is not exactly a duplicate. In git-master the href is removed. Maybe we could be smarter and allow "safe" href values in such cases. I'm not sure we should add the protocol prefix.

In Thunderbird the link looks like a link, but does not work, i.e. it does not add http:// to the href.

**Comment by alecpl** [comment] 2020-07-29 13:19
Fixed.

**Closed by alecpl** 2020-07-29 13:19 UTC
Labels: C: Mail view, bug
