### ISSUE TITLE
Limit the number of new emails and delete old ones

### ISSUE THREAD

**Issue by zxcvqwerasdf** [roundcube/roundcubemail#7947] opened 2021-03-15 20:32 UTC
What's the best method to do it?
Maybe there is complete plugin or whatever?
I need to limit new emails and if it number reached => delete oldest.
Like i set limit to 50.
There is new the 51th emails, i need to delete one of the oldest, if there is 55 emails, i need delete 5 oldest and etc.
Thank you.

**Comment by alecpl** [comment] 2021-03-16 11:46
Sounds like a retention policy, so a duplicate of #5029.

**Closed by alecpl** 2021-03-16 11:46 UTC
