### ISSUE TITLE
Enhancement: Group messages on the list in the Outlook manner: today, yesterday, this week and so on.

### ISSUE THREAD

**Issue by Skygge666** [roundcube/roundcubemail#6221] opened 2018-03-21 12:04 UTC
My users often ask me a question if Roundcube has a feature to group messages on the list in the MS Outlook style: "Today", "Yesterday", "This week" and so on.
I spent some time on searching plugin for this, but I found nothing, so my duty is to ask for this feature here. :)
Thanks!
Skygge

**Comment by alecpl** [comment] 2018-03-21 14:18
Duplicate of #4990.

**Closed by alecpl** 2018-03-21 14:18 UTC
