### ISSUE TITLE
Elastic: Menu disappears if i download an attachment

### ISSUE THREAD

**Issue by danielh84** [roundcube/roundcubemail#6677] opened 2019-03-12 18:30 UTC
in the normal elastic layout you have an menü 

![image](https://user-images.githubusercontent.com/19638140/54225454-ffc39a80-44fb-11e9-9fbb-d84c71ac8c9d.png)

if you open a message with an attachement and download the attachement the menu disappears. Changing to another message will not show the menu again. you have to create a new mail and then go back to your mails. 

Tested with php 7.0 and php 7.2. (Roundcube 1.4-RC1)

**Comment by alecpl** [comment] 2019-03-13 07:41
I cannot reproduce. The whole menubar disappears or only its content (buttons)? What browser? Any errors in browser console?

**Comment by alecpl** [comment] 2019-03-13 09:06
Ok, I see it happens in Chrome 72. It looks like this version brings a lot of flexbox issues. I.e.  https://bugs.chromium.org/p/chromium/issues/detail?id=927066. This one however, is not yet fixed in developers version.

**Comment by madsinamsterdam** [comment] 2019-03-13 09:16
Chrome: 73.0.3683.75 (Official Build) (64-bit) (Fedora 29)
The menu does not disappear when downloading the attachment.

**Comment by alecpl** [comment] 2019-03-13 09:32
I've been testing 74.0.3724.8 from the Dev channel and the issue is reproducible there.

**Comment by danielh84** [comment] 2019-03-14 11:53
ok, you are right. it seems to be a chrome-only bug (Firefox works fine).
but i also use Chrome Version 73.0.3683.75 (Offizieller Build) (64-Bit) and it does not work.

it disappears if you click on this button:
![image](https://user-images.githubusercontent.com/19638140/54354950-2565b680-4658-11e9-8dac-b1fa6c9d3d7d.png)

**Comment by alecpl** [comment] 2019-03-18 12:55
I've found a workaround. Fixed.

**Closed by alecpl** 2019-03-18 12:55 UTC
Labels: C: User Interface, bug
