### ISSUE TITLE
Apply new filter to inbox

### ISSUE THREAD

**Issue by LadyAleena** [roundcube/roundcubemail#7656] opened 2020-10-04 22:02 UTC
I would like to create filters and then apply them to the messages in the inbox as well as all incoming new email messages. New filters are only applied to new incoming messages currently.

Roundcube Webmail 1.0.7 (not by choice)
Firefox 68.11.0esr (64-bit)
Debian 10

**Comment by alecpl** [comment] 2020-10-05 07:57
Duplicate of #6787.

**Closed by alecpl** 2020-10-05 07:57 UTC
