### ISSUE TITLE
Compact: better ask for confirmation

### ISSUE THREAD

**Issue by jidanni** [roundcube/roundcubemail#9004] opened 2023-05-07 03:18 UTC
Here the user sees the friendly looking Compact button, 
![Screenshot_20230507_093405_Chrome Beta.jpg](https://user-images.githubusercontent.com/1230959/236655673-3beea3d1-124b-4e96-965b-8ac2180c50c7.jpg)

He thinks, "Oh,  Compact! I get it. Just like in Gmail!",

![Screenshot_20230507_094226_Gmail.jpg](https://user-images.githubusercontent.com/1230959/236655736-d5187627-1ab5-4c5d-9f4e-83a36298c0bf.jpg)

Little does he imagine, it actually involves **deleting things**!

Sure, you might argue, "Well it's not deleting a lot of things... Just a few things.. or maybe no things.. "

But there still needs to be a dialogue. A dialogue that asks the user if he knows what he's doing, and is if he's prepared to actually delete {insert number here} things!

**Comment by jidanni** [comment] 2023-05-07 03:22
(P. S., you might be curious why my first image is skewed to the side. Well it's because I increased the font size in my Android settings and a Certain Program couldn't deal with it properly.)

**Comment by alecpl** [comment] 2023-05-07 06:37
I don't think we need a confirmation dialog, but maybe the label should be changed. I'm closing this as a duplicate of #8440.

**Closed by alecpl** 2023-05-07 06:37 UTC
